### ISSUE TITLE
アイテム名・ツールチップの不整合

### ISSUE THREAD

**Issue by NattoLover15** [defeatedcrow/HeatAndClimateMod#100]
forge-1.12.2-14.23.5.2768
HeatAndClimateLib_1.12.2-3.0.3
HeatAndClimateMod_1.12.2-3.0.7

**ツールチップ**
- ステンレスのギアボックスが「Tier 2」
- 水車のOutputが「32.0F torque/s」(特別な条件がある?)
![Watermill](https://user-images.githubusercontent.com/50796537/57983717-41d70280-7a90-11e9-9e80-f6aeb0acfa87.png)
- 風車(Tier 1)のOutputが「1 ~ 8.0F torque/s」(通気WINDで4 or 2、特別な条件がある?)
![Windmill](https://user-images.githubusercontent.com/50796537/57983750-574c2c80-7a90-11e9-933a-863577dbf987.png)
- 風車・大型風車・特大風車のツールチップに「西向きに設置したときに出力が上昇します。」とありますが、
  出力面が西、風車の向きが東(太陽が昇る方向)の際に出力が上昇しているようです。

**アイテム名**
- 黒のスペル (恐慌/Depress)・黒の上位スペル (惑乱/Hypnotic)
  恐慌が同士討ち、惑乱が装備剥がしの効果で逆になっている?
- 英語名と日本語名の逆転
  ブラックオパール=Oil Shale
  含油頁岩=Black Opal
- HeatAndClimateLib側
> dcs.tip.heat.SMELTING=STRING
- 文字抜け
> item.dcs_axe_toolsteel.name=To`o`l Steel Axe
> item.dcs_scythe_toolsteel.name=To`o`l Steel Scythe
> item.dcs_scythe_brass.name=Bras`s` Scythe
- 同テクスチャのコンテナとの違い
> tile.dcs_cont_crop_beet.name=Beets Container(Box)
> tile.dcs_cont_metal_blaze.name=Blaze Rod Container(Box)
> tile.dcs_cont_bags_soy.name=Soy Beans Bag(Bags)
> tile.dcs_cont_bags_riceseed.name=Rice Seed Bag(Bags)

また、非常に細かいですし仕様の部分もあるかもしれませんが、
langファイルを検索して気が付いた分の頭文字が小文字となっている部分を上から順に書いておきます。
> item.dcs_pattern_paper_jacket.name=Pattern Paper ([jacket])
> 
> item.dcs_gem_jadeite.name=[jadeite]
> 
> item.dcs_mechanical_induction_motor.name=Induction [motor]
> item.dcs_mechanical_gun_barrel.name=Gun [barrel]
> 
> item.dcs_food_bread_pancake_baked.name=[pancake]
> item.dcs_food_salad_natto.name=[natto]
> item.dcs_food_crops_young_soy.name=Green Soy [beans]
> 
> item.dcs_cartridge_crow.name=Decoy [balloon] Ammo
> 
> tile.dcs_build_synthetic_glass_red.name=[red] Acrylic Glass
> tile.dcs_build_claybrick_red.name=[red] Clay Brick
> 
> tile.dcs_build_shield_0.name=Commendation [shield] of the Climate
> tile.dcs_build_shield_1.name=Commendation [shield] of the Machine
> tile.dcs_build_shield_2.name=Commendation [shield] of the Magic
> 
> tile.dcs_device_water_pump_0.name=Centrifugal [pump]
> tile.dcs_device_windvane_0.name=Wind [vane]
> 
> entity.dcs.food.stew_lotusroot.name=Lotus [root] Soup
> entity.dcs.food.salad_lotusroot.name=Lotus [root] Kinpira
> entity.dcs.food.simmered_natto.name=[natto]
> entity.dcs.food.wagashi_strawberry.name=[berry] Daihuku
> 
> entity.dcs.main.big_cushion.name=Gray Big Cushion for the [lazy] [mobs]
> entity.dcs.main.big_cushion_brown.name=Brown Big Cushion for the [lazy] [mobs]
> 
> advancements.dcs_climate.metal_chamber.title=[higher] tier

**Comment by defeatedcrow** [comment]
とりあえず上から順に
要修正のものに○をつけます

- ○ ステンレスギアボックス: 直しました

- ○ 水車・風車のTooltip: 内部仕様Nerf後にチップ側を直していない例です（直しました）

- 風車の向き: F3で表示されるブロックの内部向きが西向きですので
（補足すると、マイクラの空に流れているバニラ雲に風車が向くように設置すると加速します。ネザーのように空がないDimでは下向きにつけると加速します。）

- 黒のスペル名: 仕様です。惑乱はMtGネタですので。
（主に黒のハンデス効果に惑乱・催眠の名がつけられることから取ったネタです。手札を捨てる効果のマイクラ的解釈として装備品を外させています。いわゆるA定食です。）

- ○ 翻訳系については、意図的であるもの以外は修正しておきます。

**Comment by NattoLover15** [comment]
行もメモしていたのですが、長くなり過ぎるかと思い書いていませんでした。
すでに済んでいるかもしれませんが書いておきます。

- 逆転
> 114
> item.dcs_gem_opal.name=Oil Shale
> item.dcs_gem_crude_oil.name=Black Opal

- 文字抜け
> 459
> item.dcs_axe_toolsteel.name=To`o`l Steel Axe
> 478
> item.dcs_scythe_brass.name=Bras`s` Scythe
> 483
> item.dcs_scythe_toolsteel.name=To`o`l Steel Scythe

- 同テクスチャのコンテナとの違い
> 806
> tile.dcs_cont_crop_beet.name=Beets Container(Box)
> 812
> tile.dcs_cont_metal_blaze.name=Blaze Rod Container(Box)
> 829
> tile.dcs_cont_bags_soy.name=Soy Beans Bag(Bags)
> tile.dcs_cont_bags_riceseed.name=Rice Seed Bag(Bags)

- 小文字
> 30
> item.dcs_pattern_paper_jacket.name=Pattern Paper ([jacket])
> 
> 111
> item.dcs_gem_jadeite.name=[jadeite]
> 
> 158
> item.dcs_mechanical_induction_motor.name=Induction [motor]
> 
> 166
> item.dcs_mechanical_gun_barrel.name=Gun [barrel]
> 
> 273
> item.dcs_food_bread_pancake_baked.name=[pancake]
> 
> 366
> item.dcs_food_salad_natto.name=[natto]
> 
> 417
> item.dcs_food_crops_young_soy.name=Green Soy [beans]
> 
> 510
> item.dcs_cartridge_crow.name=Decoy [balloon] Ammo
> 
> 993
> tile.dcs_build_synthetic_glass_red.name=[red] Acrylic Glass
> 
> 1013
> tile.dcs_build_claybrick_red.name=[red] Clay Brick
> 
> 1023
> tile.dcs_build_shield_0.name=Commendation [shield] of the Climate
> tile.dcs_build_shield_1.name=Commendation [shield] of the Machine
> tile.dcs_build_shield_2.name=Commendation [shield] of the Magic
> 
> 1100
> tile.dcs_device_water_pump_0.name=Centrifugal [pump]
> 
> 1111
> tile.dcs_device_windvane_0.name=Wind [vane]
> 
> 1654
> entity.dcs.food.stew_lotusroot.name=Lotus [root] Soup
> 
> 1665
> entity.dcs.food.salad_lotusroot.name=Lotus [root] Kinpira
> 
> 1670
> entity.dcs.food.simmered_natto.name=[natto]
> 
> 1687
> entity.dcs.food.wagashi_strawberry.name=[berry] Daihuku
> 
> 1721
> entity.dcs.main.big_cushion.name=Gray Big Cushion for the [lazy] [mobs]
> entity.dcs.main.big_cushion_brown.name=Brown Big Cushion for the [lazy] [mobs]
> 
> 1754
> advancements.dcs_climate.metal_chamber.title=[higher] tier

**Comment by defeatedcrow** [comment]
Fixed in afd662a514877e4c95e71e999858077a2466f704

**Comment by NattoLover15** [comment]
Bras Scytheは仕様でしたでしょうか?

**Comment by defeatedcrow** [comment]
見落としですね…
緊急性はなさそうなので次回にでも直します
