### ISSUE TITLE
"Lite" mod?

### ISSUE THREAD

**Issue by AspectSk** [defeatedcrow/HeatAndClimateMod#101]
Isnt there a way to have just the temperature mechanics? I mean why are things like muskets in here, in a climate mod with other minerals and ores which have pretty much very little to do with the name of the mod, i would to ask if there isnt a way to have just the temperature mechanics and not other things because i would like to incorporate this into my personal medieval-style modpack but the ores, minerals and other things dont fit in there, isnt there a way to maybe modify the config files or something like that to remove anything other than those temperature mechanics? Thanks in advance

**Comment by defeatedcrow** [comment]
First. SEE THE CONFIG. I already prepared module.cfg for a way to get rid of many things. You can remove almost the elements you mentioned in the config. You didn't check that.
Or, use HeatAdnClimateLib only. It is a lib mod, but has just a climatic feature. (Of course, you must make all the necessary armor and recipes yourself. Their API are also included in HaCLib.)

You're just writing a request for what you want to make, saying it's an advice.
This mod is my project. It is not a material for mod pack. Make yourself what you want.
I made muskets and minerals as I wanted. I do not follow your hobbies. I will not cooperate with you.
(Many packers are like this. I hate it.)

**Comment by AspectSk** [comment]
Sorry but i didnt say it was advice, i was just asking for help, i wasnt saying that its stupid that muskets are in there and other things but just that it wouldnt fit in my modpack and asking if there isnt a way to remove them(me removing them not you completely from the mod)
I mean i was just making fun of muskets being in a mod named heat and climate because of the name but i wasnt saying that you should completely remove them, now that i am reading this i meant it like isnt there a way to have just that thing, refering to what i can do but i get how you could get that the wrong way.
And yeah i rather did not mess in the configs much because diffirent mods have things named diffirently and i didnt know if i wouldnt mess something up by deleting things, generally thanks for the advice!
