### ISSUE TITLE
Recipe problems of Villager Trading, Spinning Machine, Hammer Mill, Crafting, and Fluid Processing

### ISSUE THREAD

**Issue by NattoLover15** [defeatedcrow/HeatAndClimateMod#103]
forge-1.12.2-14.23.5.2768
HeatAndClimateLib_1.12.2-3.0.4
HeatAndClimateMod_1.12.2-3.0.8
jei_1.12.2-4.15.0.268

貿易商人との取引で、旧バージョンのアイテムであるEXPジェムが要求されることがあるようです(引継ぎ等では入手できます)。
https://github.com/defeatedcrow/HeatAndClimateMod/blob/bf0030816d920c675d3d9e6743461b2164b03caa/main/java/defeatedcrow/hac/main/villager/HaCTradeData.java#L70

ガラ紡機のレシピに関して、藤細工ブロック:1 → 藤糸:1に修正されたようですが、
蔓の束:4 → 藤糸:4のレシピはそのままになっているようです。

ハンマーミルのレシピに関して、SUSのハンマープレートによる緑の鉱石:1 → 錫石:3のレシピが無い状態です。
https://github.com/defeatedcrow/HeatAndClimateMod/blob/afd662a514877e4c95e71e999858077a2466f704/main/java/defeatedcrow/hac/machine/recipes/MachineCrusherRecipe.java#L84
また、エンドストーン増殖レシピはハンマーミルにも存在するようです(確認・言葉不足で申し訳ありません)。

現在作成レシピが確認できないアイテム
**液体加工レシピ**
- イカスミリゾット
https://github.com/defeatedcrow/HeatAndClimateMod/search?q=%22foodSquid%22

- キノコのアヒージョ
https://github.com/defeatedcrow/HeatAndClimateMod/search?q=%22cropMushroom%22

**クラフト**
- 生のポテトと魚のキッシュ
https://github.com/defeatedcrow/HeatAndClimateMod/search?q=%22foodFish%22

- 黒のしずく×3
https://github.com/defeatedcrow/HeatAndClimateMod/search?q=%22oreCrudeOil%22

- 戦闘服
https://github.com/defeatedcrow/HeatAndClimateMod/search?q=%22ingotTitanium%22

これでJEIに表示されるアイテムのレシピは恐らく一通り確認できたと思います。

**Comment by defeatedcrow** [comment]
ご報告ありがとうございます。
7534efc23cc2013fab2257a54988b4453ebbbd8f で修正されました。

**Comment by NattoLover15** [comment]
対応ありがとうございます。
