### ISSUE TITLE
TileFluidProcessorBase showing wrong fluids in server

### ISSUE THREAD

**Issue by Snownee** [defeatedcrow/HeatAndClimateMod#108]
I poured milk in a steel pot and then got oil on gui.

**Comment by defeatedcrow** [comment]
Fluid ID is managed by an external file in the config folder. This is used for communication between the server and client, so it will be displayed incorrectly if there is a discrepancy between the server and client.
There is currently no plan to fix this.

**Comment by Snownee** [comment]
Could you please tell me why there are Fluid IDs? Why not serializing FluidStack directly?

**Comment by defeatedcrow** [comment]
The GUI progress bar (IInventory# get/setField) needs a numeric ID. These do not correspond to handling FluidStack directly.
When I ported this feature from AMT2, the numeric ID was already removed, so I made it myself. That's all.

**Comment by Snownee** [comment]
OK I got that. I think you do not have to implement IInventory. if you implement IInventory, you do not have to make every data in field.

**Comment by defeatedcrow** [comment]
What does that mean?
Many machines in this mod have an inventory. (Of course it needs to handle ItemStack and Slot.) This looks like unrealistic advice. Or is it just ironic?

**Comment by Snownee** [comment]
No. Just overriding getCapability and hasCapability can implement all the logics.

**Comment by defeatedcrow** [comment]
Capability is not a feature for server-client communication. They require a another communication method.
(Field of IInventory is a communication function between GUI-Container compatible with ICraftig of old version. It is different.)
Well, there are other ways to send and receive NBT while the player is opening the GUI. Anyway. I may consider it.
