### ISSUE TITLE
[バグ]食べ物エンティティが一致しない

### ISSUE THREAD

**Issue by ym1025** [defeatedcrow/HeatAndClimateMod#111]
クリエイティブタブにある食べ物をエンティティとして設置したとき、すべてとんかつになります。ドロップするものもとんかつです。
バージョン:1.12.2
HaC:1.12.1_3.1.0
HacLib:3.1.0
Forge:14.23.5.2838
動画:https://youtu.be/OLQVXVQlqM0
Modリスト:https://pastebin.com/K631jXB9

**Comment by defeatedcrow** [comment]
https://github.com/defeatedcrow/HeatAndClimateMod/commit/5c8b95e55e5c6c587d50ea9355c0c163096aca74 で未実装アイテムをクリエイティブタブから除去しました。ご報告ありがとうございました。
