### ISSUE TITLE
Lost Empty Steak Plate by right click

### ISSUE THREAD

**Issue by NattoLover15** [defeatedcrow/HeatAndClimateMod#113]
forge-1.12.2-14.23.5.2768
HeatAndClimateLib_1.12.2-3.1.1
HeatAndClimateMod_1.12.2-3.1.1

ステーキ皿を手に持って空中に右クリックするとスタックごと消滅するようです。

**Comment by defeatedcrow** [comment]
6d7518d で修正しました。
