### ISSUE TITLE
Startup crash by DisableOldMaterials config true

### ISSUE THREAD

**Issue by NattoLover15** [defeatedcrow/HeatAndClimateMod#114]
forge-1.12.2-14.23.5.2768
HeatAndClimateLib_1.12.2-3.1.1
HeatAndClimateMod_1.12.2-3.1.1

module.cfgのB:DisableOldMaterials=をtrueにすると起動時にクラッシュします。

クラッシュレポート
https://pastebin.com/Hny2ex3G

**Comment by defeatedcrow** [comment]
6d7518d で修正しました。
ご報告ありがとうございます。

**Comment by NattoLover15** [comment]
HeatAndClimateMod_1.12.2-3.1.2

HeatAndClimateModの更新後もクラッシュが発生するようです。

クラッシュレポート
https://pastebin.com/CJXbeLPN
