### ISSUE TITLE
Reversed armor slot in entity inventory GUI

### ISSUE THREAD

**Issue by NattoLover15** [defeatedcrow/HeatAndClimateMod#115]
forge-1.12.2-14.23.5.2768
HeatAndClimateLib_1.12.2-3.1.1
HeatAndClimateMod_1.12.2-3.1.1

エンティティ・村人のGUIの頭/胴体/脚/足スロットが足/脚/胴体/頭防具の順にずれて対応しているようです。
![Issue_EntityInventoryGUI](https://user-images.githubusercontent.com/50796537/61579496-be459a80-ab40-11e9-9c84-738a95ab4b17.png)
![Issue_VillagerInventoryGUI](https://user-images.githubusercontent.com/50796537/61579497-c271b800-ab40-11e9-89a7-2e43dc0ae423.png)

**Comment by defeatedcrow** [comment]
6d7518d で修正しました。

**Comment by NattoLover15** [comment]
HeatAndClimateMod_1.12.2-3.1.2

HeatAndClimateModの更新後も違う順番でスロットのずれがあるようです。
![Issue_EntityInventoryGUI_3 1 2](https://user-images.githubusercontent.com/50796537/62135652-8c40ef00-b31d-11e9-9684-bdaf67f38c33.png)

また、メインハンドスロットと頭スロットが同期しており、
村人のGUIでスロットをShiftクリックするとアイテムが2倍になります。

アイテム設置前
![Issue_VillagerInventoryGUI_3 1 2_1](https://user-images.githubusercontent.com/50796537/62135708-a7abfa00-b31d-11e9-8b0c-7c698f9e61ae.png)

アイテム設置後
![Issue_VillagerInventoryGUI_3 1 2_2](https://user-images.githubusercontent.com/50796537/62135772-c14d4180-b31d-11e9-9590-b7269c7bcdae.png)

Shiftクリック後
![Issue_VillagerInventoryGUI_3 1 2_3](https://user-images.githubusercontent.com/50796537/62135840-e477f100-b31d-11e9-9d2b-c1fa94da79db.png)

**Comment by NattoLover15** [comment]
HeatAndClimateMod_1.12.2-3.1.3

対応ありがとうございます。
