### ISSUE TITLE
Some mistaken strings

### ISSUE THREAD

**Issue by NattoLover15** [defeatedcrow/HeatAndClimateMod#116]
forge-1.12.2-14.23.5.2768
HeatAndClimateLib_1.12.2-3.1.1
HeatAndClimateMod_1.12.2-3.1.1

- ja_jp.lang

(SMELTING)
https://github.com/defeatedcrow/HeatAndClimateMod/blob/5c8b95e55e5c6c587d50ea9355c0c163096aca74/main/resources/assets/dcs_climate/lang/ja_jp.lang#L1736

(地底)
https://github.com/defeatedcrow/HeatAndClimateMod/blob/5c8b95e55e5c6c587d50ea9355c0c163096aca74/main/resources/assets/dcs_climate/lang/ja_jp.lang#L1738

- en_us.lang

(Vines)
https://github.com/defeatedcrow/HeatAndClimateMod/blob/5c8b95e55e5c6c587d50ea9355c0c163096aca74/main/resources/assets/dcs_climate/lang/en_us.lang#L424

(Seaweed)
https://github.com/defeatedcrow/HeatAndClimateMod/blob/5c8b95e55e5c6c587d50ea9355c0c163096aca74/main/resources/assets/dcs_climate/lang/en_us.lang#L1224-L1227

Black・White以外の部分が逆転
https://github.com/defeatedcrow/HeatAndClimateMod/blob/5c8b95e55e5c6c587d50ea9355c0c163096aca74/main/resources/assets/dcs_climate/lang/en_us.lang#L1881
https://github.com/defeatedcrow/HeatAndClimateMod/blob/5c8b95e55e5c6c587d50ea9355c0c163096aca74/main/resources/assets/dcs_climate/lang/en_us.lang#L1883

- その他

紙パックのみゲーム内日本語でFluid is empty: empty
https://github.com/defeatedcrow/HeatAndClimateMod/blob/7534efc23cc2013fab2257a54988b4453ebbbd8f/main/java/defeatedcrow/hac/food/item/ItemFluidPack.java#L192

Soupのみゲーム内日本語でもPlaceable as an Entity
https://github.com/defeatedcrow/HeatAndClimateMod/blob/7534efc23cc2013fab2257a54988b4453ebbbd8f/main/java/defeatedcrow/hac/food/item/PlateSoupItem.java#L93
https://github.com/defeatedcrow/HeatAndClimateMod/blob/7534efc23cc2013fab2257a54988b4453ebbbd8f/main/java/defeatedcrow/hac/food/item/PlateMeatItem.java#L118

**Comment by defeatedcrow** [comment]
>dcs.info.desc.cube_red=赤のキューブは、UHT以上の温度の場所で活性化します。 

せっかくなので表示に仕様を合わせます。

>紙パックのみゲーム内日本語でFluid is empty: empty

仕様
（正しく空であるかのチェック機構を兼ねているので）

他は 6d7518d で修正されました。
