### ISSUE TITLE
[Suggestion] Add option to disable Highway Robber or add excluded entities

### ISSUE THREAD

**Issue by Prunoideae** [defeatedcrow/HeatAndClimateMod#117]
The enchantment Highway Robber V is extremely powerful and fun, but in circumstances like PVP or some other things (Like spawning mobs with late game armor and weapons to increase difficulty), this could be something really dangerous.
So is it possible to add an option to disable the enchantment, or to disable it on some entities (Like EntityPlayer or EntityZombie)? 
Many thanks.

**Comment by defeatedcrow** [comment]
At 6d7518d, added the config of disable HaC enchantment effects.
Thank you!
