### ISSUE TITLE
Server crash when using HaC pickaxes and axes

### ISSUE THREAD

**Issue by RisingInIris2017** [defeatedcrow/HeatAndClimateMod#118]
Forge Version: 1.12.2 - 14.23.5.2838
HaC Lib version: HeatAndClimateLib_1.12.2-3.1.0
HaCMod version: HeatAndClimateMod_1.12.2-3.1.0

Here are two crash-report:
1. https://paste.ubuntu.com/p/QXBykKfCgD/
2. https://paste.ubuntu.com/p/jBdw9tnXKk/
Server is using Catserver, a 1.12.2 Forge+Bukkit server, just like Cauldron server.
You may find some useful information here: https://github.com/CatServer/CatServer

I will provide further information if you need.
Thanks a ton in advance!

**Comment by defeatedcrow** [comment]
It fixed at https://github.com/defeatedcrow/HeatAndClimateMod/commit/6d7518de23ea69c2cf8e8e4ccd47509259cf5559.
Thank you!
