### ISSUE TITLE
Render problems of Kuzuyu and Gazpacho

### ISSUE THREAD

**Issue by NattoLover15** [defeatedcrow/HeatAndClimateMod#122]
forge-1.12.2-14.23.5.2768
HeatAndClimateLib_1.12.2-3.1.1
HeatAndClimateMod_1.12.2-3.1.2

葛湯・ガスパチョを設置した際に下部分が地面に埋まります。
![Issue_entityFoods_drink](https://user-images.githubusercontent.com/50796537/62413322-de994d00-b648-11e9-8c62-91759fcc7feb.png)

**Comment by defeatedcrow** [comment]
9e7cf0d で修正しました。
ご報告ありがとうございました！

**Comment by NattoLover15** [comment]
対応ありがとうございます。
