### ISSUE TITLE
Conflict Mill Recipe of Sand

### ISSUE THREAD

**Issue by NattoLover15** [defeatedcrow/HeatAndClimateMod#124]
forge-1.12.2-14.23.5.2768
HeatAndClimateLib_1.12.2-3.1.1
HeatAndClimateMod_1.12.2-3.1.3
jei_1.12.2-4.15.0.268

3.1.3にてJEIで石臼の砂 → 粘土:1+石灰_50%のレシピが表示されるようになりましたが、
実際の石臼では既存の砂 → 石英の粉:1+ホウ砂_50%のレシピが優先されるようです。
![issue_MillRecipe_Sand](https://user-images.githubusercontent.com/50796537/62629237-c5a1dc00-b967-11e9-99e7-5945c1301282.png)
![issue_Interface_Mill_Sand](https://user-images.githubusercontent.com/50796537/62629281-d3eff800-b967-11e9-8b39-29dcaad2e7f0.png)

**Comment by defeatedcrow** [comment]
既存のレシピの方を残したいので、現状で一応動作は正常に動いています
（追加したレシピは次の更新で削除します）

**Comment by NattoLover15** [comment]
レシピ変更を確認しました、対応ありがとうございます。
