### ISSUE TITLE
I need to know where to find....but I can't log into curseforge due to expired oauth token

### ISSUE THREAD

**Issue by JadianRadiator** [defeatedcrow/HeatAndClimateMod#126]
I need to know where to find the source/bug tracker for Dynamic Trees - Heat and Climate Compat.
I can't ask on CurseForge because [CurseForge's oauth token has expired](https://twitter.com/JadianRadiator/status/1179720810350731264).
I need their bug tracker page, because I found the cause and solution of the addon reporting the wrong version.

**Comment by defeatedcrow** [comment]
I am not the author of the add-on and I am not involved in the project. So I don't have permission to edit the page. There is nothing I can do.

Contact the correct author.

**Comment by JadianRadiator** [comment]
How do I strike out text?
[_This page_](https://forum.proxmox.com/threads/permission-denied-invalid-csrf-token-401.34961/) made me think to use the "forget this site" on curseforge and twitch.
So that's working now.
Sorry for bothering you.

I wasn't asking you to fix.
I know you have nothing to do with it.
I asked you where I can contact the people for it.
As I can't ask him because web browser side of curseforge can't oauth with twitch.
It gives a 401 error message saying "invalid csrf token" when it tries and fails to kick back over to CurseForge/

**Comment by defeatedcrow** [comment]
I don't have any interaction with him, he seems to have an account on github. How about trying this?
I don't know if he's still active. sorry.

https://github.com/odorousrex
