### ISSUE TITLE
Better With Mods integration

### ISSUE THREAD

**Issue by LEWeee** [defeatedcrow/HeatAndClimateMod#128]
https://www.curseforge.com/minecraft/mc-mods/bwm-suite
Better With Mods is another mod adding mechanical power. I think that since both of these mods explore a lot of the same themes, some compatibility measures should be taken between the two. This can done by either:

a) making BWM machines should be able to work with HaC torque and generate torgue or
b)making  HaC machines should be able to work with BWM gearpower

**Comment by defeatedcrow** [comment]
The mod is only “looks similar” and has little in common with HaC internally. HaC works with industrial mods and supports RF. Other energy is not supported. Also, It seems to have no advantage.

Both mods expose the energy API, so it is recommended that anyone who needs them create an Addon on their own.
