### ISSUE TITLE
Lost recipes of Pumpkin Box, Garlic Basket and Pancake Tower

### ISSUE THREAD

**Issue by NattoLover15** [defeatedcrow/HeatAndClimateMod#129]
forge1.12.2-14.23.5.2847
HeatAndClimateLib_1.12.2-3.1.1
HeatAndClimateMod_1.12.2-3.1.5
jei_1.12.2-4.15.0.292

カボチャ箱・ニンニクのバスケット・パンケーキと蜂蜜が作成不能になっています。
また、焼いたモツ串の気候精錬レシピがJEIに表示されないようです(作成自体は可能)。

**Comment by defeatedcrow** [comment]
f6c96ad29a8d9fab45d3d050c6d0381015a9bf91 で修正しました。
ご報告ありがとうございました！

**Comment by NattoLover15** [comment]
HeatAndClimateMod_1.12.2-3.1.6で修正を確認しました、対応ありがとうございます。
