### ISSUE TITLE
Setting the number of generation of buildings (mills)

### ISSUE THREAD

**Issue by SeagalKru** [defeatedcrow/HeatAndClimateMod#130]
Hello!
I really liked your mod and I use it on my server. But I do not like that very often (close) mills are generated. And I could not figure out where to set this indicator so that they are generated with less quantity?
[https://drive.google.com/open?id=1OdhnePG0FspSK8ZrLh36OdeGCvgLM1mN](url)

**Comment by defeatedcrow** [comment]
Hello SeagalKru.

The generation probability of windmills can be reduced by changing "Windmill Gen Probability" in worldgen.cfg.

**Comment by SeagalKru** [comment]
Oh! Found! Thank you! ;)
