### ISSUE TITLE
Crash upon creating world

### ISSUE THREAD

**Issue by Rongmario** [defeatedcrow/HeatAndClimateMod#131]
Crash: https://paste.dimdev.org/poviwizowo.mccrash

I'm using OpenJ9 u242.

**Comment by Rongmario** [comment]
Same with Oracle.

**Comment by defeatedcrow** [comment]
Confirmed the normal operation on Oracle Java (1.8.0_231 latest) and Forge2847. I can't see a similar crash. Sorry.
This mod is developed in Oracle Java and is not supported for OJ9. Please use at your own risk.

**Comment by Rongmario** [comment]
Happens in Oracle Java too:
[crash-2019-12-25_00.51.11-server.txt](https://github.com/defeatedcrow/HeatAndClimateMod/files/4000541/crash-2019-12-25_00.51.11-server.txt)

**Comment by defeatedcrow** [comment]
Looks like a crash because multiple coremods change the same method. However, this log does not reveal any conflicts.
This mod is (in principle) supported to work with the recommended Forge and plugin targets (specified in the readme). In the case of coremod conflicts, conflicts cannot be avoided and we will take action, but we do not promise to fix them.

**Comment by defeatedcrow** [comment]
In https://github.com/defeatedcrow/HeatAndClimateLib/commit/c03aa11ca114b5de9cbdee8c9b8ad39fcbbaa954 , added config for core mod. This can stop the crashing MethodTransformer. This is a temporary measure.

**Comment by Rongmario** [comment]
I'll try build it if there's no releases out, what would disabling the coremod do?

**Comment by defeatedcrow** [comment]
Oh, sorry to wrong update in curseforge.
New file is [here](https://github.com/defeatedcrow/HeatAndClimateLib/releases/tag/v3.2.2) now. This version creates a new file "dcs_asm.cfg". This is the config file for controlling coremod. 
They stop only the coremod override of the specified part, and limit the functions that require it.
For example, in the crash you presented, HaC failed to override World#canBlockFreezeBody. If this is stopped, the function for freezing the water block will be limited. And you may be able to play the mod without affecting the rest.
