### ISSUE TITLE
Waila fails to display HAC's entity info

### ISSUE THREAD

**Issue by RisingInIris2017** [defeatedcrow/HeatAndClimateMod#132]
#### Mod version:

HACLib version: HeatAndClimateLib_1.12.2-3.2.0
HAC version: HeatAndClimateMod_1.12.2-3.2.0
Waila(Hwyla) version: Hwyla-1.8.26-B41_1.12.2

#### Forge version:

forge-1.12.2-14.23.5.2847

#### Singleplayer or Multiplayer:

Singleplayer

#### Installed mods:

![](https://camo.githubusercontent.com/b57ccf42abbdc8dfbc5fdda91b8d9ad627538c0c/68747470733a2f2f73322e617831782e636f6d2f323031392f31322f32392f6c6e784835462e706e67)

#### How to reproduce:

Simply point at an entity using mouse, and you can see an \<ERROR\> in Waila's information box.

#### Pictures:

Four pictures. Link: https://imgur.com/gallery/DE8KfEz
A link to WailaErrorOutput.txt: https://paste.ubuntu.com/p/5QG7cY8nmS/

**Comment by defeatedcrow** [comment]
Thanks for the report!
It fixed at https://github.com/defeatedcrow/HeatAndClimateMod/commit/3dc9c4636893e0fa32433db252b4d555605a2908.

The new version is [here](https://github.com/defeatedcrow/HeatAndClimateMod/releases/tag/v3.2.2) now. Please try it.

**Comment by RisingInIris2017** [comment]
Bug is fixed!
Thanks to dear crow-chan :)
