### ISSUE TITLE
=Duplicate mod=: after updating through the Twitch launcher.

### ISSUE THREAD

**Issue by SeagalKru** [defeatedcrow/HeatAndClimateMod#133]
In my opinion, the same mod impersonates another in one of the updates! ;)
[latest.log](https://github.com/defeatedcrow/HeatAndClimateMod/files/4008637/latest.log)

**Comment by defeatedcrow** [comment]
Really sorry about it!
The file updated to curseforge was incorrect. Currently replaced with a new file.

**Comment by SeagalKru** [comment]
Well, great! What would you do without us testers ?! ;) Happy New Year! ;)
