### ISSUE TITLE
Server crash: Attempted to set villager profession to unregistered profession: -1 null

### ISSUE THREAD

**Issue by RisingInIris2017** [defeatedcrow/HeatAndClimateMod#134]
#### Mod version:

Lib Version: HeatAndClimateLib_1.12.2-3.2.2
Mod Version: HeatAndClimateMod_1.12.2-3.2.2

#### Forge version:

14.23.5.2847

#### Singleplayer or Multiplayer:

Multiplayer, using [Catserver](https://github.com/Luohuayu/CatServer).

#### Installed mods:

![20200108235700](https://user-images.githubusercontent.com/28519848/71993794-a985cc00-3272-11ea-8d20-719fe4bf177a.png)

## Link to full crash log

https://paste.ubuntu.com/p/fxb9QXqmwc/

## Description of the problem
Some players randomly walk in the Overworld and suddenly server crashes.
This problem I mentioned above keeps occurring for more than 50 times, after I modified this line in config\defeatedcrow\climate\module.cfg:
`B:EnableVillager=true`
I modified this to false on server side, but client side was still true.
May the difference of module.cfg between server and client lead to this issue?
I am not sure. Maybe this is my issue, rather than yours  :(

Besides, I have enabled Forge's error entities removing mechanic by modifying the forge.cfg:
`B:removeErroringEntities=true`
on server side, but this issue still occurs.

Look forward your reply.
Thanks in advance!

**Comment by defeatedcrow** [comment]
Thanks for the report!
I'm sorry about my mistake. This crash is caused by Caravansaray generation calling a removed villager by the "EnableVillager" setting. I'll fix it in the next version.

**Comment by defeatedcrow** [comment]
Fixed the issue and uploaded a new version! please try it.
https://github.com/defeatedcrow/HeatAndClimateMod/releases/tag/v3.2.4

**Comment by RisingInIris2017** [comment]
> Fixed the issue and uploaded a new version! please try it.
> https://github.com/defeatedcrow/HeatAndClimateMod/releases/tag/v3.2.4

Thanks a lot! I think this issue has been solved now :)
