### ISSUE TITLE
土レンガが固すぎる

### ISSUE THREAD

**Issue by ym1025** [defeatedcrow/HeatAndClimateMod#141]
何を使っても土レンガが固いのですが、これは仕様ですか？

**Comment by defeatedcrow** [comment]
仕様です
固さはバニラ鉱石と同値なので特別固くはないですよ
ただしCLAY属性（マテリアルは粘土）なので適性ツールはシャベルです、ツルハシで壊そうとすると遅いと思います

（石属性にすると素手破壊で何も落とさなくなるので、粘土にしてあります
　つまりめちゃくちゃ硬い粘土です）

追記：バニラ仕様がCLAY属性をシャベル適性にしていないことが発覚したので、次回更新で素手破壊可能なツルハシ適性マテリアルの新設を検討します…
結構大掛かりな改変になりそうなので、次回で直っているかはわかりませんが

**Comment by defeatedcrow** [comment]
commit 83768b2bf35db832c48a7314b430fd9742c8dc0a で素手破壊可能・ツルハシ適性に設定されました。
ご報告ありがとうございました！
