### ISSUE TITLE
Client crash: IllegalStateException: Unable to get Y-rotated facing of up

### ISSUE THREAD

**Issue by RisingInIris2017** [defeatedcrow/HeatAndClimateMod#142]
#### Mod version:
HaCLib Version: HeatAndClimateLib_1.12.2-3.2.4
HaCMod Version: HeatAndClimateMod_1.12.2-3.2.6

#### Forge version:

forge-1.12.2-14.23.5.2847

#### Singleplayer or Multiplayer:

Both singleplayer and multiplayer.

#### Installed mods:
![TIM截图20200209210415](https://user-images.githubusercontent.com/28519848/74102622-5a3bff80-4b80-11ea-8243-81de5d380a78.png)

## Link to full crash log
https://paste.dimdev.org/tilibeyonu.mccrash

#### How to reproduce:

1. Use a Wrench to right click a steel shaft.
2. Game crashes immediately.
3. Use WorldEdit to remove that shaft, game stops crashing.

Looks forward to your reply!
Thanks in advance!

**Comment by defeatedcrow** [comment]
Thank you for the report!
The crash was fixed in v3.2.7.

**Comment by RisingInIris2017** [comment]
Hooray! 🎉 
I will have a try! Thanks for your effort!

**Comment by RisingInIris2017** [comment]
This issue is fixed! Thanks for your effort again!

**Comment by defeatedcrow** [comment]
Thanks too. please enjoy!
