### ISSUE TITLE
Game crash HaC and Optifine related: ArithmeticException: / by zero

### ISSUE THREAD

**Issue by RisingInIris2017** [defeatedcrow/HeatAndClimateMod#144]
#### Mod version:
HaCLib Version: HeatAndClimateLib_1.12.2-3.2.5
HaCMod Version: HeatAndClimateMod_1.12.2-3.2.7
Optifine Version: OptiFine_1.12.2_HD_U_F5

#### Forge version:

forge-1.12.2-14.23.5.2847

#### Singleplayer or Multiplayer:

Both singleplayer and multiplayer.

#### Installed mods:
![modlist](https://user-images.githubusercontent.com/28519848/74581097-4d873380-4fe6-11ea-9eb1-38614a2aa139.png)

## Link to full crash log
https://paste.dimdev.org/danekodohi.mccrash

## Description of the problem
One player of my modpack reported that:
He stood by an HaC Crusher.
He intended to open an HaC Steel Chest near him, but game crashed just at the moment before he could open the chest.
So no HaC's GUI was opened according to his report.

I know that Optifine is a close source project, so any issue related to it is much more difficult.
But I do still need your help, or your explanation.

Looks forward to your reply!
Thanks in advance, and thanks for your consistent help! :heart:

**Comment by defeatedcrow** [comment]
Thanks for your report!
In e2f4bb1, the divide by zero that caused the crash was removed. It is probably fixed!

**Comment by RisingInIris2017** [comment]
After so many days' testing, I may confirm that this issue has been fixed.
Thank you dear crow-san! ❤️
