### ISSUE TITLE
Block duplication with scaffold blocks

### ISSUE THREAD

**Issue by Prunoideae** [defeatedcrow/HeatAndClimateMod#146]
![2020-03-11_22 38 36](https://user-images.githubusercontent.com/24620047/76429973-bb0e6000-63ea-11ea-95c4-83e36aed79ec.png)
![2020-03-11_22 38 48](https://user-images.githubusercontent.com/24620047/76429977-bd70ba00-63ea-11ea-8016-c7ab0b9cc313.png)
![VMBF2 V1IHR@656HAXW ${6](https://user-images.githubusercontent.com/24620047/76429985-bfd31400-63ea-11ea-807b-1987b248cc8b.png)

On version 3.3.0.
Steps to reproduce:
1. Place a 1x3x1 column with scaffold.
2. Right click scaffold with any block holding in hand.
3. The center scaffold block is not replaced, but the upper one and the lower one will be, causing the block to be replicated.

**Comment by defeatedcrow** [comment]
The same phenomenon has not been reproduced. If reproducibility is confirmed, I'll consider modification.
![2020-03-13_20 18 47](https://user-images.githubusercontent.com/6741099/76616789-26317100-6568-11ea-8962-6c5a01049f10.png)

**Comment by Prunoideae** [comment]
> The same phenomenon has not been reproduced. If reproducibility is confirmed, I'll consider modification.

Some friends of mine haven't reproduced it either, considering it to be a bug caused by mod interaction or something else.
