### ISSUE TITLE
Infinite energy from Induction Rotor Block

### ISSUE THREAD

**Issue by Prunoideae** [defeatedcrow/HeatAndClimateMod#147]
Induction Rotor Block use tag dcs.Ecash to store additional energy drained from RF provider, but it seems that the dcs.Ecash tag is never reduced, so the energy will not be further drained once it met the maximum number of 1280, which means that it will run forever.
![image](https://user-images.githubusercontent.com/24620047/76432738-581ec800-63ee-11ea-84de-66e30c790e30.png)
I removed the provider below and wait a few minutes for it, but it still stay at 1280.

**Comment by defeatedcrow** [comment]
Kinetic motors reduce internal cash according to the energy consumption at the destination of the torque. If there is no energy consumption at the destination, idle at 1280.

It works fine in the author's test play, and your guess that Ecash does not decrease is wrong.

https://github.com/defeatedcrow/HeatAndClimateMod/blob/1.12.2_v3/main/java/defeatedcrow/hac/machine/block/TileKineticMotor.java#L42

**Comment by Prunoideae** [comment]
> It works fine in the author's test play, and your guess that Ecash does not decrease is wrong.

That's quite strange... A friend of mine who's hosting a server told that he also met this problem, and have to remove the recipe of KineticMotor every time he starts a modpack with HAC...

**Comment by defeatedcrow** [comment]
In the supported environment (that includes the mod mentioned in ReadMe as Compat), there is no problem with my verification environment for both single and multi play. Also, there is no similar report so far.

I don't seem to have a way to reproduce it, as there is no clarification of your verification environment, but for now I put on hold this as unverified information.
