### ISSUE TITLE
Thermal expansion - 5.5.4.43 & Immersive engineering 0.12-92 - [Issues with creosote oil & Ethanol]

### ISSUE THREAD

**Issue by Devalut** [defeatedcrow/HeatAndClimateMod#151]
I'm not sure if the issue with creosote would any of your concern or the author of thermal expansion , in any case I'll post this here: 

Creosote oil is displayed as viable source of fuel in H&C JEI recipe however bucket filling does not work and filling the respected machines with fuel via pipe results in no action, oddly enough, removing Thermal expansion seems to work.

Ethanol fluid is simply not compatible with Immersive engineering equivalent, nor is  it or numerous fluids from immersive engineering (or petroleum) as viable a fuel.

**Comment by defeatedcrow** [comment]
Hello, Devault. 

First, liquids do not have Forge-supported dictionary features (such as the ore dictionary). Therefore, there is no compatibility. All liquids compatibility "manually" have added by modder.
For IE, I have not made it.
(HaC compatibility is only for the mods shown [here](https://github.com/defeatedcrow/HeatAndClimateMod/blob/1.12.2_v3/main/resources/ReadMe_Plugin.txt). It's imcomplete for other fluids.)

About TF creosote, (note: that added in Thermal Foundation, not Thermal Expantion,) it registered as fuel for HaC. Operation has been confirmed. Also, some HaC machines require gas and cannot use creosote.

**Comment by Devalut** [comment]
Hello esteemed creator!
Thank you for the explanation, I had no idea it was caused by foundation (as it wouldn't let me run it without both.)

As for creosote perhaps you can share the version of Thermal dynamics so that I may downgrade and use that instead otherwise in the version listed:
- filling it with a bucket of creosote results in opening the GUI instead
- forcing the fluid via tank allows for the fluid to placed in but the machine doses not function ("stopping")
![Screenshot_27](https://user-images.githubusercontent.com/20247202/78412171-41bbf480-75c7-11ea-8623-79d5bf0b1457.png)

Offtopic:
- love the mods, thanks so much for making this mod!
- why doesn't fuel burner or gas stove have a switch to turn off via right click?

**Comment by defeatedcrow** [comment]
From the situation, I think there are other mods that add a liquid of the same name "creosote". Probably I can handle this and will fix it in the next update.

The fuel burner is controlled by the RS signal as the RS signal is better for automation than a right-click.
