### ISSUE TITLE
Transfer Portal tooltips, behavior, and GUI inconsistencies

### ISSUE THREAD

**Issue by NattoLover15** [defeatedcrow/HeatAndClimateMod#152]
forge1.12.2-14.23.5.2847
HeatAndClimateLib_1.12.2-3.3.0
HeatAndClimateMod_1.12.2-3.3.1
Hwyla-1.8.26-B41_1.12.2
jei_1.12.2-4.15.0.293

転送ポータルのツールチップ・動作・GUI表示・テクスチャの条件にずれがあるようです。

- ツールチップ
「ABSOLUTE または液体窒素のどちらかが必要です。」

- 気温CRYOGENIC時のGUI表示・ブロックテクスチャ
「適温」・空色

- 気温ABSOLUTE時のGUI表示・ブロックテクスチャ
「気温ABSOLUTEまたは液体窒素が必要です」・黒色

- 実際の動作
ABSOLUTE・CRYOGENICのどちらでも転送

![issue_TransferPortal_ABSOLUTE](https://user-images.githubusercontent.com/50796537/78500595-4ed90f00-7792-11ea-9e91-699bf5691dc4.png)
![issue_TransferPortal_CRYOGENIC](https://user-images.githubusercontent.com/50796537/78500599-53052c80-7792-11ea-81d4-c83720e7583b.png)

**Comment by defeatedcrow** [comment]
・動作はCRYOGENIC以下で動くのが正しい仕様です（ツールチップを修正します）
・マシンの色は温度の適正を示すものではありません。温度の適正&エネルギーの残量の両方が適正値の場合にテクスチャが変化します
（サーバー・クライアント間でパケットのやり取りをしつつのマシンのため、特にマルチ環境ではマシンの状態に即した表示は保証できません）

**Comment by defeatedcrow** [comment]
a96474b で修正しました。
動作・表示ともにCRYOGENIC以下で動きます。

**Comment by NattoLover15** [comment]
修正を確認しました。対応ありがとうございます。
