### ISSUE TITLE
Raven and Armadillo Gauntlet malfunction

### ISSUE THREAD

**Issue by NattoLover15** [defeatedcrow/HeatAndClimateMod#153]
forge1.12.2-14.23.5.2847
HeatAndClimateLib_1.12.2-3.3.0
HeatAndClimateMod_1.12.2-3.3.1
Hwyla-1.8.26-B41_1.12.2
jei_1.12.2-4.15.0.293

カラスのガントレット・アルマジロのガントレットが正常に動作していないようです。

- カラスのガントレット
石臼レシピにおいて確率で副産物か出るブロックを破壊した際、
プレイヤーの移動除くチェストの開閉・エンティティ・
攻撃・水流・採掘時のドロップ等の動作が停止する。
(クラッシュはせず、セーブしてタイトルへ戻ることができずにMinecraftがフリーズする)

![issue_RavenGauntlet](https://user-images.githubusercontent.com/50796537/78500907-37028a80-7794-11ea-8d98-69c542dc78ad.png)

- アルマジロのガントレット
オフハンドに持って攻撃しても一切回復しない

![issue_ArmadilloGauntlet](https://user-images.githubusercontent.com/50796537/78500914-3b2ea800-7794-11ea-882a-7e9c8554d920.png)

**Comment by defeatedcrow** [comment]
＞カラスのガントレット
状況を見るに、サーバー側でクラッシュが生じてクライアントのみが取り残された動作をしています
（恐らくサーバー側はクラッシュレポートかエラーログを吐いていると推測されます。）
報告内容から使用状況・不具合を特定できないので、作者環境で再現が取れた場合のみ修正します。

＞アルマジロのガントレット
不具合箇所を特定できたので、次回更新で修正します。

**Comment by defeatedcrow** [comment]
a96474b で修正しました。

**Comment by NattoLover15** [comment]
修正を確認しました。対応ありがとうございます。
