### ISSUE TITLE
Strange date displayed on Climate Info HUD after second year

### ISSUE THREAD

**Issue by Iunius118** [defeatedcrow/HeatAndClimateMod#154]
2年目以降のワールドで気候HUDに表示される日付がおかしくなります。

**確認環境**

- forge-1.12.2-14.23.5.2847
- HeatAndClimateLib_1.12.2-3.3.0
- HeatAndClimateMod_1.12.2-3.3.2
- jei_1.12.2-4.15.0.291
- Hwyla-1.8.26-B41_1.12.2

**詳細**

HeatAndClimateの暦で2年目以降のワールドでは、その季節の日付に経過した年数分の日数を加算したものが現在の日付として気候HUDに表示されます。

例えばコンフィグがデフォルトの場合、HUDに表示される日付は以下のようになります。

- 2年目 春 1日→SPRING Day 241
- 2年目 春 61日→SPRING Day 301
- 2年目 夏 1日→SUMMER Day 241

この日付は2年目以降も1日なら`Day 1`のように表示されている方が適当だと感じます。
また可能でしたらHUDに年数を、例えば2年目なら`Year 2`のように表示する機能が欲しいです。

**Comment by defeatedcrow** [comment]
2年目以降に日付がリセットする機能は一応検討します
（その場合、プレイ開始からの累積日数が確認できなくなるので、累積日数を確認する代替方法が必要になります、それも含めて検討課題ですね…）

ただし、開始季節を選べるコンフィグを実装予定であり、一年の周期、開始季節、季節の範囲設定などを弄った場合に累積日数の表示をそのように変更するとバグの温床になるので、あなたが適切だと感じるアイデアは私にとってそうであるとは限りませんし、選ばれない可能性があります、ご了承ください
（自作してPR、ということであれば歓迎しますが）

**Comment by Iunius118** [comment]
返答いただいた内容に納得しました。
ありがとうございます。
