### ISSUE TITLE
Biomes o' Plenty plugin turns barley into rice in a mill

### ISSUE THREAD

**Issue by ketsuban** [defeatedcrow/HeatAndClimateMod#155]
I think this might be because of these two lines.

https://github.com/defeatedcrow/HeatAndClimateMod/blob/a96474bb5fcc8f040374ecf501cd30b113545462/main/java/defeatedcrow/hac/plugin/DCPluginBoP.java#L97-L98

**Comment by defeatedcrow** [comment]
It's a specification I added intentionally. Because mugi meshi (barley-rice) is my favorite foods.

**Comment by ketsuban** [comment]
Alright. I think it's a little unexpected, but if there's a reason for it that's fair.
