### ISSUE TITLE
Mangalloy Plate crash, lost and duplicate

### ISSUE THREAD

**Issue by NattoLover15** [defeatedcrow/HeatAndClimateMod#158]
forge-1.12.2-14.23.5.2768
HeatAndClimateLib_1.12.2-3.3.2
HeatAndClimateMod_1.12.2-3.3.4

1:
ハンマーミルに高マンガン鋼のプレートをセットしてアイテムの還元を行う際、
各種馬鎧・Mobの頭・エンチャントされた金のリンゴ等一部アイテムを搬入するとクラッシュするようです。

クラッシュレポート
https://pastebin.com/mX1X72kz

2:
還元可能なアイテムを複数同時に搬入スロットに置くと
1アイテム分のみ還元されてそれ以外が消滅します。

3:
還元の元になるレシピの完成品が複数の場合、1アイテムから素材が入手でき
アイテム増殖が可能な状態になっています。
例:石墨の粉・アパタイトの粉・投げ矢・光の矢等

**Comment by defeatedcrow** [comment]
ご報告ありがとうございます

3c1a94f で修正しました！

**Comment by NattoLover15** [comment]
修正を確認しました、対応ありがとうございます。
