### ISSUE TITLE
Crash client

### ISSUE THREAD

**Issue by SeagalKru** [defeatedcrow/HeatAndClimateMod#159]
[crash-2020-05-13_14.13.19-client.txt](https://github.com/defeatedcrow/HeatAndClimateMod/files/4621561/crash-2020-05-13_14.13.19-client.txt)

P.S.: This crash happens after the "[Immersive Energy](https://www.curseforge.com/minecraft/mc-mods/immersive-energy/issues/4)" mod has been updated. After rolling back the version of the updated mod, everything works: both the server and the client.

**Comment by defeatedcrow** [comment]
It's a very strange crash.
This is (probably) not a HaC content issue, Forge is failing to load the mod. It seems to be some serious problem (the log shows some obfuscation or class loading problem).

If the mod you changed is obvious, you should contact the author. I can't find anything I can do from this log, however, I may respond if them request to cooperate.
