### ISSUE TITLE
Can u..

### ISSUE THREAD

**Issue by LUEZIS** [defeatedcrow/HeatAndClimateMod#161]
Can u:
1. Add flint crude hatcher compability with Dynamic Trees mod (It's very hard to find "regular" tree with this mod)
2. Add tree compability with Dynamic Trees (It looks just better)
3. Dump some textures to 16x resolution or made additional resourcepack for it (details are good, but it doesn't fit into the main artstyle)

**Comment by defeatedcrow** [comment]
1. I don't know what a flint crude hatcher is (as HaC doesn't have such an item), but Dynamic Trees already has an easy way to get a regular saplings. (It can be created with dirt and a bucket.) Also, many HaC recipes that use logs support the ore dictionary. The trees in Dynamic Trees also support it.
2. Dynamic Trees already has an [add-on for HaC](https://www.curseforge.com/minecraft/mc-mods/dynamic-trees-heat-and-climate-compat). (The update seems to be stalled, but please contact the author.)
3. I don't have time to prepare all the x16 textures for your personal taste. It should be made by the person who wants it.

**Comment by LUEZIS** [comment]
Sorry, hatchet is not from your mod, my fault tho. It's from Fauna and Ecology.
