### ISSUE TITLE
Creatures don't suffocate 

### ISSUE THREAD

**Issue by El13B** [defeatedcrow/HeatAndClimateMod#163]
Ok, so I'm trying to get mobs to suffocate in "tight" airflow but it won't work. 
Here are copies of my cfg files. 

Also, thanks for the mod love your work!!

[climate cfg.zip](https://github.com/defeatedcrow/HeatAndClimateMod/files/4674870/climate.cfg.zip)

**Comment by defeatedcrow** [comment]
Currently, undead monsters do not take damage from choking (since they presumably do not breathe).

**Comment by El13B** [comment]
oh that's good to know that's for the info
