### ISSUE TITLE
他MODの液体と熱交換器

### ISSUE THREAD

**Issue by tetuis** [defeatedcrow/HeatAndClimateMod#170]
Thermal Foundationの燃え盛るパイロジウムの液体源を設置したところ温度はUHTになったのですが、その上に熱交換器を設置した途端に温度がNORMALになってしまいました。
それ以外にもいくつかのMODの液体でNORMAL以外の温度になるものを試してみましたが、そういったものも（試した範囲では）全てNORMALになってしまうようです。

**Comment by defeatedcrow** [comment]
ご報告ありがとうございます。
温度計算時にIFluidBlock用の特殊動作を入れておくのを忘れたようなので、
次回更新時に修正しておきます。

**Comment by tetuis** [comment]
修正確認できました、ありがとうございます。
確認してて気づきましたが、他MODの液体はJEIでの『気候に影響するブロック』にも表示されませんね。これは仕様でいいんですか？

**Comment by defeatedcrow** [comment]
仕様です。

JEIの該当タブは、modの液体ブロックはブロック登録用APIを通して登録されたブロックのみを表示します。modで追加されているものも、BoP流砂やFFM液体など、このAPIを通したものであれば表示されます。
この機能は『ブロック』を登録するものですから、Fluid・FluidStackには原則的に対応していません。

表示されない場合：
・まず、Forge液体はすべて内部的な温度情報を持っています。なので、原則的にはすべての液体が上記APIなしで温度情報を持てるため、未登録で気候情報を持つものが多くあります。
　コレについては、Forgeユニバーサルバケツのツールチップに拡張機能をつけて温度表示していますので、こちらを確認してください。

・もう一つは、ForgeModの液体の仕様が統一されていません。modによって、『液体はあるがBlockとして設置できない』『液体ブロックはあるがItem状態にできない』『Forgeユニバーサルバケツに登録していない』など仕様がばらばらで、このような場合は登録されていてもJEI上に表示できません。（例えば、バニラの2種の液体はItem状態が未実装のため、仕方なく特例としてバケツアイテムを表示しています。）

Fluid用のJEI情報表示は検討しますが、HaC向けパラメータの有無に関わらず、全液体の一覧表のような状態になると思います。

**Comment by tetuis** [comment]
なるほど、了解です。説明ありがとうございました。
