### ISSUE TITLE
being damaged but the heart doesn't show it

### ISSUE THREAD

**Issue by gatoborrachon** [defeatedcrow/HeatAndClimateMod#171]
when im 1 block over lava i get damage but the heart remains pink,
![2020-08-07_18 49 53](https://user-images.githubusercontent.com/61126174/89696859-4bd86180-d8df-11ea-96b8-2e86362e6691.png)

 it only turns red when im above lava
![2020-08-07_18 50 21](https://user-images.githubusercontent.com/61126174/89696871-50047f00-d8df-11ea-85e3-02307f772e1e.png)

**Comment by defeatedcrow** [comment]
The display data for the client uses the coordinates of the player's chest height. Also, the damage calculations (as a common specification for all creatures) use the internal coordinates of the player. They are off by one block, but are the intended specification.

**Comment by gatoborrachon** [comment]
oh, ok, sorry for late reply
