### ISSUE TITLE
[Issue] many recipes for drinks doesn't show in JEI

### ISSUE THREAD

**Issue by gatoborrachon** [defeatedcrow/HeatAndClimateMod#173]
JEI doesn't show recipes for almost all the drinks like the Nitrogen Pack, Lemonade Pack, Soy Milk Pack, Sulfuric Acid Pack, Cream Drop, etc.

is this intended? or simply these objects don't have recipe at the moment?

**Comment by defeatedcrow** [comment]
There are no recipes for those items.
Paper packs are fluid containers and can be filled with HaC fluid using tanks and fluid slots.

**Comment by gatoborrachon** [comment]
oh ok, then i think it would be good to add this info in JEI. (when they press "R" to access to the recipe this info could be displayed)

**Comment by defeatedcrow** [comment]
We are currently working on a JEI plugin that will display all fluid information (temperature, unique dictionary of HaC's and drinking effects).
Drinking effects are also shown in the tooltip of the item (as well as many other mod items) and it's visible in the JEI item list, we won't make a drinking effect-only JEI plugin.
