### ISSUE TITLE
[Suggestion] more customization in the "Anaerobic Underworld" config

### ISSUE THREAD

**Issue by gatoborrachon** [defeatedcrow/HeatAndClimateMod#174]
i like when its enable and you need a source of oxygen, mods like Mekanism and IC2 give options to solve this challenge, but the option also makes too slow the labor of mining ores, this feature could be separated from "Anaerobic Underworld"? in something like "Slow Mining"?

**Comment by defeatedcrow** [comment]
The reduction in mining speed in an anaerobic environment is the same as the underwater specifications for vanilla. Therefore, vanilla features that improve underwater mining speed (enchantments and potions) are a good solution.

Another measure is the use of blocks and machines that improve airflow.
For example, IC2Air has "FLOW" airflow as a fluid block, which can be placed into the world in a bucket to help the player

**Comment by gatoborrachon** [comment]
ok, i will take that advice
