### ISSUE TITLE
[Issue] How exactly you can sync HaC with Serene Seasons? + Error with the seasons

### ISSUE THREAD

**Issue by gatoborrachon** [defeatedcrow/HeatAndClimateMod#176]
i setted the year length to 96, i setted the duration of seasons in HaC in 24 days periods, i setted too the first day of a new world in HaC on 16 (the first day of Spring in HaC that i configured) and in SereneSeasons i setted the first day of a new world as "early spring" because they doesn't have exact times, this is enought? there will not be miss-syncs?

https://imgur.com/a/LIXM2xt

EDIT: Well, i think there's a problem with the first day of the seasons, check the image above and you will see how it says that the spring starts in 16, but in the image below you can see how it says that is Summer, and in a new image it says that is autum...
https://imgur.com/a/8EeHOtU
https://imgur.com/a/qZ2SEZm

or probably im doing it wrong, tell me if that's the case, and if its not a nuisance, then how is the right way? i like a lot the concept but probably i forgot a detail

**Comment by defeatedcrow** [comment]
In fact, HaC's seasonal settings are complicated. (It's became complicated caused past demanders who want to have the HaC season exactly match reality.)

The following steps are required:
Year Length: Match the year length of Serene Seasons.
Season Length: With this setting, make sure it have a total of 365 days a year! If you set the length of each season to 24 days (96 days in total), the remaining 97 to 365 days will be recognized as unset.
Also, this setting allows you to span the New Year if the end date is less than the start date.

By default, the spring start date is the official setting of the Japan Meteorological Agency. If you need the same settings as Serene Seasons, set the spring start date to day 0.

**Comment by gatoborrachon** [comment]
sorry for late reply
ok, so that "first day" is more symbolic than something with a real impact in game (ignoring the buffs and nerfs that each season have),

so i should set the first day to 0, and calculate an equivalent to (24 days each season)/(96 days each year) but for (x days)/(365 days) right?

the answer is 91.25, but i can set numbers with decimals in the config?

also, this part in specific:
https://imgur.com/a/4zSTiH3
uses a day zero?
because i should set the beginning and end of spring like this?

"0
91.25" (option 1)

or this?

"1
91.25" (option 2)

and sorry, i used the command /climate in another world, and i think that the global current season is saved in the config file right? i think that's why i saw how the seasons changed with no reason.

Do you consider that this issue is solved? I think that the information that is worth getting from here could go well in the documentation, if you consider it so.

and well, i need to say: thanks for working on this mod, in the last days i was looking for many mythical mods in both 1.7 and 1.12, and i saw how this mod is a spiritual predecessor of your old mods like EconomicalMilkTea, AppleMilkTea2, FluidityFoodstuffs, and it combines things of BetterThanWolves, SextiarySector2, and of your mods, thanks for bring them to newer versions. i really appreciate the work.
