### ISSUE TITLE
[Suggestion] Could you add option to hide liquids that have no potion effect in "Fluid Information" tab?

### ISSUE THREAD

**Issue by Prunoideae** [defeatedcrow/HeatAndClimateMod#177]
It's good too add a tab to skim through the effects of fluids, but when the fluid is a bit too much, especially when mods like NuclearCraft or Tinker's Construct is added, this tab becomes quite hard to read since there are too many "No Effect" fluids.

![image](https://user-images.githubusercontent.com/24620047/92927384-1ab7f780-f470-11ea-8199-36865507c852.png)

When it comes to a modpack with over 700 liquids, it's almost impossible for anyone to get a total view of all effective liquids.

**Comment by defeatedcrow** [comment]
This JEI plugin is for viewing generic fluid information (including climate information). We will not accept requests that are too narrow in scope, adapting only to your play style.
(Such requests should be implemented by the modpack author for those environments. I think that the inability of many modpack authors to support java modding is a serious pollution of the current MC environment. You are asking too much of me for modpack author support).

Anyway, the "narrowed search" feature seems to be better than the feature you specified.
We will implement a feature that will narrow down the items that have a drinking effect when you select HaC teacups in JEI.
