### ISSUE TITLE
[Issue] crash on startup with new version of Animania

### ISSUE THREAD

**Issue by gatoborrachon** [defeatedcrow/HeatAndClimateMod#178]
Animania version: 
animania-1.12.2-base-2.0.0.23
animania-1.12.2-extra-1.0.0.23
animania-1.12.2-farm-1.0.0.23

HaC version : HeatAndClimateMod_1.12.2-3.4.0.jar
HaC Lib version: HeatAndClimateLib_1.12.2-3.4.0

when i removed the 3 .jars of animania all worked again, so i think they were the cause

Crash report: https://pastebin.com/Q3rjTzG6

i already reported this to Animania's staff, i think this is 100% fault of them, i will close this issue when they release a hotfix

**Comment by defeatedcrow** [comment]
HaC's Animania plugin does not support that version of Animania. You can turn the plugin off in the config.

**Comment by shinoharatsuru** [comment]
@defeatedcrow , inside module.cfg ? manually key in the B:Animania=false?

**Comment by defeatedcrow** [comment]
Hmm, it seems that the Animania plugin config was not yet implemented, so I'll add it in the next update.

**Comment by gatoborrachon** [comment]
ok, i will wait for the next update, thanks.
should i close the issue? (you can re-open it if you consider it appropriate)
