### ISSUE TITLE
[Suggestion] add compat with SimpleDifficulty

### ISSUE THREAD

**Issue by gatoborrachon** [defeatedcrow/HeatAndClimateMod#180]
forgive me for bothering you again, if you don't want to add this compat i perfectly understand it and you are free to close this issue, just wanted to suggest it to you in case you did not know about this mod

its practically a Tough as Nails but updated, since the original TaN is dead

(oh, and by "compat" i mean to the drinks, because adding compat to the heat sources maybe will depend more on their side)

https://www.curseforge.com/minecraft/mc-mods/simpledifficulty

**Comment by defeatedcrow** [comment]
Hello, Thank you for your comments.

For SimpleDifficulty, this mod has enough APIs for drink compat (if it's just a simple recovery effect of the thirst). It seems have kinder APIs than TaN.

There are no plans to implement compat for temperature. There is a lack of documentation on proper settings such as speed or amount of change body temperature. (HaC temperature and human body temperature are incompatible, so we cannot consider the proper balance.)

**Comment by gatoborrachon** [comment]
oh ok, many thanks for answer, yeah i just wanted compat with drinks

**Comment by gatoborrachon** [comment]
sorry for late reply, i were busy these days

it seems to not being working:
https://streamable.com/n2v47u

**Comment by defeatedcrow** [comment]
No new version has been released since I received your request. Of course, compat too.
Have you checked the release notes?

The contents of the mod cannot change without release. 
Or is this an arrogant reminder?
Are you okay?

**Comment by gatoborrachon** [comment]
oh sorry, i thought that when you said "this mod has enough APIs for drink compat" you meaned that Heat and Climate already had compat, but I didn't understand well, english its not my native language and sometimes my messages are rude without intention, sorry again.

i just saw you released a new .jar with this issue solved in the description, many thanks.

**Comment by defeatedcrow** [comment]
understood.
"API" refers to that SimpleDifficulty has. (It's what modder need if one mod makes a compat for another.)

And now compat has been released. Enjoy the mod :)

**Comment by gatoborrachon** [comment]
yeah, when i re-read your first comment i noticed what exactly i understood bad, many thanks for the aclaration
