### ISSUE TITLE
[Issue] Small issue with chairs

### ISSUE THREAD

**Issue by gatoborrachon** [defeatedcrow/HeatAndClimateMod#181]
just a minor bug, when you want to get out of a chair you get trapped, its easy to totally get out but maybe can be an issue for other users
https://streamable.com/7gabs7

**Comment by defeatedcrow** [comment]
It looks like there is a known vanilla bug.
Such ghost blocks often occur when the block is destroyed too quickly. I think it will be repaired by reloading the world.

**Comment by gatoborrachon** [comment]
i'm the only one who have this issue? i think maybe its one of my other mods, i will try to check which one is the guilty (because this issue happens always, in a new world, an already existing world, etc)
