### ISSUE TITLE
Ticking Player Server Crash on Mod Update

### ISSUE THREAD

**Issue by ScottoMotto** [defeatedcrow/HeatAndClimateMod#184]
Crash updating existing world to HeatAndClimateMod_1.12.2-3.5.0 and HeatAndClimateLib_1.12.2-3.5.0.
https://pastebin.com/pdrE7RqX

**Comment by defeatedcrow** [comment]
Thank you for your report!

It fixed at 110343a52ed9a982de9657c2ede986b379d688bb.
