### ISSUE TITLE
[Minor bug] Wrong oreDict names in Zinc Clump and Nickel Clump

### ISSUE THREAD

**Issue by gatoborrachon** [defeatedcrow/HeatAndClimateMod#185]
idk if this was intended, but the oreDict of these 2 items in the title are incorrect if you compare them with the oreDict names from Mekanism.

HaC's Nickel and Zinc clums have the following oreDict names: "chunkNickel" and "chunkZinc".

For reference, the Mekanism's Iron Clump has the oreDict name "clumpIron", and the Gold Clump has "clumpGold".

Close this issue if this was intended.

**Comment by defeatedcrow** [comment]
Fixed at e8779c363fd413a4a42782b427da3367fee04cc7.
