### ISSUE TITLE
This mod seems to be incompatible with the Coffee Workshop mod now.

### ISSUE THREAD

**Issue by UberbeastX** [defeatedcrow/HeatAndClimateMod#186]
Sorry if this is a pain but I was wondering if there was a way to make this mod compatible with coffee workshop again because I remember it was compatible before but just doesn't work with it now. I came here first since coffee workshop has had no changes since 2019 but this mod has so I was just assuming that something here changed that caused the crash.

**Comment by defeatedcrow** [comment]
I'm not involved in the development of that mod, so I can't fix that mod.
Contact the author of the Coffee Workshop.

Regarding HaC backward compatibility, we maintain some backward compatibility for plugins through the API, but we cannot support plugins created in any other way. (That mod is doing it at their own risk.)

**Comment by defeatedcrow** [comment]
It fixed at e38d763. Temporarily added measures to avoid crashes. It can work together!
But it still needs the Coffee Workshop author's fix. (This measure is very tentative.)

**Comment by UberbeastX** [comment]
thanks
