### ISSUE TITLE
温度計がレッドストーンコンパレーターの信号強度を変化させない

### ISSUE THREAD

**Issue by tetuis** [defeatedcrow/HeatAndClimateMod#187]
温度計が背面に来るようにレッドストーンコンパレーターを配置した場合、温度によって強度の違うレッドストーン信号が出力されますが、配置した後に温度が変化しても強度が変わりません。
また、既に配置してあるレッドストーンコンパレーターの背面に温度計を設置した場合、信号が出力されません。

**Comment by defeatedcrow** [comment]
バージョンや環境の情報がないので、最新版（v3.6.1）かつ、作者の使用している開発環境限定でお話します。

＞配置した後に温度が変化しても強度が変わりません。
作者の環境で再現できませんでした。
なお、温度変化から10F（0.5秒）ほど遅延してモニターの表示が変化するのは仕様です。（このクールタイムを短くするとサーバー負荷が増大するので、安定して複数個置けるクールタイムを意図的に設定しています。）

＞既に配置してあるレッドストーンコンパレーターの背面に温度計を設置した場合、信号が出力されません。
こちらも作者の環境で再現できませんでした。

**Comment by tetuis** [comment]
あ、MOD/Libはv3.6.1です、すみません。modをこの２つのみにして新規ワールドで試しています、再度確認しましたがやはり発生しました。
コンパレーター付近にブロックを置くなどの行為をすれば反映されますが、そのままでは数分放置しても変わらないため時間の問題ではなさそうです。
実際に試した様子はこのようになります。
左がコンパレーター・温度計・マグマブロック、中央が温度計・コンパレーター・マグマブロック、右が温度計・マグマブロック・コンパレーターの順に配置したものです。
![image](https://user-images.githubusercontent.com/69350996/108757890-c91ea780-758d-11eb-8112-04183c998062.png)

**Comment by defeatedcrow** [comment]
こちらの温度計には簡易のコンパレータ出力のみ実装してあり、バニラコンパレータの動作保証はしていません。

わたしが示している、「正常に動いた」とは遠隔版のことです。
自前のサーバ・クライアント同期処理を備えていてバニラBUDバグに対応できるのはこちらのみですので…
![2021-02-23_11 59 34](https://user-images.githubusercontent.com/6741099/108797600-e45dd700-75ce-11eb-9c6b-2e3a20296042.png)

バニラコンパレータは確認先の座標のブロックのコンパレータ出力に変化があっても、自力でそれを検知する能力は実装されていません。（バニラの色々なブロックが更新処理が呼ばれるまでブロックの変化を検知できないのは、昔から有名なバニラの不具合です。公式がBUDとして仕様化してしまったので今後も修正はされないと思います…）
こちらから検知させる（定期的にブロックの更新処理を呼ぶ）のはサーバー負荷が重いので、HaCでは限られたブロックに実装しています。


こちらの温度計を使用する場合は、バニラコンパレータではなく、（BUD対策を実装している）HaCの遠隔コンパレータランプを中継させる必要があります。
![2021-02-23_12 13 14](https://user-images.githubusercontent.com/6741099/108798312-e32da980-75d0-11eb-8f3c-75386805c92a.png)
![2021-02-23_12 21 20](https://user-images.githubusercontent.com/6741099/108798658-ac0bc800-75d1-11eb-96b7-5cb579f7d44e.png)

**Comment by tetuis** [comment]
なるほど、遠隔版のOutputに書いてあるのはそういう事ですか、了解しました。
できればその辺りもう少し（非対応側にも）表記していただけると助かります。
素材の違いから遠隔の方を使うという考え自体出てこなくて、そちらのtooltipに書いてあることも今気づいたくらいなので……

**Comment by defeatedcrow** [comment]
バニラのBUDなどの仕様情報はmodのものではないので、原則的に既知のものとして扱っています。
（解説でバニラ仕様の網羅をすることは個人制作では無理があり、サポートの対象外です。マインクラフトというゲーム自体が公式の解説が少なく有志製の解説に頼った体制の、若干不親切なゲームですので、プレイヤーもある程度そのような環境に耐えうるものとみなしています。）

サーモメーターはプレイヤーが視覚的に温度を確認する目的のインテリアブロックですので、コンパレータでのRS制御への組み込みは目的としていません。
誤解の原因になるようならコンパレータ出力機能の削除を検討します。

**Comment by tetuis** [comment]
HaCの遠隔コンパレーターランプであれば動作するといった部分の説明は多分ゲーム中にもWikiにもなかったと思うんですが、あったのであればすみません。
バニラのレッドストーンコンパレーターとの組み合わせだけなら非対応ブロックの出力機能削除で誤解はなくなりそうな気はします。

**Comment by defeatedcrow** [comment]
遠隔でない方のサーモメーターにコンパレータ対応機能があるという旨の説明はゲーム中、同梱ReadMe、公式Wikiのどこにもありません。（ですので、コンパレータ対応のあると説明されている温度計は遠隔のもののみです。）
「コンパレータに対応していない」明記は必要ないと考えます。

**Comment by tetuis** [comment]
温度計＋遠隔コンパレータランプの対応を削除しないなら、バニラの物では動作せずHaCの遠隔コンパレーターでは動作するという事の記述があればと。
そちらの対応も削除するのであれば必要はなくなりますが、できていた事ができなくなってしまうので。
ともあれ、仕様という事は理解できましたし、後の対応の判断はおまかせします。

**Comment by defeatedcrow** [comment]
本家マインクラフトの説明の少なさや、自己責任でModdedMinecraftをプレイしている点、ライセンス上をノンサポートを謳っている点からも、こちらの解説記述の有無を争点にするつもりはありません。
ゲーム中で試行錯誤してブロックの性質などを発見して利用する…という趣旨のゲームですしね。
（有償サービスのようなサポートと同等のものを求められないことは、承知の上で遊んでいるものと思っています。）

このmodの場合は個人制作故に完全な解説記述は保証できませんというスタンスですので、今後は解説記述の整合性・不完全性を争点とした不具合指摘についてはお断りいたします。

今回の場合は解説未記載で、仕様に気づいた人が上手く使えばいい、程度の機能でしたが、
・issueオーナーが解説内容との整合性を求めている点
・期待される機能の安全な実装が困難である点
から、機能削除で対応します。

**Comment by defeatedcrow** [comment]
Fixed at 195c907
