### ISSUE TITLE
windmill generates more in TIGHT condition

### ISSUE THREAD

**Issue by Pliosauroidea** [defeatedcrow/HeatAndClimateMod#188]
when puts a windmill in NORMAL flow condition ,it gains 0.5* torque,but when in TIGHT flow condition ,it gains 1*torque ,which seems to be illogical.

**Comment by defeatedcrow** [comment]
That was certainly an inappropriate spec and will be fixed in the next update.
Thank you for your report!

**Comment by defeatedcrow** [comment]
It fixed at e38d763.
