### ISSUE TITLE
missing texture for leaves blown by dynamite 

### ISSUE THREAD

**Issue by Pliosauroidea** [defeatedcrow/HeatAndClimateMod#189]
while using blue dynamite(the one with silk touch) nearby a tree,the leaves dropped get no textue
（both trees in vanilla minecraft and in this mod,like olive tree）

**Comment by Pliosauroidea** [comment]
![123](https://user-images.githubusercontent.com/37920182/110740171-889d7a00-826d-11eb-9781-17481c1e919a.png)
![123111](https://user-images.githubusercontent.com/37920182/110740172-8a673d80-826d-11eb-9f45-f1556687a532.png)

**Comment by defeatedcrow** [comment]
Silk dynamite has the purpose of forcibly obtaining blocks that are not available with the vanilla silk touch effect, and intentionally produces drops that are different from normal silk touch.
Often the block model is abnormal, but it is the expected specification. (Such a drop will recreate the state before the drop when placed.)

Normalization undermines these performances and is not planned for correction.
