### ISSUE TITLE
[Minor Bugs] Missing Oxygen Translation Key & Bad Render of Thermal Entity Sensor

### ISSUE THREAD

**Issue by gatoborrachon** [defeatedcrow/HeatAndClimateMod#191]
As i said, they are just minor bugs that do not compromise anything of high importance, so don't worry about releasing a hotfix just for this.

The tests where made using only Heat and Climate, and JEI-HWYLA

1.- The Translation Key of "dcs.oxygen" (both bucket and water block) and are missing:
![2021-05-08_09 23 27](https://user-images.githubusercontent.com/61126174/117542766-82aee580-afdf-11eb-8d26-06d886032253.png)
![2021-05-08_09 28 41](https://user-images.githubusercontent.com/61126174/117542823-d28dac80-afdf-11eb-8af5-cd8327243f28.png)

----------------------------------------------------------------
2.- The Thermal Entity Sensor does not render, anyways, it seems to still working.
![2021-05-08_09 24 04](https://user-images.githubusercontent.com/61126174/117542794-a4a86800-afdf-11eb-8d35-3231de22143d.png)
![2021-05-08_09 24 06](https://user-images.githubusercontent.com/61126174/117542796-a540fe80-afdf-11eb-95ad-23d40705c897.png)

**Comment by gatoborrachon** [comment]
Also, i have another small doubt: Where are the Vanilla Furnace smelting recipes? (for example: Copper Dust-> Copper Ingot)

i tried to remove them using CraftTweaker but they persist, so i just wanted to know: in which .java file are these recipes being registered?
(i want to use Tinkers' Construct Smeltery to get things like ingots, plates, gears and cubes)
![2021-05-08_10 28 32](https://user-images.githubusercontent.com/61126174/117544706-39af5f00-afe8-11eb-8af9-177051efcda2.png)

**Comment by gatoborrachon** [comment]
to not open another issue, i have a third doubt:

you implemented a way to add a potion effect to any liquid drinked from the HaC's NickelSilver cup right?
where is the function to add custom ones? (i tried to find it)
![2021-05-09_14 56 58](https://user-images.githubusercontent.com/61126174/117585220-db14de80-b0d6-11eb-88e7-79bec3d73451.png)

**Comment by defeatedcrow** [comment]
It is desirable to set up issues individually. These are not problems with a common cause. 
This time, I will treat them all together (because it is unavoidable).
It will be closed after all issues have been resolved.

> 1. Translation error
> 2. Display of block model 

These will be fixed in the near future. 

> 3. Smelting recipes

They are included in MachineRecipeRegister.java, but if the recipe is not removed by CT, it is due to the specifications of other mods.
(Some mods will automatically generate vanilla smelting recipes from the ore dictionary entries. They cannot be modified by HaC, so please contact the author of it.) 

> 4. Drinks

They are specifications and there are no plans to add configs in the future. The effect is mainly based on the difficulty of acquisition and HaC's internal magic settings.

Modding means are needed to remove it.
DrinkPotionType.java holds a Map of registered contents, so you can modify it by editing the Map.

We do not intend to support ModPacker's lack of Java Modding skills, so you should have the necessary Modding skills.

**Comment by gatoborrachon** [comment]
> It is desirable to set up issues individually. These are not problems with a common cause.
> It will be closed after all issues have been resolved.

sorry, that's a vice of mine, i always think that opening an entire issue just for a translation key in a .lang file would be too much for too little, but i will avoid doing this again.

---------------------

> These will be fixed in the near future.

thanks

---------------------

> They are included in MachineRecipeRegister.java, but if the recipe is not removed by CT, it is due to the specifications of other mods.
(Some mods will automatically generate vanilla smelting recipes from the ore dictionary entries. They cannot be modified by HaC, so please contact the author of it.)

thanks again, [i found them](https://github.com/defeatedcrow/HeatAndClimateMod/blob/1.12.2_v3/main/java/defeatedcrow/hac/main/recipes/MachineRecipeRegister.java), and yeah some mods add furnace recipes based on oreDict (like [GregTech Experimental](https://github.com/Su5eD/GregTech-Experimental/blob/unstable/src/main/java/mods/gregtechmod/init/OreDictHandler.java)), (which i recently edited) but i ensure you that using this [CT Script](https://pastebin.com/1ZhDkbqU) these recipes persisted, and they are from HaC because i tested an instance with only HaC, Rockhounding mod: Chemistry and Advanced Rocketry as the main tech mods, and the only Ingots and Dusts that had a Furnace Recipe were from HaC (using the previous CT Script).

---------------------

> They are specifications and there are no plans to add configs in the future. The effect is mainly based on the difficulty of acquisition and HaC's internal magic settings.

> Modding means are needed to remove it.
DrinkPotionType.java holds a Map of registered contents, so you can modify it by editing the Map.

> We do not intend to support ModPacker's lack of Java Modding skills, so you should have the necessary Modding skil

-oh no problem, yeah i'm a beginner but i'm continuously learning lots of basic-mid knowledges, i just wasn't able to find the exact [.java file](https://github.com/defeatedcrow/HeatAndClimateMod/blob/1.12.2_v3/main/java/defeatedcrow/hac/plugin/DCPluginFluid.java) with the specifications of fluid-potion, that's all i need, many thanks for your answer.

-oh, and regarding to the balance, i just asked this because someone (in another repo) wanted to add the potion effect of "warming" (to increase the body temperature in one of these early game mods) effects to a fluid like "hot chocolate", and i remembered that HaC had this system on the NickelSilver cup, but if this is not meant to be a custom option to modpackers, no problem, you have a strong argument of why not.

**Comment by defeatedcrow** [comment]
1 & 2 fixed at 0d82940.

Customization of drink effects can be modified by add-ons. (DrinkPotion.java has a registration method.)

Alternatively, even if you don't use the function of this mod, Forge has an Event that fires when you right-click and use an item, so you can modify it using it.
(See Forge's documentation for how to use Event.)

**Comment by gatoborrachon** [comment]
oh, ok. Really many thanks for the bugfixes and the info,
