### ISSUE TITLE
アイテムドロップ数の異常

### ISSUE THREAD

**Issue by RedRayz** [defeatedcrow/HeatAndClimateMod#195]
赤の金ペンダントをインベントリの最上段に置き、カラスのガントレットをオフハンドに持った状態でブロックを採掘すると鉄鉱石や金鉱石などの一部のブロックのアイテムドロップ数が異常になります。
バージョンはForge14.23.5.2854,HaCLib3.6.5,HaC3.6.6です。

**Comment by RedRayz** [comment]
掘るごとに2倍になっていき、ドロップ数がintの上限値(2147483647)に達するとペンダントの効果がなくなります。

**Comment by defeatedcrow** [comment]
1ea06fe で修正しました

ご報告ありがとうございました！
