### ISSUE TITLE
minor bug for motor minecart

### ISSUE THREAD

**Issue by Pliosauroidea** [defeatedcrow/HeatAndClimateMod#198]
when mid-click a motor minecart in creative mod,player will get a normal minecart instead
it does not affect much so it's ok to leave it there.
ver:V3.6.7 in minecraft 1.12.2

**Comment by defeatedcrow** [comment]
Thank you for your report. 

It fixed at https://github.com/defeatedcrow/HeatAndClimateMod/commit/b045bce2ef5e31b1060747191fd55903b62d33db.
