### ISSUE TITLE
My .minecraft directory is full of your blockstate files?

### ISSUE THREAD

**Issue by Bluberry-Kat** [defeatedcrow/HeatAndClimateMod#199]
versions:
forge = 14.23.5.2855
heat and climate = 1.12.2-3.6.7
h&c lib = 1.12.2-3.6.5

for some reason, while loading the game, my .minecraft directory receives a dump of multiple blockstate files from heat and climate
![image](https://user-images.githubusercontent.com/20749209/120907194-8ad56180-c62d-11eb-9ffa-4de550f86e31.png)

i was able to reproduce this with no other mods in my modpack

**Comment by defeatedcrow** [comment]
Thank you for your report.

It fixed at https://github.com/defeatedcrow/HeatAndClimateLib/commit/895c527d9f804825dedab7147d271f0aa566cc13.
