### ISSUE TITLE
Recipe issue with Mekanism

### ISSUE THREAD

**Issue by AileRozy** [defeatedcrow/HeatAndClimateMod#20]
the recipe for Zinc and Nickel like crystal, clump, shard, dirty dust can not be use even when config file module.cfg B:MekanismPlugin=true

HeatAndClimateLib-1.10.2_1.5.17
HeatAndClimateMod-1.10.2_1.5.21
Mekanism-1.10.2-9.2.3.97
MekanismGenerators-1.10.2-9.2.3.97
MekanismTools-1.10.2-9.2.3.97

**Comment by defeatedcrow** [comment]
Those recipes can not be seen with JEI, but they are registered normally.
(It can confirm the normal registration in the console log, I do not know the reason why it can not be confirmed with JEI. But I can not fix it.)

**Comment by AileRozy** [comment]
put Zinc ore and Nickel ore in mekanism's machine won't work, just like the recipe isn't there
![2017-11-04_20 58 27](https://user-images.githubusercontent.com/19416768/32405583-27d5f708-c1a3-11e7-8d46-46416295e730.png)
![2017-11-04_20 58 36](https://user-images.githubusercontent.com/19416768/32405586-340cbf7a-c1a3-11e7-9083-61ed7b1dcee7.png)
![2017-11-04_20 58 43](https://user-images.githubusercontent.com/19416768/32405588-3994f69c-c1a3-11e7-8eee-21d624e554cd.png)

**Comment by defeatedcrow** [comment]
Sorry, it does not seem to work with Garnierite.
I'll fix it soon.

![2017-11-04_22 38 38](https://user-images.githubusercontent.com/6741099/32405954-75018b5a-c1b2-11e7-982c-de459f616ecb.png)

**Comment by AileRozy** [comment]
it recipe issue too so I think better put it here:
Nickel Dust can't smelt in Mekanism's Smelting factory, Zinc Dust is fine

![2017-11-06_10 35 30](https://user-images.githubusercontent.com/19416768/32423018-f5e3edda-c2de-11e7-87e9-76f7909bbe05.png)
![2017-11-06_10 35 26](https://user-images.githubusercontent.com/19416768/32423021-f909e06e-c2de-11e7-9148-b04ea6e3fa4d.png)

**Comment by defeatedcrow** [comment]
Zinc is tier 1 metal in HaC.
It can be refined with vanilla Furnace.

But Nickel is tier 2 metal in HaC.
It require SMELTING temperature. It' can not refined with vanilla furnace, with the Smelting factory too.
