### ISSUE TITLE
minor bug for creative drill

### ISSUE THREAD

**Issue by Pliosauroidea** [defeatedcrow/HeatAndClimateMod#200]
when using the drill in enchanted mode(silk touch mode?) and right-click a redstone ore,it will shine for a while and then disappear.
minor bug,fine to leave it there.
ver:v3.6.8

**Comment by defeatedcrow** [comment]
Hello.
I will fix it in the next update, but can also be solved by the player giving the ore dictionary name "oreRedstone" to the Lit Redstone Ore.

As for vanilla redstone ore, "lit ore" and "non-lit ore" are registered as separate blocks. Only non-lit ones have ore dictionary names. Therefore, the glowing ore is treated as a non-mineral block.
