### ISSUE TITLE
no recipe for chickInEgg in JEI

### ISSUE THREAD

**Issue by Pliosauroidea** [defeatedcrow/HeatAndClimateMod#201]
when i tried to find how to make a chickInEgg,i found nothing in JEI and had to check the source code to find the recipe.

**Comment by defeatedcrow** [comment]
This item can be obtained by warming vanilla eggs in an incubator.
I didn't have enough in-game instructions, so I added a tooltip with c387f9c3e9fc90775f86a7ffd1040349e9b6e789.
thank you!
