### ISSUE TITLE
Cannot set EnableAdvancedMagic to false when EnableMagicModule is true

### ISSUE THREAD

**Issue by RisingInIris2017** [defeatedcrow/HeatAndClimateMod#203]
### Forge Version:
14.23.5.2855
### Heat & Climate Version:
Lib: HeatAndClimateLib_1.12.2-3.6.6
Mod: HeatAndClimateMod_1.12.2-3.6.8
### Crash Report:
https://paste.dimdev.org/owubugoluv.mccrash
### How to Reproduce:
1. In `config/module.cfg`, set `B:EnableAdvancedMagic=true` to `B:EnableAdvancedMagic=false`, but keep `B:EnableMagicModule=true` unchanged.
2. Start the game and it will crash.

I have read your H&C Mod Wiki, but I am still confused with what game contents "Advanced Magic" module and "Magic Module" respectively control. It is highly appreciated if you could explain the function of these two configuration options, and why my configurating leads to game crash.

Thanks in advance for your kind-hearted help!

**Comment by defeatedcrow** [comment]
Thank you for your report!
This case is a bug, and it is the correct specification that those settings can be compatible.
It will be fixed at the next update.

The "advanced" element of the magic module is currently a temporary implementation, so the settings are currently unstable. (The definitions of them have changed from v2.X.X.)

In the future, magical materials of Tier 2 and above and multicolored magic will be limited as advanced modules.

**Comment by RisingInIris2017** [comment]
Quite helpful reply, thanks a lot!

**Comment by defeatedcrow** [comment]
The module has now been reviewed and the crash due to changes in module.cfg has been removed in c387f9c3e9fc90775f86a7ffd1040349e9b6e789.
thank you!
