### ISSUE TITLE
[Suggestion] Allow players with Wing Blessing potion effect to hover in air

### ISSUE THREAD

**Issue by RisingInIris2017** [defeatedcrow/HeatAndClimateMod#204]
This is just a suggestion.
Wing Blessing potion now allow players to fly very quick and immune to the drop damage.
Considering that we sometimes just need to hover in air to place some blocks to build our new house,
a "hovering mode" - just like the Creative Mode - for Wing Blessing potion may be very useful. It will be loved by those who like building in Minecraft.
Since the potion can only last for 3 minutes, "hovering mode" will not be too over-powered. 
What do you think of this idea? Please let me know your opnion.
Thanks in advance for your reply!

**Comment by defeatedcrow** [comment]
Hello.
Does "hovering mode" refer to creative flight?
Creative flight is allowed to the player by manipulating the creative flag. This vanilla spec causes flag conflicts with other mods. Therefore, we have implemented a different flight control "intentionally" to avoid collisions with other mods.
(If we reproduce creative flight with our own implementation, we will need core mod for interference with keyboard control and critical parts of the client.)

With future vanilla updates, modders may be able to safely implement if any changes to the internal implementation of flight or player control.
There are no plans to implement it in the current version.

**Comment by RisingInIris2017** [comment]
> Does "hovering mode" refer to creative flight?

Yes. 
If core mod is used, compatability will be a problem, I know that.
I have got your idea. Thanks for your explanation!
