### ISSUE TITLE
Game crashes when a player with Exp Absorption effect kills many mobs

### ISSUE THREAD

**Issue by RisingInIris2017** [defeatedcrow/HeatAndClimateMod#206]
### Forge version:
14.23.5.2855
### HAC Mod version:
1.12.2-3.6.8
### HAC Lib version:
1.12.2-3.6.6
### Crash report:
https://paste.dimdev.org/qojaqosisa.mccrash
### How to reproduce:
1. Run command `/effect @p dcs_climate:dcs.potion.absorption_exp 255 255`, or equip a Black Golden Ring.
2. Summon enough mobs. You may use a command block with command<br>`summon enderman ~ ~1 ~ {NoAI:1}`<br>to get plenty endermans for testing, due to their Exp drop is more than other mobs.
3. Switch to Survival Mode, then kill them. To reproduce this issue, you may need to kill mobs as many as possible in one attack. In my testing, I used the sweeping attack of a SlashBlade Mod's weapon.
4. Game crashes.
5. Install [CodeChickenLib](https://www.curseforge.com/minecraft/mc-mods/codechicken-lib-1-8) mod.
6. Retry Step 1 to Step 3.
7. Game will not crash.

Thanks for your help in advance!

**Comment by defeatedcrow** [comment]
Thanks for the report.
This bug has been fixed in 2b648995ccb8869c2f3065f126ee62a336450754.
