### ISSUE TITLE
Silver Compression Hoppers convert String Items into Cactus Boxes

### ISSUE THREAD

**Issue by RisingInIris2017** [defeatedcrow/HeatAndClimateMod#209]
Forge version:
14.23.5.2855

HAC Mod version:
1.12.2-3.6.8

HAC Lib version:
1.12.2-3.6.6

How to reproduce:
1. Put a Chest at the top of a Silver Compression Hopper.
2. Put a Chest under it. So the hopper will suck items from the Chest over it, compress them and put the compressed item into the Chest below it.
3. We will get this.
![image](https://user-images.githubusercontent.com/28519848/128000715-f0f933cf-5eef-4fdf-aeee-bb0f56aff4c2.png)

4. Put 64 String items into the upper Chest.
5. Wait, and collect 8 Cactus Boxes from the lower Chest.

I checked if there is an "Compressed Strings" item, but I found nothing. So maybe String items should not be compressed.
So I post this issue here.
Thanks for your help in advance!

**Comment by defeatedcrow** [comment]
It didn't reappear in my environment.

Silver hopper is a specification that considers "items with the same dictionary name" to be the same, so if each item has the same dictionary name, you will see such behavior.

**Comment by RisingInIris2017** [comment]
> Silver hopper is a specification that considers "items with the same dictionary name" to be the same, so if each item has the same dictionary name, you will see such behavior.

I did a thorough examination, and found that it is EarthWorks mod that created an OreDict entry which included both String and Cactus.
So will there be a way to prevent some material to be compressed? As you know there are some mods adding OreDict for their reasons, but those OreDicts produce unreasonable recipes for you Silver Hopper.

**Comment by defeatedcrow** [comment]
Players need to defend themselves against issues that arise from the playing environment.
This mod is a project that allows free use on the condition that the operation is not guaranteed. (As you know.)
We will not consider dealing with individual cases by adding special restrictions to mod blocks.

Tweaker can remove OreDict. (We cannot guarantee that other mods will work properly if deleted.) 
Or, as for sorting and transportation items, many mods have added functional machines, so I don't think to need about solving with HaC blocks.
