### ISSUE TITLE
no texture change for grape growing on the ground&&wall.

### ISSUE THREAD

**Issue by Pliosauroidea** [defeatedcrow/HeatAndClimateMod#213]
when planting grapes,those both on the wall and on the ground will not change textures as growing.
![1](https://user-images.githubusercontent.com/37920182/128834691-c7fec935-e34b-4823-a4c9-4951278a42e3.png)
V3.7.1 in 1.12.2

**Comment by defeatedcrow** [comment]
Thank you for your report.
This is a bug to grow. The root should have been a non-growing block, but it has a growing property due to glitches.

Consider how to fix it.

**Comment by defeatedcrow** [comment]
Fixed at 3cf64c4209a3497571b36fb850d1eac73ccf0b00.
