### ISSUE TITLE
Induction Motor Block- Not Compatiable with EnderIO/Mekanism conduits

### ISSUE THREAD

**Issue by RidemChu** [defeatedcrow/HeatAndClimateMod#214]
It seems that this induction motor cannot be attached with EnderIO/Mekanism RF conduits, so how can it receive RF?
![3](https://user-images.githubusercontent.com/88817661/129145776-5b0be397-7c19-4971-b07f-5f350a3c2a25.png)

![4](https://user-images.githubusercontent.com/88817661/129145795-c217c84f-1305-4e20-955f-6d2c33f83703.png)

**Comment by defeatedcrow** [comment]
RF plugins require RF API.
Therefore, the RF plugin will stop working in an environment where RedstoneFlux is not installed. (This feature cannot be replaced by other mods that support RF.)
