### ISSUE TITLE
Chemical Reactorでの加工時にスロットパネルの位置によってはアイテムが消失します

### ISSUE THREAD

**Issue by SkyTheory** [defeatedcrow/HeatAndClimateMod#216]
TileReactorとTileReactorIBCにおいて、Device Slot Panelを置く位置によってはアイテムを加工できず、素材の一部がtickごとに消失してしまいます。
具体的には、TileReactorの448行目とTileReactorIBCの403行目の判定で、スロットパネルが入っているスロットに来た場合にinRecipeをfalseにしてしまうことが原因ではないかと思います。

**Comment by defeatedcrow** [comment]
ご報告ありがとうございます！
c3e667f316d4b49508d8be9aacd798df3c7a3e10 でスロットパネルの判定を追加しました。
