### ISSUE TITLE
マスケットに付与したフレイムが正常に動作しない

### ISSUE THREAD

**Issue by K-ebisen** [defeatedcrow/HeatAndClimateMod#219]
マスケットにフレイムのエンチャントを付与した際、矢のグラフィック以外に炎上効果が得られず、倒した相手が経験値をドロップしなくなります。
しばらくクモで試してみたところ、一向にクモの目をドロップせず、また昼間に撃った場合に敵対しないため、非プレイヤー属性になっているのだと思われます。

**Comment by defeatedcrow** [comment]
仮実装のまま放置してしまっていた要素なので、次回更新で修正します。

現状ではマスケット銃の弾にフレイムのエンチャントがかかると、銃弾のダメージソースがLAVA（溶岩ダメージ）に置き換わっています。
