### ISSUE TITLE
crash on startup "HeatAndClimateMod_1.12.2-2.1.1, MC 1.12.2 Forge_2566

### ISSUE THREAD

**Issue by JasonKillsUs** [defeatedcrow/HeatAndClimateMod#22]
https://pastebin.com/P3ZnMC2i

thanks for looking into it :-)

**Comment by defeatedcrow** [comment]
All my projects are developed with the recommended version of Forge.
The latest Forge is not supported.

**Comment by JasonKillsUs** [comment]
oh okay, thanks for the info :-)
