### ISSUE TITLE
たらこのパスタの英名に誤植がある

### ISSUE THREAD

**Issue by K-ebisen** [defeatedcrow/HeatAndClimateMod#223]
誤植もこちらでよろしいのでしょうか？
たらこのパスタの英語アイテム名がCod **Roe** Pasta(タラの魚卵パスタ)ではなくCod **Raw** Pasta(タラの生パスタ)になっています。
エンティティ名は正しく登録されていました。

**Comment by defeatedcrow** [comment]
ご報告ありがとうございました！
be9b645e570a9258f1cdb28a65ea405bfef0438c で修正しました。
