### ISSUE TITLE
ガラスのフェンス越しに見た一部ブロックが描画されない

### ISSUE THREAD

**Issue by K-ebisen** [defeatedcrow/HeatAndClimateMod#225]
仕様か不具合かこちらでは判断できないのですが、ガラスのフェンスを通すとこのように一部描画が欠けます。
ランタンは火が消えています。
![2021-10-02_00 40 18](https://user-images.githubusercontent.com/90062524/135659264-a5876bfa-d04f-44f0-af65-1aa22634b0f5.png)

**Comment by defeatedcrow** [comment]
1.8以降の**バニラ**の仕様です。
TileEntity、Entityの透過処理では、他のTESRや、水などの透過ブロックの描画と重ねて表示できなくなりました。
mod側からどうにかすることは出来ません。

バニラのスライムでも同じことが起きます。
スライムを通して見た水ブロックが消えているのが見えますね。

![2021-10-02_12 15 48](https://user-images.githubusercontent.com/6741099/135702104-46dcaf36-801d-44e3-92ca-2721a9c1cce4.png)

（バニラでは透過度を下げたり、透過テクスチャを持ったTileEntityを実装しない、という形で回避しているようです。）
1.7.10以前の頃のほうが良かったものの一つですね…

**Comment by K-ebisen** [comment]
なるほど…。
＞透過テクスチャを持ったTileEntityを実装しない、という形
まさしくこれのためか、初めて知った仕様です。
スライムの外殻(？)も盲点でした。
リソースパックで完全な透明にして対処することにします、ありがとうございました。
