### ISSUE TITLE
several issues and bugs with the owl gauntlet

### ISSUE THREAD

**Issue by Pliosauroidea** [defeatedcrow/HeatAndClimateMod#227]
in the newest version 3.8.1, the owl gauntlet have some   imperfections:

First:
1.get two owl gauntlet
![image](https://user-images.githubusercontent.com/37920182/137707706-e1bfddd9-d14a-430a-99c0-4fa924e93f3b.png)

2.put on each of them and gain two owls
![image](https://user-images.githubusercontent.com/37920182/137709492-1f1dafb8-1e76-4116-9367-65e8a1a0bed0.png)

3.put the two gauntlets together
![image](https://user-images.githubusercontent.com/37920182/137709568-3a966045-467e-443a-aced-1b504ccdbd9b.png)

4.destory the two owls wearing both of the gauntlets
![image](https://user-images.githubusercontent.com/37920182/137709608-d2ca4f1a-dd97-4a71-bdb0-35540e74a5b0.png)

5.after the 4 steps above,you will have 2 gauntlets that can both set two owls,and by cycling the first 4 steps you will get gauntlets with unlimited doll numbers.
![image](https://user-images.githubusercontent.com/37920182/137709674-7a1d6d0d-715f-4521-a491-075bda3a15cf.png)

Second:
the moniter mode trigger and cancel by right-click wearing a gauntlet, but when you point the owl to a block like a chest or an oven,a right click will lead to opening the container's gui instead of quiting the moniter,so one have to destory the container or rejoin the game in order to do so.
![image](https://user-images.githubusercontent.com/37920182/137708758-8dabf4ff-f412-464e-bf04-74a3defa9fc1.png)

Third:
when in moniter mode ,player can open his inventory and throw the gauntlet away,and get himself forever stuck in an owl doll,he also will have to rejoin the game to quit that mode .

**Comment by Pliosauroidea** [comment]
when bound two mermaid gauntlets two the same coordinate and stack them together ,player can no longer unbound them.
and i think the easiest solution is to set the max stack number of the gauntlets to 1 thus forbid stacking gauntlets.

**Comment by defeatedcrow** [comment]
Thank you for your report!
The number of stacks in the gauntlet should be fixed at 1. (It's fatal, so I'll fix it in the next update.)

Also, we plan to add a process to restore the viewpoint by removing the off-hand gauntlet while the player is using the viewpoint of Owl Doll.

**Comment by defeatedcrow** [comment]
It fixed at 9851773587f1d5f4a863fd9ed82946f997d2d210.

Thank you!
