### ISSUE TITLE
Mod malfunction with IC2 when both installed

### ISSUE THREAD

**Issue by Man-Renge-Kyou** [defeatedcrow/HeatAndClimateMod#229]
Hi! I found a bug while playing HeatAndClimate with IndustrialCraft2!
While both mods are installed, the Scanner in IC2 won't work.Cannot put items that need to be scanned into the Scanner's GUI.
mod versions:
HaC 1.12-3.8.4
HaCLib 1.12-3.8.2
IC2 2-2.8.218-ex112

**Comment by defeatedcrow** [comment]
Operation is not guaranteed for mods not included in [ReadMe_Plugin.txt](https://github.com/defeatedcrow/HeatAndClimateMod/blob/1.12.2_v3/main/resources/ReadMe_Plugin.txt).
Especially for mods that are difficult to check in the development environment and mods that are unstable in the beta version.

Regarding IC2, we will investigate defects only for the current latest version (112-221). We will fix it only if possible, but it is not guaranteed.

**Comment by Man-Renge-Kyou** [comment]
Hi!Thank you for replying!
I have upgraded to IC2 version 112-221
still, could not put items into the Scanner GUI…:(

**Comment by defeatedcrow** [comment]
I have tested this issue and both HaC and IC2 seem to be working fine.
The test has ended.

Please reconsider the following points:
- IC2 scanner looks like a tool that doesn't require you to put items in the GUI. You should justify the fact that the item does not put in the GUI as a "bug".
(Repeat, I don't surpport about the behavior other than the mod specified as the plugin target. If you want to negotiate the behavior of the mod that is not supported, please give me the necessary explanation.)
- There is information that it is a phenomenon that occurs with IC2 alone. Before isuse, make sure HaC is the cause. (It is inappropriate to ask me to fix a bug in another project.)

**Comment by Man-Renge-Kyou** [comment]
I understand. Sorry for my rude behavior, was a little too hurry about
reporting this.
Sorry again for that.
