### ISSUE TITLE
Zinc Recipe issue with Mekanism [HeatAndClimateMod-1.10.2-1.6.4]

### ISSUE THREAD

**Issue by AileRozy** [defeatedcrow/HeatAndClimateMod#23]
HeatAndClimateLib-1.10.2-1.6.4
HeatAndClimateMod-1.10.2-1.6.4
Mekanism-1.10.2-9.2.4.103
MekanismGenerators-1.10.2-9.2.4.103
MekanismTools-1.10.2-9.2.4.103
.

Sphalerite's issue:
One Sphalerite won't process in Mekanism machines, need at least 2 ore, but with 2 ore will only produce one item.
And Sphalerite will produce Nickel item instead of Zinc item with Mekanism machines.

![2018-01-06_00 36 17](https://user-images.githubusercontent.com/19416768/34619801-55500c5a-f23b-11e7-9216-5e4627230e29.png)
![2018-01-06_00 36 22](https://user-images.githubusercontent.com/19416768/34619819-590e1814-f23b-11e7-9063-188afcdc5468.png)
![2018-01-06_00 36 54](https://user-images.githubusercontent.com/19416768/34619823-5b2a05c2-f23b-11e7-8ba3-c6e3a59a2d77.png)
![2018-01-06_00 37 00](https://user-images.githubusercontent.com/19416768/34619825-5cd23958-f23b-11e7-962e-9f68dfadbba1.png)

**Comment by defeatedcrow** [comment]
Thank you for the report!
It fixed in a3c44c0.
