### ISSUE TITLE
[Question]How could I add blocks or items to config file using NBT tag?

### ISSUE THREAD

**Issue by ym1025** [defeatedcrow/HeatAndClimateMod#230]
In detail, I wanted to machines of IC2 and Mekanism to generate HaC's heat, but there is no information for adding blocks with NBT tag to config files in the documentation.

**Comment by defeatedcrow** [comment]
No config documentation is available for support for NBT Tile. (There is no plan for that.)

It requires a modding technique, so it is not appropriate to support it in the config. I don't think I need to make up for the technical deficiencies of those who can't make add-ons.

If you do it as an add-on, you can do that by using BlockHeatTierEvent in  the HaCAPI .
Here is an example plugin for a Simple Difficulty block.
https://github.com/defeatedcrow/HeatAndClimateMod/blob/1.12.2_v3/main/java/defeatedcrow/hac/plugin/sd/DCPluginSD.java#L108
