### ISSUE TITLE
hi, I have some problems when playing this mod with IC2.

### ISSUE THREAD

**Issue by w123456w30w** [defeatedcrow/HeatAndClimateMod#232]
behavior is similar this [issue](https://github.com/defeatedcrow/HeatAndClimateMod/issues/229)
when i put HAC and IC2 in the mods, The UU mechanism of IC2 will be completely broken.
the specific is the IC2 scanner(item id /give @a ic2:te 1 64) cannot put any item into scanning, and the amount of UU fluid required for the scanned item is infinite.
and this issue happens randomly, sometimes it works normally.
most time they can't
now i'm hosting a server 
hope the log file can help with this issue
due to IC2 has not been updated a long time, i can only come here for help
i'm sorry about that
[latest.log](https://github.com/defeatedcrow/HeatAndClimateMod/files/7532335/latest.log)

**Comment by defeatedcrow** [comment]
This is a bug in IC2. It's not a HaC bug.
It has been reported that the same bug can be reproduced in different environments without HaC.
It is inappropriate to report an issue to this project and I have nothing I can do for the IC2 project. You should report to the IC2exp project. (IC2exp is a closed project and I can't see the source code, so I can't even verify the cause of the bug.)
The stagnation of the IC2 project is not a reason to ask the authors of other mods to fix it.
