### ISSUE TITLE
Can climate parameters of block/armor with NBT set?

### ISSUE THREAD

**Issue by delta-nos** [defeatedcrow/HeatAndClimateMod#234]
In parameter config file (ex. block_climate_patameter.json), I can set this parameters of block/item with metadata, but are there no syntax to set it by NBT of them?
for example, Tinker's-style armor has NBT to separate material types.

**Comment by defeatedcrow** [comment]
This config has no plans to support NBT.

This is a config to support blocks in other mods and cannot support NBT with the free syntax of other mods. The purpose of using NBT is not compatible between mods, and reading and writing of NBT cannot be generalized.
(In the case of Tink, it is a case where the NBT description method can be standardized. The purpose is different from that case, and it is an inappropriate comparison.)

If you want to use the block NBT, you can use API events.
https://github.com/defeatedcrow/HeatAndClimateLib/blob/1.12.2_v3/main/java/defeatedcrow/hac/api/climate/BlockHeatTierEvent.java
This can be implemented in the same way as ForgeEvent.

An example implementation of this event is included in the plugin for Simple Difficulty.
https://github.com/defeatedcrow/HeatAndClimateMod/blob/1.12.2_v3/main/java/defeatedcrow/hac/plugin/sd/DCPluginSD.java#L108

**Comment by delta-nos** [comment]
my implementation is worked. thanks for your explanations!
