### ISSUE TITLE
[Soft Crash] LogSpam related to Hwyla when looking at the Chemical Reactor

### ISSUE THREAD

**Issue by gatoborrachon** [defeatedcrow/HeatAndClimateMod#236]
**What is happening**
+When you look at the (advanced) Chemical Reactor you will get a massive logspam about a soft crash when you use [Hwyla](https://www.curseforge.com/minecraft/mc-mods/hwyla) (Also know as Waila)

**Steps to reproduce**
1. Add 'Heat and Climate' and [Hwyla](https://www.curseforge.com/minecraft/mc-mods/hwyla)
2. Enter to any world
3. Place the Chemical Reactor
4. Check the Log (Or you can use VanillaFix to get the warnings of the Soft Crash In-Game)

**Screenshots**
(Using VanillaFix)
![2021-12-02_20 31 35](https://user-images.githubusercontent.com/61126174/144534937-de95f24d-4335-4bde-96fa-7d1b311585c0.png)

**Files**
+Crash Report from VanillaFix: https://pastebin.com/jJ9qqGpT

-Both the Log and the Debug are bloated of LogSpam
+Log: [latest.log](https://github.com/defeatedcrow/HeatAndClimateMod/files/7646419/latest.log)
+Debug: [debug.log](https://github.com/defeatedcrow/HeatAndClimateMod/files/7646422/debug.log)

**Versions**
+Forge: 14.23.5.2855
+HeatAndClimateMod: 3.8.5
+HeatAndClimateLib: 3.8.2
+Hwyla: [1.8.26-B41_1.12.2](https://www.curseforge.com/minecraft/mc-mods/hwyla/files/2568751)
+VanillaFix (Optional): [1.0.10-150](https://www.curseforge.com/minecraft/mc-mods/vanillafix/files/2915154)

**Additional Notes**
+I tried older versions (3.8.1 in both HaCM and HaCL) but i still get the same soft-crash logspam in the Log, i don't remember them when i was playing some months ago (i stopped recently due to school)
-I also switched back to the normal JVM (i use OpenJ9) but i still get it

**Comment by defeatedcrow** [comment]
Thank you for your report.

The chemical reaction tank had a bug. (There was an incorrect process that returned null to the fluid capability.) I'll fix it at the next update!

**Comment by gatoborrachon** [comment]
ok, many thanks

**Comment by defeatedcrow** [comment]
It fixed in 4e3bc4b, and it will be included in the next version.
