### ISSUE TITLE
[Request] Make the Chemical Reactor be able to process more than 1 quantity of an ItemStack (as Input)

### ISSUE THREAD

**Issue by gatoborrachon** [defeatedcrow/HeatAndClimateMod#237]
**Proposed Idea**
As the title says, i kindly wanted to request you to make the Chemical Reactor to take any quantity of an ItemStack (as input in a recipe), more details below:

**Additional Notes**
+While i was implementing a recipe that uses the quantity of 8 Ash Dust as input (along with another item), i noticed that the Chemical Reactor only takes 1 Ash Dust every time it process the recipe (giving the exact quantity of Outputs), so i can only think that this is due to how the recipe system works, this already happened to me a lot before with other mods (that are dead), but i know that this simple change could break lots of things or take a lot of time

-So as always, feel free to close this request (without saying anything) in case you don't want to implement this (by any reason), or if this is the expected behavior of the Chemical Reactor, i will try to change my recipes, don't worry

-I also noticed that all the recipes from the Chemical Reactor only use 1 quantity of each input, so i will totally get it if you don't want to implement this

**Comment by defeatedcrow** [comment]
I thought this would be a useful change for players, so I've updated [a8eb64f](https://github.com/defeatedcrow/HeatAndClimateLib/commit/a8eb64fefae23132f5d06a7b8f31c9ba3c05a22f) and 4e3bc4b to handle stack sizes of 2 and above.
This change has been applied to reactors and IBC reactors.

However, those machines cannot consume items across multiple slots, so you need to have enough items in one slot.

**Comment by gatoborrachon** [comment]
> However, those machines cannot consume items across multiple slots, so you need to have enough items in one slot.

yeah, many thanks for implement it, i will consider this, thanks a lot 

EDIT: (After looking that you just required to [change 1 variable](https://github.com/defeatedcrow/HeatAndClimateMod/blob/4e3bc4b80446fbfcc2d96169f29f3c481f5b1bf9/main/java/defeatedcrow/hac/machine/block/TileReactor.java#L522), now i feel stupid, sorry, i thought that it could be as hard as it was in another mod's machine (Pneumaticraft))
