### ISSUE TITLE
[1.10.2]ModularPowersuitsとの競合

### ISSUE THREAD

**Issue by wachiki** [defeatedcrow/HeatAndClimateMod#24]
初めまして、当Modを楽しませて頂いていましたが、競合と思わしき現象を確認したので投稿させて頂きます

競合内容：該当Modで追加されるPower fistを使用する際、Axe,Pickaxe,shovelのモジュールが機能しない
競合と判断した理由：虱潰しに確認時、当Modを追加した直後、モジュールが機能しない事を目視したため

▼確認時の環境
・Minecraftforge1.10.2-12.18.3.2511
・ModularPowersuits-1.10.2-1.2.129.jar
・HeatAndClimateLib-1.10.2-1.6.4.jar
・HeatAndClimateMod-1.10.2-1.6.5.jar

▼使用しているJava
・Java8　jre1.8.0_161(パスの指定をしております)

▼その他の特筆事項
モジュールが機能しないだけで、クラッシュはしないためクラッシュレポートが生成されませんでしたorz

競合確認時の流れは
「チートONで新規ワールド作成後、一度クリエイティブに変更　Powerfistを取り出し
ティンカーテーブルでバッテリーと前述の3種のモジュールを追加、オーバークロックを限界まで上げた状態で
サバイバルモードに戻し　近隣の木や石、土を掘り返す」
....と言うものでした　最初は他の大型Modか何かの前提Modにあたりをつけていたのですが
前述のモジュール機能が復活せず、諦めて最低環境(ForgeとMPSのみ)から5つずつほど
虱潰しに追加しては確認を繰り返し、HaC追加後にモジュールが機能しない現象に直面
ForgeとMPS以外をすべて外して再度確認し、特定した所存であります。

**Comment by defeatedcrow** [comment]
今回提示されているModはHaCが連携しているMod（ビルド時に開発環境に加えているMod）ではないですし、私は該当のModの機能や遊び方は知りません。
対応に差し支えるので、次回からは作者に検証を求めるのであれば必要な情報を渡してください。
- 該当のアイテム名（ゲーム内での正しい名称）
- 仕様通りに動作した場合の具体的な効果（「機能しない」ではわかりません）
- 使用方法（デバッグで動かす方法があればその方法、無ければ実機での使用方法を）

今回は情報不足のため修正箇所と目的が不明瞭なので、こちらで適当に解釈し対処しました

「Axe,Pickaxe,shovelのモジュール」という文言から採掘関係のEventと推測し、双方のソースコード上でForgeAPIの採掘速度関係のイベントPlayerEvent.BreakSpeedを実装している箇所、
HaC側: OnMiningEventDC#preMining
MPS側:HarvestEventHandler#handleHarvestCheck
を比較し、HaC側で原因になっていそうな処理（不要な初期化処理）を除去することで対応しました。

直っているかはわかりませんが、該当のアイテムの使用方法が分からず、動作確認できませんので対応はここまでとします。

**Comment by defeatedcrow** [comment]
fixed in ead3795

**Comment by wachiki** [comment]
修正後の1.6.6へ更新しゲーム内での正常な動作を確認致しました、まずは対応して頂いた事に感謝致します。
以後、また何かしらの機会で不具合報告をする場合は掲示された内容を肝に銘じておきます、申し訳ないorz

念のため、現時点で私に可能な範囲でのご疑問の返信も添えておきます、宜しければご参考に。
＞該当のアイテム名（ゲーム内での正しい名称）
アイテム名：Power Fist(内部名称はpowersuits:powerToolでした)
ゲーム内での正しい名称がアイテムの名前なのか内部名称なのか
素人の私には測りかねたのでどうせならと両方記述させて頂きました。

＞仕様通りに動作した場合の具体的な効果（「機能しない」ではわかりません）
＞使用方法（デバッグで動かす方法があればその方法、無ければ実機での使用方法を）
こちらの情報の抜けは本当に申し訳ない、自分の馬鹿さ加減に返す言葉もありませんorz

Power Armor Tinker Table(powersuits:tile.tinkerTable)を設置して使用し
UI左に表示されるPower Fistのアイコンをクリックで選択、Energyの項目にある何れかのBatteryモジュール
(Basic Battery～Ultimate Battery)のアイコンをクリック選択しUI下部に表示されるInstallボタンを押下
同様にToolの項目にあるAxe,Pickaxe,shovelと言う名前のアイコンのモジュールを選択肢Installボタンを押下
その後Axe,Pickaxe,shovelのモジュールをクリックして選択している時にUI右下に表示される
Overclockのスライダーを一番右までクリック長押ししながら操作した場合....
えー、と、挙動の表現単体だと自分の語彙で伝わるか不安なので....
バニラ環境でダイヤのツールに効率強化Vを付与、ビーコンで効率強化効果の機能を最大Lvで
使ったかのような、採掘に必要なフレーム数が0または0に近い数字になったかのような採掘、採取速度に
強化される、と言うのが本来の挙動となります

問題のVersionだった1.6.5ではOverclockのスライダーをどの位置においても何ら採掘、採取速度に
微塵も変化が起きず、HaCをmodsから抜くと採掘、採取速度にきちんと変化があったため
自分の中でAxe,Pickaxe,shovelのモジュールが機能しなくなってしまう、と感じそのまま書き込んでしまった次第
重ね重ね申し訳ない....改めて、迅速な対応をして頂き有難う御座いました。
