### ISSUE TITLE
Crash When Loading Game Caused By Heat and Climatelib

### ISSUE THREAD

**Issue by UberbeastX** [defeatedcrow/HeatAndClimateMod#240]
[crash-2021-12-27_16.06.47-client.txt](https://github.com/defeatedcrow/HeatAndClimateMod/files/7781920/crash-2021-12-27_16.06.47-client.txt)

**Comment by defeatedcrow** [comment]
Thank you for your report.
This is a bug in HaCLib. It will be fixed in the next update.

**Comment by UberbeastX** [comment]
No problem thanks for making a cool climate mod

**Comment by defeatedcrow** [comment]
It fixed at https://github.com/defeatedcrow/HeatAndClimateLib/commit/8fd75d8ca879863224ac4f3350ee39a65fa1d85d.
