### ISSUE TITLE
No Climate Damage With First Aid Mod 

### ISSUE THREAD

**Issue by UberbeastX** [defeatedcrow/HeatAndClimateMod#241]
Sorry to bother you again but when messing around with this mod and the first aid mod I realized that I take no climate damage for some reason. Like I can stand in frostbite climate and nothing happens. I'm not sure what causes it but it hope you can find it out

**Comment by defeatedcrow** [comment]
This project does not guarantee any normal operation except for the plug-in targets shown [here](https://github.com/defeatedcrow/HeatAndClimateMod/blob/1.12.2_v3/main/resources/ReadMe_Plugin.txt).
Forge also has an API for damage manipulation for modder, which can be used to neutralize HaC's climate damage. (If it disables the damage, it can also disable the damage effect.) I don't understand the purpose of the damage reduction intended by the First Aid Mod, however, I think it's legitimate for other mods or players to negate HaC's climate damage.

Choose and use mod combinations at your own risk. It's your freedom.

**Comment by UberbeastX** [comment]
ok
