### ISSUE TITLE
[Suggestion] The ability to poison or taint food and drinks with the poison in the mod 

### ISSUE THREAD

**Issue by UberbeastX** [defeatedcrow/HeatAndClimateMod#242]
Exactly what it says, I think it would make a cool feature for the sake of messing with people

**Comment by defeatedcrow** [comment]
I couldn't read "what this element means in Minecraft and has a purpose as a gameplay or level design". It looks very boring to me (sorry) and I find it unpleasant that your easy ideas pollute my project. It's also very unpleasant about what you call "cool" what makes my mod player uncomfortable or hurt.

Make your ideas a reality as your project, at your own risk.

You aren't using your resources, you're not working on your own, you're only giving me instructions, and you're trying to realize your ideas. If other users find your idea uncomfortable, it's me who gets the complaint. This your act is very cowardly.

This is clearly outside the scope of support for this project.
**The act of opening an issue with such a thing as a "Suggestion" will be closed immediately without comment in the future.**
