### ISSUE TITLE
Potion effect Displayed ≠ Potion effect upon consumption

### ISSUE THREAD

**Issue by Devalut** [defeatedcrow/HeatAndClimateMod#243]
Ex. Coke "EXP Absorbtion" but when consumed gain the effect "Projectile Protection"
![Potion effect problem](https://user-images.githubusercontent.com/20247202/152584989-fe4eb7b0-254b-4476-a2e3-f773a68eecc4.png)

**Comment by defeatedcrow** [comment]
Thank you for your report!
It fixed at [2c8db40](https://github.com/defeatedcrow/HeatAndClimateMod/commit/2c8db40c7711b891bfb945a66b6db2799466e2b8).

The drinking effect has been fixed to be the same as a tooltip.
There were other problems, so they have been fixed.
- Fixed the effect amplifier of aged drinks being too low.
- Added the potion amplifier display (III-XV) missing in the vanilla tooltip to en_us.lang.
