### ISSUE TITLE
New gauntlet description

### ISSUE THREAD

**Issue by Devalut** [defeatedcrow/HeatAndClimateMod#244]
![Untitled](https://user-images.githubusercontent.com/20247202/152588777-ea0eb0fc-ba3f-4440-a286-c730a66ab752.png)

**_And I haven't the slightest clue on reading logs so please forgive me if it's painfully obvious._**
<details> 
  <summary>Spoiler</summary>

-    [11:02:13] [Client thread/ERROR] [jei]: Failed to get tooltip: 1xitem.dcs_color_gauntlet2@4 dcs_climate:dcs_color_gauntlet2
- java.util.UnknownFormatConversionException: Conversion = 'U'
- 	at java.util.Formatter$FormatSpecifier.conversion(Unknown Source) ~[?:1.8.0_261]
- 	at java.util.Formatter$FormatSpecifier.<init>(Unknown Source) ~[?:1.8.0_261]
- 	at java.util.Formatter.parse(Unknown Source) ~[?:1.8.0_261]
- 	at java.util.Formatter.format(Unknown Source) ~[?:1.8.0_261]
- 	at java.util.Formatter.format(Unknown Source) ~[?:1.8.0_261]
- 	at java.lang.String.format(Unknown Source) ~[?:1.8.0_261]
- 	at defeatedcrow.hac.magic.item.ItemColorGauntlet2.addInformation2(ItemColorGauntlet2.java:145) ~[ItemColorGauntlet2.class:?]
- 	at defeatedcrow.hac.core.base.DCItem.addInformation(DCItem.java:100) ~[DCItem.class:?]
- 	at net.minecraft.item.ItemStack.getTooltip(ItemStack.java:707) ~[aip.class:?]
- 	at mezz.jei.plugins.vanilla.ingredients.item.ItemStackRenderer.getTooltip(ItemStackRenderer.java:42) [ItemStackRenderer.class:?]
- 	at mezz.jei.plugins.vanilla.ingredients.item.ItemStackRenderer.getTooltip(ItemStackRenderer.java:23) [ItemStackRenderer.class:?]
- 	at mezz.jei.render.IngredientRenderer.getIngredientTooltipSafe(IngredientRenderer.java:138) [IngredientRenderer.class:?]
- 	at mezz.jei.render.IngredientRenderer.getTooltip(IngredientRenderer.java:109) [IngredientRenderer.class:?]
- 	at mezz.jei.render.IngredientRenderer.drawTooltip(IngredientRenderer.java:90) [IngredientRenderer.class:?]
- 	at mezz.jei.gui.overlay.IngredientGrid.drawTooltips(IngredientGrid.java:119) [IngredientGrid.class:?]
- 	at mezz.jei.gui.overlay.IngredientGridWithNavigation.drawTooltips(IngredientGridWithNavigation.java:102) [IngredientGridWithNavigation.class:?]
- 	at mezz.jei.gui.overlay.IngredientListOverlay.drawTooltips(IngredientListOverlay.java:173) [IngredientListOverlay.class:?]
- 	at mezz.jei.gui.GuiEventHandler.onDrawScreenEventPost(GuiEventHandler.java:119) [GuiEventHandler.class:?]
- 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1618_GuiEventHandler_onDrawScreenEventPost_Post.invoke(.dynamic) [?:?]
- 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
- 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
- 	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:397) [ForgeHooksClient.class:?]
- 	at sun.reflect.GeneratedMethodAccessor42.invoke(Unknown Source) ~[?:?]
- 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
- 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_261]
- 	at net.optifine.reflect.Reflector.callVoid(Reflector.java:669) [Reflector.class:?]
- 	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1462) [buq.class:?]
- 	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1119) [bib.class:?]
- 	at net.minecraft.client.Minecraft.run(Minecraft.java:3942) [bib.class:?]
- 	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
- 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_261]
- 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
- 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
- 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_261]
- 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
- 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
- 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_261]
- 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
- 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
- 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_261]
- 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
- 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
- 	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
- 	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]

</details>

**Comment by defeatedcrow** [comment]
Thank you for your report!
It fixed at 2c8db40.
