### ISSUE TITLE
SPICE seasoning becomes HONEY when adding into tea pot

### ISSUE THREAD

**Issue by Courier99** [defeatedcrow/HeatAndClimateMod#245]
Forge: 14.23.5.2855
Mods:
HaCLib 3.8.5
HaC 3.8.10

If adding anything with oreDict "listAllspice" (including herb leaves, garlic, ginger, cinnamon, and spice mix in HaC) into a teapot, the teapot GUI shows that it stores HONEY instead of SPICE, and any liquid taken out from that teapot is also seasoned by HONEY. Is this a feature or a bug?

**Comment by defeatedcrow** [comment]
Thank you for your report.

This is a bug. Spice items should have given SPICE to the drink.
This will be fixed in the next update.

**Comment by defeatedcrow** [comment]
It fixed at 9ec07df,
