### ISSUE TITLE
Brewing machines stop working in 3.8.11

### ISSUE THREAD

**Issue by Courier99** [defeatedcrow/HeatAndClimateMod#246]
Forge: 14.23.5.2855
Mods:
HaCLib 3.8.6
HaC 3.8.11

After updating to the new version 3.8.11 via curseforge, both the wooden and metal brewing machine stop working even though under a proper climate condition. Everything goes well after rolling back to 3.8.10. 

![2022-02-22 00-01-282](https://user-images.githubusercontent.com/99863862/154996634-2b0cbf97-a7da-4df7-9263-8e9a8c03b8c5.gif)

**Comment by defeatedcrow** [comment]
It's a bug and fixed at db4b0d2. Thank you!
