### ISSUE TITLE
confused by the translation name

### ISSUE THREAD

**Issue by Pliosauroidea** [defeatedcrow/HeatAndClimateMod#247]
I'm translating the newest version into chinese and confused by the translation of "tile.dcs_build_wallpaper_presscake.name"
in japanese ,its translation is given "アクセントクロス(花)" and the english version "Accent Wallpaper (Flower)"

but in real gameplay i found the block and really can't see any "flower"
so am I misunderstand the name or are there any explanation about it?

![image](https://user-images.githubusercontent.com/37920182/156868247-9e155098-f69b-4fdf-9065-329fccf9f31c.png)

**Comment by defeatedcrow** [comment]
"Accent Wallpaper (Flower)" is a specification that a flower pattern appears when the height is 5 blocks or more. (I'm trying a pseudo CTM.)
At a height without a flower pattern, you can try it as a wallpaper with vertical stripes.

**Comment by Pliosauroidea** [comment]
ok got it, thanks for the explaination, I will pr the chinese translation soon today.
