### ISSUE TITLE
Cooled/Hot/Brittle/& Dust Mangalloy uses Incorrect Textures

### ISSUE THREAD

**Issue by EmilyBZ** [defeatedcrow/HeatAndClimateMod#249]
Mangalloy is using Tool Steel textures for Cooled, Hot, Brittle, and Dust blocks. Attached pictures with WAILA captions:

![CooledManga](https://user-images.githubusercontent.com/67805293/158001489-406b96fe-e9d1-45c2-b610-9e1a91ad0982.png)
![BrittleManga](https://user-images.githubusercontent.com/67805293/158001493-765f3c97-5f7b-4afc-9f05-17f3f5504f47.png)
![DustManga](https://user-images.githubusercontent.com/67805293/158001495-f232be6a-a542-4340-b1dd-84fcff91bd5e.png)
![HotManga](https://user-images.githubusercontent.com/67805293/158001496-dc7f4a14-0e93-49e2-af96-0810fbd54b76.png)
:

**Comment by defeatedcrow** [comment]
Thank you for your report.
I've confirmed the problem and fixed it!

**Comment by defeatedcrow** [comment]
It fixed at fb685d4.
