### ISSUE TITLE
Game crashed while exploring world

### ISSUE THREAD

**Issue by Microsoft6477** [defeatedcrow/HeatAndClimateMod#252]
I have no idea which mod cause this issue
### versions:
forge: 14.23.5.2860
HeatAndClimateLib: 3.8.7
HeatAndClimateMod: 3.8.17

### some mods mentioned in the crash report：
ImmersiveEngineering-0.12-98
HeatAndClimate
BetterFoliage-MC1.12-2.3.3

### crash reports:
[crash reports.zip](https://github.com/defeatedcrow/HeatAndClimateMod/files/8569942/crash.reports.zip)

**Comment by defeatedcrow** [comment]
There was a similar example in the past. (https://github.com/defeatedcrow/HeatAndClimateMod/issues/210)
There is a crash when the vanilla method references the IE base class (BlockIEBase.java) and it looks like there is a problem on the IE side.

This is not a problem on the HaC side, so I can't fix it. (We recommend contacting IE.)
However, HaC can refrain from using the vanilla method that causes a crash, and I will consider to fix it to the next HaCLib.
