### ISSUE TITLE
クラッシュが頻発

### ISSUE THREAD

**Issue by Gwaewluin** [defeatedcrow/HeatAndClimateMod#253]
このゲームは一年前くらいにやめましたが、いま復帰してプレイ続けました。
一年前くらいでゲームをやる時にクラッシュはほぼありませんでした。

復帰した時に幾つかのmodをアップデートしました。
EnderIO-1.12.2-5.2.61->EnderIO-1.12.2-5.3.70
ExtremeReactors-1.12.2-0.4.5.67->ExtremeReactors-1.12.2-0.4.5.68
Fluxnetworks-1.12.2-4.0.15-32->FluxNetworks-1.12.2-4.1.1.34
FTBUtilities-5.4.1.130->FTBUtilities-5.4.1.131
GVCLib__1.12.2__2.9->GVCLib__1.12.2__5.3.1
HeatAndClimateLib_1.12.2-3.6.6->HeatAndClimateLib_1.12.2-3.8.7
HeatAndClimateMod_1.12.2-3.6.8->HeatAndClimateMod_1.12.2-3.8.17
HMGDollsFrontLine1.12.2.β.18.1->HMGDollsFrontLine1.12.2.β.21.1
zerocore-1.12.2-0.1.2.8->zerocore-1.12.2-0.1.2.9

そして、いまゲームをプレイ中でクラッシュが頻発になりました。
使用しているmodは沢山ですから、クラッシュの原因は特定が難しいと思いますが、一応ゲームのメッセージによって報告します。
![crash](https://user-images.githubusercontent.com/104683682/166108686-65e1f116-ecc8-42db-a4ca-2e3365966a44.png)
[crash-2022-04-22_20.10.02-server.txt](https://github.com/defeatedcrow/HeatAndClimateMod/files/8597171/crash-2022-04-22_20.10.02-server.txt)
[crash-2022-04-24_00.41.25-server.txt](https://github.com/defeatedcrow/HeatAndClimateMod/files/8597172/crash-2022-04-24_00.41.25-server.txt)
[crash-2022-04-24_00.45.04-server.txt](https://github.com/defeatedcrow/HeatAndClimateMod/files/8597173/crash-2022-04-24_00.45.04-server.txt)
[crash-2022-04-30_16.48.23-server.txt](https://github.com/defeatedcrow/HeatAndClimateMod/files/8597164/crash-2022-04-30_16.48.23-server.txt)
[crash-2022-04-30_16.53.04-server.txt](https://github.com/defeatedcrow/HeatAndClimateMod/files/8597165/crash-2022-04-30_16.53.04-server.txt)
[crash-2022-04-30_19.37.32-server.txt](https://github.com/defeatedcrow/HeatAndClimateMod/files/8597166/crash-2022-04-30_19.37.32-server.txt)
[crash-2022-04-30_19.56.13-server.txt](https://github.com/defeatedcrow/HeatAndClimateMod/files/8597167/crash-2022-04-30_19.56.13-server.txt)
[crash-2022-04-30_20.11.02-server.txt](https://github.com/defeatedcrow/HeatAndClimateMod/files/8597168/crash-2022-04-30_20.11.02-server.txt)

**Comment by defeatedcrow** [comment]
ご報告ありがとうございます。

8a75738abae4c70e3a505c47b78c1d6301d49d48 で、絵画に関する、クラッシュの原因と思われるコードを修正しました。
新しいバージョンv3.9.0に適用されています。

v3.9.0以降でクラッシュが再発する場合は、再度調査いたしますのでお知らせください。

**Comment by Gwaewluin** [comment]
30分プレイ続いてもクラッシュは出ませんでした、ご対応ありがとうございました。
