### ISSUE TITLE
Hard-coded backslashes cause config generated in unwanted path under Linux

### ISSUE THREAD

**Issue by kappa-maintainer** [defeatedcrow/HeatAndClimateMod#255]
What happened:
![2022-05-03_17-44](https://user-images.githubusercontent.com/11038263/166433469-23b7f26c-c21b-42c3-8de9-b9cf86fb3be4.png)

I think https://github.com/defeatedcrow/HeatAndClimateMod/blob/6828bb037efa39fa53839634aad79aa237628330/main/java/defeatedcrow/hac/main/worldgen/vein/VeinTableJson.java#L382 should use File.separator inside.

**Comment by defeatedcrow** [comment]
Thank you for pointing out.

It has been fixed in 51017cd7d5340d99beee4e44d5745321b9d2fb9b.
