### ISSUE TITLE
only one malted rice used when making sake

### ISSUE THREAD

**Issue by mokkunsimu** [defeatedcrow/HeatAndClimateMod#256]
HaCLib Ver. 3.9.0
HaCMod Ver. 3.9.1
Using on: Linux server

以下、日本語で報告します。
醸造タンクにて米麹+酵母で日本酒を造ったところ、米麹が８個消費されるべきところ１個のみ消費されています。
泡盛においても同様の症状が発生しています。

**Comment by mokkunsimu** [comment]
「発酵した砂糖汁」の糖蜜使用レシピでも同様でした。おそらく発酵のうち１種の材料を複数個使うものすべてが同様のバグを持っているものと考えられます。

**Comment by defeatedcrow** [comment]
ご報告ありがとうございました！
レシピに不具合があったので、 ea8a23c で修正いたしました。
