### ISSUE TITLE
Lotus cannot grow in certain growing stages

### ISSUE THREAD

**Issue by Courier99** [defeatedcrow/HeatAndClimateMod#259]
Forge: 14.23.5.2855
From HaC 3.9.0 & HaClib 3.9.0, regardless the option "Crop Seasonality" is turned on or off, lotus in its first three growing stages (block ID: dcs_climate:dcs_crop_lotus2@<0/1/2>) stops growing into the next stage. When using bone meal on these lotus, it consumes bone meal but still keeps in the current stage.
![2022-06-09 02-59-24 00_00_05-00_00_12~1](https://user-images.githubusercontent.com/99863862/172700230-a9f1eb73-829d-48b6-a951-0cf956733eb2.gif)

**Comment by Courier99** [comment]
I make some more tests and find black lotus has the same problem.

**Comment by defeatedcrow** [comment]
Thank you for your report.
The problem was fixed in 18873a9 .
