### ISSUE TITLE
他modのアイテムを自販機の通貨として使用できない

### ISSUE THREAD

**Issue by mokkunsimu** [defeatedcrow/HeatAndClimateMod#260]
HaCLib Ver. 3.9.2
HaCMod Ver. 3.9.3
動作環境: Linux serverならびにWindows

タイトル通りです。
configでアイテムを記入しても通貨がエメラルド（読み込み失敗時のデフォルト？）になります。
試したのは自作通貨追加modとLittleTilesのアイテム群です。
ダイヤモンド等、バニラやHaCのアイテムには変更できることを確認済です。
これは仕様でしょうか？

**Comment by defeatedcrow** [comment]
modの読み込み順の問題で、HaCよりロードが遅いmodのアイテム（登録処理が終わっていない）の登録ができていなかったようです。
次回更新でコンフィグファイルのロードタイミングを少し遅らせるので、解消すると思います。

**Comment by defeatedcrow** [comment]
f45829b で修正しました！
