### ISSUE TITLE
switch torch render issue

### ISSUE THREAD

**Issue by Pliosauroidea** [defeatedcrow/HeatAndClimateMod#264]
swedish torch can help see through blocks after placed.
![ruidian](https://user-images.githubusercontent.com/37920182/185048371-8b3310a7-e2be-47e5-9230-61e502d04326.png)

mod ver:3.9.6

**Comment by defeatedcrow** [comment]
Thank you for your report. i had overlooked that...
It fixed at 7176f36a7e718a4c6c34762fddf3b5f79813cb22 .
