### ISSUE TITLE
BlockGasBurnerがガス性ではない燃料を受け付けてしまう

### ISSUE THREAD

**Issue by SkyTheory** [defeatedcrow/HeatAndClimateMod#265]
表題の通り、本来ガス性の燃料のみを使用できるはずのガスバーナーが、右クリックした際の処理においてガス性でない燃料を受け取ってしまう問題があります。
TileGusBurnerの方ではfluid.isGaseous()によるチェックがありますが、BlockGasBurnerの方ではそれが抜けてしまっていることが原因ではないかと思います。
なお、隣接するタンクからの吸出し処理の方は、通常通りガス性の燃料のみを受け取るよう動作しています。

**Comment by defeatedcrow** [comment]
https://github.com/defeatedcrow/HeatAndClimateMod/commit/363de9878f914c8c4bb655987bf6f495fec3f29c で修正しました！
ご報告ありがとうございました。
