### ISSUE TITLE
Vending Machine

### ISSUE THREAD

**Issue by Night-Shadow107** [defeatedcrow/HeatAndClimateMod#266]
Hello does someone know how i can change the pay item in the vending machine in 1.12.2

**Comment by defeatedcrow** [comment]
Hello!
main.cfg has a "Display Case Currency" config to change the vendor's currency. Set the RegistryName of the desired item.

For example, if you write thermalfoundation: coin:1, it will look like this:
![2022-06-12_15 37 23](https://user-images.githubusercontent.com/6741099/199478341-8ea57315-ccc7-4e81-b6e6-5dab50a4b577.png)
