### ISSUE TITLE
Custom layered veins with HaC

### ISSUE THREAD

**Issue by Primitive-Human** [defeatedcrow/HeatAndClimateMod#267]
HaC is one of the few mods that has layered ore veins (and the other one I can remember is GTCEu). I can find options of which ores each vein has, its size and frequency, but is it also possible to add custom veins without altering the default ones provided by HaC?

**Comment by gatoborrachon** [comment]
(If i recall correctly) yeah you should be able, just copy one of these files (as a template) and edit it

i never tried it before, but if i remember correctly, it should be possible, if not, well, i guess we have one doubt less

**Comment by Primitive-Human** [comment]
Tested as I usually would by duplicating and renaming, and tried finding the custom vein using WorldStripper, as Crow's Drill deletes the block entries in the custom vein. 

After clearing many chunks to bedrock except for the blocks in the custom vein, there has been no sight of my custom vein. I somewhat expected this, since the parameters for existing veins are configured in worldgen.cfg, and seem to be hardcoded for those veins only. I'm not going to try to edit my own variables into there, and instead go with CoFH World or Realistic Oreveins.

**Comment by defeatedcrow** [comment]
Hello.
The HaC ore deposits in 1.12 are hard-coded and there is no ability to add new veins. (They are prototypes, and enums are used to prevent missing elements in order to work with the magic module.)

In 1.19HaC, it is planned to be able to add the type of deposit in the config.
