### ISSUE TITLE
The client does not synchronize server settings. v.1.12.2

### ISSUE THREAD

**Issue by SeagalKru** [defeatedcrow/HeatAndClimateMod#268]
(Google translation from Russian)

Hello!
Suggest a solution to the problem.
On my server, the settings for your mod, when creating the world, start the season from the 1st day of early spring. But at the same time, the duration of the year is 365 days and the period for spring is set from 59 to 150 days.

At the same time, I didn’t bother myself much with setting up the client, there I have a year of 240 days and spring from 31 to 90 days.

And when I go to the server, then the 31st day is indicated on my HUD (this is on the client), and not the 51st (this is on the server).

Is it possible to fix this so that the client receives the server settings when entering the world?

Thank you!

**Comment by defeatedcrow** [comment]
This mod requires matching server and client configs.
There are many other items that require matching configs, and (like many other mods) the player must voluntarily match the configs.

These are by design and there are no plans to fix them.

**Comment by SeagalKru** [comment]
Clear.
Sadly.
Thanks to.
