### ISSUE TITLE
[v4-alpha1] Item names and GUIs are not translated into English (US)

### ISSUE THREAD

**Issue by Iunius118** [defeatedcrow/HeatAndClimateMod#273]
### Mods
- Forge-1.19.2-43.2.0
- HeatAndClimate-1.19.2-v4-alpha1
- jei-1.19.2-forge-11.6.0.1011

### Screenshots
![2023-03-08_00 05 00](https://user-images.githubusercontent.com/18502177/223463066-b0fcb680-2737-4584-b2e0-918809112bd7.png)
![2023-03-08_00 06 08](https://user-images.githubusercontent.com/18502177/223463088-bb4f7424-da6e-4d68-a444-f9631b902e9c.png)

**Comment by defeatedcrow** [comment]
It fixed at v4-alpha2.
Thank you!
