### ISSUE TITLE
The texture of bellpepper and paprika is not correct.

### ISSUE THREAD

**Issue by shoestring-cut** [defeatedcrow/HeatAndClimateMod#276]
When trying to harvest bellpepper and paprika, we receive the unexpected.
![20230326001](https://user-images.githubusercontent.com/128956330/227773033-852d8a38-d124-4690-a780-6072c772a808.JPG)
![20230326002](https://user-images.githubusercontent.com/128956330/227773042-9fce98c4-24aa-4d41-ab08-9247c2d46798.JPG)
![20230326003](https://user-images.githubusercontent.com/128956330/227773051-3ff4e916-53ad-4451-b5dd-9581cd00b1dd.JPG)

The texture of the seeds is also different.
![20230326004](https://user-images.githubusercontent.com/128956330/227773052-dd72b234-d718-4d4f-b851-cddd02adf863.JPG)

**Comment by defeatedcrow** [comment]
It fixed at 727122c.
Thank you!
