### ISSUE TITLE
一括破壊MODで青の鉱石を破壊するとクラッシュする

### ISSUE THREAD

**Issue by sasasa1240** [defeatedcrow/HeatAndClimateMod#280]
他の鉱石は問題ないみたいです。
導入mod
forge-1.19.2-43.2.18
[1.19.2][forge43.1.1]mod_MineAllSMP_v2.6.6
HeatAndClimate-1.19.2-v4-alpha5

クラッシュレポートです。
[crash-2023-07-17_22.25.36-server.txt](https://github.com/defeatedcrow/HeatAndClimateMod/files/12070564/crash-2023-07-17_22.25.36-server.txt)

**Comment by defeatedcrow** [comment]
ご報告ありがとうございます!
v4-alpha6 ( https://github.com/defeatedcrow/HeatAndClimateMod/releases/tag/v4-alpha6 ) で直っていると思います。お試しください。
