### ISSUE TITLE
作物に肥料を使用した場合に、肥料の所持数が減少しない

### ISSUE THREAD

**Issue by shoestring-cut** [defeatedcrow/HeatAndClimateMod#281]
HaC作物、バニラの作物、バニラの草ブロックに対して肥料を使用した場合、
作物の成長があった場合であっても肥料の所持数が減少しない。

Minecraft 1.19.2
Forge 43.2.0
Java 17.0.3(64bit)

**Comment by defeatedcrow** [comment]
ご報告ありがとうございました！
eaeee00 で修正されました。
