### ISSUE TITLE
ロジェリアの名称について

### ISSUE THREAD

**Issue by shoestring-cut** [defeatedcrow/HeatAndClimateMod#282]
ロジェリアの作物(crops)の名称が「ロジェリアの種」、
ロジェリアの種(seend)の名称が「ロジェリア」となっており、
他の作物・種との平仄が合っていない。

Minecraft 1.19.2
Forge 43.2.0
Java 17.0.3(64bit)

**Comment by defeatedcrow** [comment]
ロジェリアの作物は「ロジェリアの種」であり仕様です。
海外文献などを漁って、種を搾油作物として利用している情報があったので作物を種とし、油源植物に設定しています。
Seed系アイテムは図鑑表示のため、「種」のような表記はなく種類名で統一されています。

故に「平仄が合っていない」という記述は他の作物と比較していない早とちりだろうと思われますが、
種とSeed系アイテムの混同の原因となるので、ロジェリアの作物は「ロジェリアの実」に変更しました。

eaeee00 にて修正されています。
