### ISSUE TITLE
Config dont work

### ISSUE THREAD

**Issue by LKD-PIX** [defeatedcrow/HeatAndClimateMod#283]
Disabling the HUD Config -> "Show Additional Tooltips" : OFF does not work

**Comment by defeatedcrow** [comment]
It fixed at [eaeee00](https://github.com/defeatedcrow/HeatAndClimateMod/commit/eaeee004f4f4c93d22b5919104c126587154c3a0).
We also plan to make further corrections in the next update.
(For some HaC items, we plan to add targets that will be disabled by "Show Additional Tooltips".)
Thank you!
