### ISSUE TITLE
Progress indication of fermentation jar

### ISSUE THREAD

**Issue by shoestring-cut** [defeatedcrow/HeatAndClimateMod#289]
発酵に使用する壺の進捗バーに、矢印以外のアイコン(通気？)が表示されてしまっている。
![fermentation](https://github.com/defeatedcrow/HeatAndClimateMod/assets/128956330/2af255ff-59ec-41ec-9f86-7fbd26250521)

Minecraft 1.19.2
Forge 43.2.0
HaC v4-alpha13

**Comment by defeatedcrow** [comment]
Fixed at https://github.com/defeatedcrow/HeatAndClimateMod/commit/7659b74ee87de1b1e32d28454be616035b688518 .
Thank you!
