### ISSUE TITLE
Cheese production

### ISSUE THREAD

**Issue by ghost** [defeatedcrow/HeatAndClimateMod#29]
A suggestion in regards to cheese production:
Currently: cheese requires viscera to be created. For automation or creating lots of cheese, it is difficult to overkill many creatures.
A method that does not require killing would be nice.
Suggestion: Cheese creation produces cheese culture which can be used in place of rennet as a starter culture. For example: Rennet + cream -> cheese + culture.  cream + culture -> cheese + culture
I'm not sure if github issue is a good place for discussion, if there is somewhere else for feedback, please let me know.

**Comment by defeatedcrow** [comment]
I can't help with personal play support.
There are other ways to add simple items or crafting recipes (like making add-on), so you can choose different ways other than to using me for several days.

There is no place to receive the idea of others.
This mod does not receive donations, workers and ideas of others, and it is operated only by the author's own funds.

**Comment by ghost** [comment]
Thank you for the response. Will mark as closed
