### ISSUE TITLE
いくつかの飲み物エンティティの表示バグ

### ISSUE THREAD

**Issue by M93hina** [defeatedcrow/HeatAndClimateMod#291]
・リンゴジュース、リンゴソーダ、野菜ジュースが全て水色の飲み物として表示されます。
・ミルクセーキ、グァバソーダ、日本酒のテクスチャが表示されません。
・ジュース・ソーダなどのグラス系のエンティティは、底がエンティティが重なったときのようにちらついてしまいます。

環境
1.19.2-forge-43.3.0
HeatAndClimate-1.19.2-v4-beta2
jei-1.19.2-forge-11.6.0.1019

画像はすべてクリエイティブタブから取り出したものです。
![2024-03-04_11 13 17](https://github.com/defeatedcrow/HeatAndClimateMod/assets/90587244/ae3af51a-0087-4b4a-b650-91f360a056c3)

**Comment by defeatedcrow** [comment]
https://github.com/defeatedcrow/HeatAndClimateMod/commit/27987f1fa81472b6f4a04da2f57efa26f5b420d3 で修正しました。
