### ISSUE TITLE
赤の銀バッチのバグ

### ISSUE THREAD

**Issue by Kaeruakira** [defeatedcrow/HeatAndClimateMod#292]
赤の銀バッチ 破砕の効果を受けた状態でブロックを破壊すると
壊したブロックだけ壊れずそれ以外は効果の通りに破壊されます
緑の銀ペンダント 整地の効果の場合はちゃんと自分が壊したブロックも壊れます

↓赤の銀バッチをつけた状態でブロックを破壊したとき

https://github.com/defeatedcrow/HeatAndClimateMod/assets/163561816/0ffb6e7d-2757-41b3-99ef-2852de4cfd28

使ってるforgeのバージョンは43.2.8です
HaCのみ入れても発生しました

**Comment by defeatedcrow** [comment]
https://github.com/defeatedcrow/HeatAndClimateMod/commit/27987f1fa81472b6f4a04da2f57efa26f5b420d3 で修正済みです。
再発する場合はお知らせください。
