### ISSUE TITLE
More of a question, but I'm trying to understand how to use the config to add temperatures to other blocks. [1.19.2-v4-alpha7]

### ISSUE THREAD

**Issue by TheUSSWatercooler** [defeatedcrow/HeatAndClimateMod#294]
![image](https://github.com/defeatedcrow/HeatAndClimateMod/assets/110517775/1f37603b-6653-47e1-8544-c939aea14c8c)
I'm not sure if I'm doing this right, but here I'm trying to make it so a modded block can heat up the player. I've checked that the block name I've entered is correct, and the .json is in the block_climate folder of the config folder, however the block does not heat up the player.
What am I missing?

**Comment by defeatedcrow** [comment]
Hello!

The "property" tab allows you to restrict some properties that a block has.
For example, if you assign a "lit" property to a vanilla furnace, it will only give heat when the furnace is burning.

In your file, heat will not be enabled unless the default "PropertyName" actually exists for the block.
So if you don't want to restrict a specific property, use "none" in the "property" tag and the "values" tag (which specifies the state of the property).

Like this: 
```
{
 "blockName": "nuclearcraft:uranium_rtg",
 "property": "none",
 "values": [
  "none"
 ],
 "heat": "HOT",
 "humidity": "NORMAL",
 "airflow": "TIGHT"
}
```

**Comment by TheUSSWatercooler** [comment]
I probably should've noticed that given what I had seen in the code. Thanks!
