### ISSUE TITLE
コンベアで鋼ブロックを製錬できない

### ISSUE THREAD

**Issue by soyo-mai** [defeatedcrow/HeatAndClimateMod#295]
画像のようにコンベアでの鋼精錬ラインを作りましたが、鋼粉末ブロックを投入すると、最初のSMELTING/TIGHTの部分で、赤熱した鋼インゴットに気候精錬されず、バニラかまどの精錬処理が入りバニラ鉄ブロックになってしまうという不具合を発見しました。
![2024-09-14_17 41 21](https://github.com/user-attachments/assets/a63983d3-a443-4a59-b420-90f2813e8ee2)
![2024-09-14_17 42 03](https://github.com/user-attachments/assets/83aea9f0-a70e-4d85-aa22-922fc8c31bcf)
![2024-09-14_17 42 26](https://github.com/user-attachments/assets/fec83bd9-3c6b-412c-a9f2-52b62153dcb8)
![2024-09-14_17 42 34](https://github.com/user-attachments/assets/6420f1a5-b20a-40cb-ba23-b8e6c53fdf66)

**Comment by defeatedcrow** [comment]
ご報告ありがとうございます。
https://github.com/defeatedcrow/HeatAndClimateMod/commit/d7dd8842f89b59ca93c58cb2ca01a55f6a8f3eab で修正しました！
