### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by LKD-PIX** [defeatedcrow/HeatAndClimateMod#296]
Hello, sorry to bother!

But, are you maybe planning on updating the mod to 1.20.1 any time in the future?
I am migrating a large Modpack of mine to that version and would really like to keep your mod, as we are using it a lot,
if you are planning for it for some time in the future we would wait.
Thanks already :)

**Comment by defeatedcrow** [comment]
Hello!
Thank you for always playing my mod!

Unfortunately, I have no plans to move to 1.20.1.
There are two reasons:

First, it will take more than two years to migrate HaC. (Work on the current 1.19.2 version also started two years ago and is not yet finished.)
So, if HaC finishes work on 1.19 and plans to migrate, it will be targeted at a more distant MC version.

The second reason is lack of motivation.
Originally, after I finished development on 1.12, I declared that I would migrate if MC made a big and ambitious update. The world altitude change and the underground enrichment were what I wanted, so I decided to migrate.
However, the current update is small and does not seem worth spending more than two years of work on. Until a bigger and more ambitious gameplay change is brought about, I intend to work on enriching 1.19.2. (I hope that they will improve the unpleasant internal lag of the server/client feel and redesign the vanilla level design. Although it's a long shot...)
