### ISSUE TITLE
Making cream from Milk/Milk Bag required new/perfect mortar

### ISSUE THREAD

**Issue by chrisshoes** [defeatedcrow/HeatAndClimateMod#31]
You can only make cream from a brand new mortar. Once the durability bar appears (you have used it once) it will no longer make cream.

**Comment by defeatedcrow** [comment]
Please place the cow on the fluid hopper. Then it collects the cream.
Recipes that make creams at mortar will be removed with the next update.

**Comment by chrisshoes** [comment]
Great thanks!
