### ISSUE TITLE
"world setting" config not working as it should?

### ISSUE THREAD

**Issue by SniperHauss89** [defeatedcrow/HeatAndClimateMod#33]
Hello, I am just curious if my observations are correct regarding one of the config options as it doesn't appear to be doing as described in the config file. That setting is this one:
  
  # Enable generating water blocks instead of lava blocks in the deep caves.
    B:"Enable Water Caves"=true

As I said it doesn't seem to work as intended I don't think as I am still getting lava generating deep underground like normal. I considered another mod might be preventing it but that turned out not to be the case either. The "submerged ocean cave" setting does work however so I thought I would report my observations as I would really like to use this feature for a modpack for some friends I am working on. 
version running is 2.5.1

Thank you for your time ;)

**Comment by defeatedcrow** [comment]
"Enable Water Caves" config works only with WET Biome. (Such as swamps and jungles.)
In other biomes, lava is generated.

If it doesn't work in WET Biome, it seems to be a bug. This config may not work if other mod modifies the cave generation in advance.

**Comment by SniperHauss89** [comment]
Oh ok that makes sense and may be something you might want to clarify in the config as I thought it was across everything (all biomes and everything) and I don't think I have any other mods that alter that sort of world gen.

Thank you for the response and sorry about forgetting about this support thread. xD
