### ISSUE TITLE
ガリレオ温度計について

### ISSUE THREAD

**Issue by 2z6c** [defeatedcrow/HeatAndClimateMod#34]
ガリレオ温度計で、温度SMELTING以上を示すはずのフロートが該当温度以上になっても浮きっぱなしで降りてきません。おそらく
https://github.com/defeatedcrow/HeatAndClimateMod/blob/7c44afd19d3560e17ecd9b69b30dc3fd7c77522e/java/defeatedcrow/hac/main/client/block/TESRThermometer.java#L43
でSMELTING以上のフロートへの処理が行われずループが打ち切られているためと思われます。

**Comment by defeatedcrow** [comment]
ご報告ありがとうございます。
e9922f7 で修正しました。
