### ISSUE TITLE
[Advice]Would u pls make a separation between the part of 'HeatAndClimate'  and  the part of 'AppleMilkTea‘

### ISSUE THREAD

**Issue by 333mhz** [defeatedcrow/HeatAndClimateMod#38]
As a modpacker，I really enjoy your AppleMilkTea2 mod.
When AppleMilkTea been updated to 1.12 version,you make 'Heat' and' Climate' an unavoidable things.
To be honest,I dont like such things of 'Heat' or 'Climate',but the things of cooking,machines and those crazy fancy tools.
I sincerely expect a config which can close the elements of  climate and temperature,
or just making separation from this mod into several mods (like buildcraft)which can be chosen to add in modpack.
Otherwise,'HeatAndClimate' cause serious worldgen lag in 1.12.2 forge server 2705,Hope u can fix it soon.

**Comment by defeatedcrow** [comment]
Many elements of heat and climate can be turned off with core.cfg and module.cfg. I have already stopped AMT2, but you can reproduce 'something similar' using config. Of course it is not perfectly identical.

**Comment by 333mhz** [comment]
________________________________
发件人: defeatedcrow <notifications@github.com>
发送时间: 2018年8月1日 10:08
收件人: defeatedcrow/HeatAndClimateMod
抄送: droashen; State change
主题: Re: [defeatedcrow/HeatAndClimateMod] [Advice]Would u pls make a separation between the part of 'HeatAndClimate' and the part of 'AppleMilkTea‘ (#38)


Many elements of heat and climate can be turned off with core.cfg and module.cfg. I have already stopped AMT2, but you can reproduce 'something similar' using config. Of course it is not perfectly identical.

―
