### ISSUE TITLE
Crash on stratup v2.5.9

### ISSUE THREAD

**Issue by AdaraChristine** [defeatedcrow/HeatAndClimateMod#45]
Forge 14.23.4.2749
HeatAndClimateLib_1.12.2-2.5.8
HeatAndClimateMod_1.12.2-2.5.9

**Sorry for more errors**
Crashes when Module.cfg     
     B:EnableMachineModule=false

https://pastebin.com/MkkbMGD5

**Comment by defeatedcrow** [comment]
Sorry, the module system contains bugs. It was fixed in 2b5b980.

**Comment by AdaraChristine** [comment]
THANK YOU for the fix
