### ISSUE TITLE
MC 1.12.2v2.5.10

### ISSUE THREAD

**Issue by ghost** [defeatedcrow/HeatAndClimateMod#46]
無限水源蛇口を開くとクラッシュします。

タンクを交換する為に蛇口を閉じないまま、
タンクを取った瞬間に落ちました。
他のMODを外して、無限水源蛇口のみで試したところ、
下に水を入れる容器がない場合にクラッシュする事がわかりました。

Automatic translation
↓

Crash when opening an infinite water source faucet.

Without closing the faucet to replace the tank,
I fell at the moment I took the tank.
I removed other MOD and tried it with infinite water source faucet only,
I found that it crashes when there is no container to put water in the bottom.

**Comment by defeatedcrow** [comment]
bf925a6 で修正されました。報告に感謝します。
t fixed at bf925a6. Thank you!

**Comment by ghost** [comment]
有難う御座いました。
無事にクラッシュして戻れなかったワールドに入ることが出来ました。

勘違いだったらごめんなさい。
イカと棒で、イカ串が作れたと思いますが、
現在は作れないようです。



Thank you very much.
I was able to enter the world which crashed safely and could not return.

I'm sorry if it was a misunderstanding.
I think that squid skewers could be made with squid and stick,
I do not seem to be able to make it now.

**Comment by defeatedcrow** [comment]
イカ串のレシピは2e0ef78で修正しました。
ご報告ありがとうございます。

It fixed at 2e0ef78.

**Comment by ghost** [comment]
修正有難う御座いました。
