### ISSUE TITLE
How to set Transfer portal?

### ISSUE THREAD

**Issue by Tronif** [defeatedcrow/HeatAndClimateMod#48]
Minecraft 1.12.2
MinecraftForge 14.23.4.2759
HeatAndClimateLib 1.12.2-2.5.8 (and 1.12.2-2.6.1)
HeatAndClimateMod 1.12.2-2.5.9 (and 1.12.2-2.6.1)

I want to know about Transfer portal.
According to the explanation,  "This device needs the ABSOLUTE temp or the liquid nitrogen."
So, I set temperature the ABSOLUTE using freezer. (use 256F torque)
then, Transfer portal set as adjacent to Freezer and conveyed other 256F torque to it with Stainless gear box.
Temperature is the ABSOLUTE, but Transfer portal isn't active yet.
what is wrong?
![2018-09-09_21 24 55](https://user-images.githubusercontent.com/40921102/45264597-02c0ce00-b47a-11e8-950b-6356a44c7d10.png)

--- JP ---
転送ポータルを使ってみようと思い、冷凍機を使ってABSOLUTE環境を作り転送ポータルを隣接させてみたのですが、しばらくすると見た目が暗くなり、転送ポータルの条件タブにマウスを置くと、"This device needs the ABSOLUTE temp or the liquid nitrogen." と表示されます。
（冷凍機、転送ポータルそれぞれに256Fトルクを伝達させています）
文面を見る限りABSOLUTE環境下なら液体窒素が無くても動作するようなのですが、何が悪いのでしょうか？

**Comment by Tronif** [comment]
Although I do not know what theory is, restart Minecraft client and enter game again, Transfer portal is active.
It solved myself. Please check this issue if you are as possible.

**Comment by defeatedcrow** [comment]
日本語話者かわからないので日英併記しておきます

タイルの読み込みから気候計算式を動かすまでに数秒ほどインターバルがあるので計算開始までは気温を読み込めなくなります
次回更新で動作を少し直します

There is a problem with this Tile now: a blank for climate calculation immediately after loading.
It is scheduled to be fixed in the next update. Thank you.

**Comment by Tronif** [comment]
日本語話者ですよー。
サイトがサイトですし、なるべく英語にしてみようとカタコトな拙い文で伝わるか不安になりつつ書いてます。
現象自体は対処方法がわかっていて、致命的ではありません。逆に言えば知らない人にはずっとわからないままですが。
次回更新を楽しみにまってますね。ありがとうございました。

Thank you for checking issue and I'm looking forward the next update.

**Comment by defeatedcrow** [comment]
転送ポータルのサーバ・クライアント同期処理に問題があったので、4afe2a2 にて修正しました。
