### ISSUE TITLE
The compression hopper turns into an oak tree

### ISSUE THREAD

**Issue by ghost** [defeatedcrow/HeatAndClimateMod#49]
· When compressing pine trees with a compression hopper, it turned into an oak tree.
Even other kinds of trees will become oak trees.

· I do not know the recipe of squid skewers.
I did not become a squid skewer no matter how it was placed.

・圧縮ホッパーで松の木を圧縮したら樫の木に変わってしまいました。
他の種類の木でも、樫の木になってしまいます。

・イカ串のレシピがわからないです。
どう配置してもイカ串にならなかったです。

**Comment by defeatedcrow** [comment]
92685b0 で修正しました。
ご報告ありがとうございます。

**Comment by ghost** [comment]
対応有難う御座います
