### ISSUE TITLE
Some Amulet do no effect in Bauble slot

### ISSUE THREAD

**Issue by AileRozy** [defeatedcrow/HeatAndClimateMod#50]
like I said in title, some amulet have no effect when placed in bauble's amulet slot.

here's the list for bugged amulet:
Amulet of Crystal(水晶のアミュレット)
Amulet of Starry Sky(夜空のアミュレット)

tested on version 2.6.0 and 2.6.1 in Minecraft 1.12.2, forge-1.12.2-14.23.4.2760
Mods:
Baubles-1.12-1.5.2
HeatAndClimateLib
HeatAndClimateMod

**Comment by defeatedcrow** [comment]
It fixed at https://github.com/defeatedcrow/HeatAndClimateLib/commit/680a6376a035c360b44538bdc12502cc4221f159
Thank you for the report!
