### ISSUE TITLE
Does it meet the condition even if it does not reach the reference value?

### ISSUE THREAD

**Issue by Tronif** [defeatedcrow/HeatAndClimateMod#51]
日本語話者です。

Minecraft 1.12.2
MinecraftForge 14.23.4.2759
HeatAndClimateLib 1.12.2-2.5.8
HeatAndClimateMod 1.12.2-2.5.9

The second stage of the heat exchanger is described as 32 F or more, but it seems to be the second stage even at 31.52 F.
In the case of connecting the shaft by extending it, it was the first step with 31.36 F.
Is it right that it is sufficient to satisfy the condition of 32F by rounding off decimal places?

細かいところですが質問させてください。
熱交換器の２段階目は32F以上と記載されていますが、31.52Fでも２段階目になるようです。
シャフトを一本伸ばして接続した場合は31.36Fで１段階目でした。

小数点以下を四捨五入して32Fという条件を満たせばよい、ということでしょうか？

**Comment by defeatedcrow** [comment]
日本語話者と判明しましたので、
翻訳コストが重くサポートに差し支えるため、以降は日本語のみで記載します。

以下の文章の英訳が必要な方がいましたらコメントにて申し出て下さい。
If you need some English translation of the following sentences please offer by comment.

---

すべてのトルクマシンの要求コストは表記よりも小さく設定されています。
ちょうどの量を要求すると、直付けでも動かなくなりプレイ感が損なわれるので、シャフト数本くらいの余裕をもたせています。
（初心者が触れた場合に、少し長くシャフトをのばした段階でコスト制限に気づくくらいのゆるさを想定しています。）
他の要素もおおむねカタログスペックよりもプレイヤーに対して甘く設定する方針です。

具体的な数値が知りたい場合は、ソースコードを直接参照して下さい。
（ソースコードが直接参照できる場所で、あえてプレイ上で検証して作者に確認を取る行動はあまり意味がないです。）

**Comment by Tronif** [comment]
回答ありがとうございます。
以前組み立てたボイラータービン＆熱交換器の設備でよくよく考えたらトルクが32 Fに足りてないんだけど２段階目に入ったのでなんでだろう？と思ったのが経緯でした。
コンセプトは理解しました。
