### ISSUE TITLE
Grow by magnetic chest

### ISSUE THREAD

**Issue by ghost** [defeatedcrow/HeatAndClimateMod#52]
· When throwing two or more items that can be stacked, it will increase as it is sucked into the magnetic chest.
In case of 2 pieces, it becomes 3 pieces.
In the case of 3, it becomes 6 with 3 + 2 + 1.

· Although it is a raw moon cake, there are two recipes.
Fabric + lotus root + sugar
Fabric + lotus root + sugar + egg
Which is correct?

· I do not know if I can write the request here.
It is a thing of UI that put three pieces of pot etc etc, but if it is put in hopper or belt conveyor, three will be buried and will not match with the recipe.
Can not we make a hopper that does not break the positional relationship?

・スタック出来るアイテムを2個以上放り投げると磁気チェストに吸い込まれると増えていきます。
2個の場合は3個になります。
3個の場合は3+2+1で6個になります。

・生の月餅ですが、レシピが二通りあります。
生地+蓮の実+砂糖
生地+蓮の実+砂糖+卵
どちらが正しいのでしょうか?

・要望をここに書いて良いのかわからないけど。
鍋等の3つ入れるUIの物ですが、ホッパーやベルトコンベアで入れると3つ埋まってしまってレシピと一致しなくなってしまいます。
位置関係を壊さないホッパーは作れないのでしょうか?

**Comment by defeatedcrow** [comment]
翻訳コストが重くサポートに差し支えるため、以降は日本語のみで記載します。
以下の文章の英訳が必要な方がいましたらコメントにて申し出て下さい。
If you need some English translation of the following sentences please offer by comment.

---

1. 磁気チェストの動作不良が再現できません。使用しているForgeおよびこのModのバージョンを明記して下さい。
（検証ができないので、判明するまで対応保留とします。）

2. どちらかが正しいのではなく**両方です**
　現実の月餅のレシピにゆで卵を入れるものと入れないものの2パターンあることの再現です。
　（アヒル卵が入手できないので鶏卵にしました）
　雰囲気要素なので好みで選択して下さい。

3. 要望のたぐいは受け付けていません。
　スロットの位置関係再現についてはレシピごとにですか？ケースバイケースでよしなにやってほしいということですか？あなた意図をマシン側から判別する実装方法が不明瞭です。
　実装の面でも特定マシン同士でのみ動作する特殊実装を要求され、必要な実装コストが重い（1週間～）のでお断りします。

　スロットをレシピに無関係なアイテムで埋めておけば同様の動作は可能だと思います。
　必要であればAMT2に実装されていたスロット埋め用のパネルの同等品を追加します。

**Comment by ghost** [comment]
1,
Forge1.12.2 - 14.23.4.2705
HeatAndClimateMod_1.12.2-2.6.1
HeatAndClimateLib_1.12.2-2.6.1



2,
分かりました。
有難う御座います。

3,
スロットに関係ないアイテムを入れると動かなくなってしまいます。
バターの自動生産をしたいのですが、
塩の生産のほうが早くて、スロットが塩で埋まってバターが作れなくなるのです。
自動化したくても、どうしても手動で行わないとどうにもならないので、
ちょっと面倒だなって思っただけです。
別になくても問題ないです。

**Comment by defeatedcrow** [comment]
1. 8e582be で修正されました。
　次回更新時に反映されます。

3. この文面から問題ないという判断はできないので、次回更新でスロット埋め用のアイテムを実装します。
　（明らかに不満が述べられていますし、パネル実装は難しくないので）

**Comment by defeatedcrow** [comment]
4afe2a2 にてスロットパネルを実装しました。

**Comment by ghost** [comment]
試してみましたがアイテムが無くなりました。
取り出し専用のスロットに、別のレシピのアイテムが２つ入っていると、
３つ目のアイテムが無くなっていきました。

ホッパーで放り込んで確認したらアイテムが無くなっていたので、
塩、緑茶、大豆肉で試しました。
塩と緑茶で埋められていると、大豆肉は作られず脱脂大豆が無くなっていきます。



・プレス金型の増殖
スタックした状態で、レシピ登録すると複数生成されますが、
手元にも1枚減った状態で残ります。
4枚で金床を使うと、3枚のプレス金型と4枚のレシピ登録済みのプレス金型になります。

・プレス加工機の欠陥
ホッパーで大量に材料を放り込むと、右のスロットにも入っていきます。

パン生地を作ろうと、小麦、水、塩を入れました。
初めは、生地と紙パックでしたが、
生地+小麦や水、塩になって紙パックが失われていきました。

プレス加工機の横に投入用のホッパー
下に回収用のホッパーをつけた状態です。


・ダイナマイトの不発
洞窟の天井に貼り付けて、爆破させようとしたのですが、
エフェクトが出るだけで爆発しませんでした。
下側からクリックすると爆発しないようです。

初見では爆発の方法が解らなくて、火を付けまくったりしてました。
回収しようとした時に爆発してビックリしました。
爆発したらダメージ受けるって思うのはクリーパーが原因か。


シルクタッチダイナマイトで、木の葉を爆破させると、
黒とピンク色のブロックになる。


昨日の時点で発見していたのですが、
更新に気づいて、確認していたら遅くなりました。
1.12.2-2.6.2でも発生したので報告しました。

**Comment by defeatedcrow** [comment]
タイトルであるGrow by magnetic chestの不具合は完了しましたよね？
閉じたissueを再利用しないで下さい
問題が解決していないのであれば再openの希望の旨を書き込んで下さい、また、別の不具合があるならば問題別にissueを立て直して下さい（修正後にcommitと紐付ける際に困ります）

issueやcloseの仕組みがわからないのであれば、gistで持ち込んでいただくか、非公式フォーラムを利用していただくほうが良いです
タイトルと異なる問題にissueを使い回されるのは迷惑です

**Comment by ghost** [comment]
すみません。

磁気チェストは直っていました。
鍋がアイテムを飲み込んで行きます。


ちゃんとテストプレーされたほうが宜しいのではないでしょうか?
何の問題もなければ何も書くこともなかったと思います。

では、さようなら。

**Comment by defeatedcrow** [comment]
私に対してだけではなく、他の利用者の迷惑になるので注意しています。
こちらとしては次回から直っていればいいという認識です。
こちらにミスが有ることと、あなたが筆談で意思疎通が十分にできないことやgithubの利用の勝手がわからないことは全くの別問題ですし、捨て台詞を吐いてこちらの指摘を無視するのであれば、この利用者が新しい問題行動を発生させたものと解釈します。

また、このModの利用ライセンスはそもそもが**現状が作りかけや不具合をふくむものであっても了承して利用する代わりに無料で利用できる**という趣旨ですから、不具合が存在すること自体をこちらに責任を求めたり、”ちゃんとテストプレーしていないコチラがおかしい”というのはお門違いです。
ユーザーは客ではありませんし、客のような応対やサービスを求めるならばライセンス内容から逸脱します。
（このModはカスタムMITですが、免責事項付きの他のオープンソースでも同様です）


内容について
＞ホッパーがアイテムを飲む
ホッパーの精密動作はそもそも仕様ではないので、現状以上の動作を要求するならば他の高精度のパイプ系Modを併用してください・
このModに求めるのであれば不具合報告ではなく仕様強化（Enhance）として新規にissueを立てて下さい。

＞ダイナマイトの不発
＞シルクタッチダイナマイトで、木の葉を爆破させると、黒とピンク色のブロックになる。
これは**バニラの仕様**です。

今回の内容に関して不具合とみられるものは含まれていません。
あなたがこうあるべきと感じるものがModの仕様であはりませんので、指摘の前に仕様の確認などをするようにしてください。

多少はこちらもエスパーして意図を汲みますが、問題行動が重なるとこちらも好意的に協力できなくなります。
ともかく次回からきちんとしていれば問題ないです。
