### ISSUE TITLE
遠隔RFモニターパネルのレシピが存在しない

### ISSUE THREAD

**Issue by HatTricK2358** [defeatedcrow/HeatAndClimateMod#54]
遠隔RFモニターパネルのレシピが存在せず、作成ができなくなっています。
連携要素と考え、RFやFEなどを使用するMOD(Thermal Expansion、Mekanismなど)を導入してみましたが、JEIにレシピが存在しないようでした。クリエイティブモードでモニターを出して使ったところ、モニター自体は問題なく動作しました。
これは仕様でしょうか、レシピ登録ミスでしょうか。

**Comment by defeatedcrow** [comment]
報告ありがとうございます。
4afe2a2 で修正しました。
