### ISSUE TITLE
Exception in server tick loop with Pam's HarvestCraft

### ISSUE THREAD

**Issue by abslon** [defeatedcrow/HeatAndClimateMod#57]
I'm running ftb revelation with some additional mods including this.
It was okay with the client side, but somehow it crashes in the server :(
I'm leaving with the crash report. 
https://pastebin.com/pvRmr67G

**Comment by defeatedcrow** [comment]
It fixed at https://github.com/defeatedcrow/HeatAndClimateLib/commit/7745b43f96ee66cd610ea0aab866059fdf0883c0 .
Thank you!
