### ISSUE TITLE
 Added crops do not become containers with compression hoppers

### ISSUE THREAD

**Issue by ghost** [defeatedcrow/HeatAndClimateMod#58]
Walnuts, red pepper etc. are discharged as it is

くるみ、とうがらし等がそのまま排出されます

**Comment by defeatedcrow** [comment]
不具合について具体的な記述をお願いします
5W1Hが大崩壊しているので何の話か理解不能です

どういう結果を期待して、何のブロックをどう動作させた後にどこからクルミと唐辛子がどこから排出され、そのままの状態とは具体的にどのような状態を指していますか？
