### ISSUE TITLE
Hope to add a tooltip for shitirin（七輪）

### ISSUE THREAD

**Issue by TartaricAcid** [defeatedcrow/HeatAndClimateMod#6]
Those players who come from other country may not know what this is.

**Comment by defeatedcrow** [comment]
OK. I will consider it.
Alternatively, it is also possible to change to a different name. (Example: charcoal stove)

**Comment by TartaricAcid** [comment]
But I think `shitirin` is better, it can make us know more about Japanese culture.

**Comment by defeatedcrow** [comment]
I see.
So I guess adding a tooltip is good idea. I'll try it.
Thank you!
