### ISSUE TITLE
Carbide street lights and lanterns are missing from creative tab and JEI

### ISSUE THREAD

**Issue by taisa-vol12** [defeatedcrow/HeatAndClimateMod#60]
カーバイドの街灯とランタンがクリエイティブタブとJEIから見つからないです。
JEIと検索タブの両方で「カーバイド」と検索にかけても見つかりませんでした。
カーバイドの用途をレシピを参照したところ街灯とランタンのレシピはありました。

導入mod
forge-14.23.4.2760

HeatAndClimateLib_1.12.2-2.6.3
HeatAndClimateMod_1.12.2-2.6.3
jei_1.12.2-4.11.0.212
jeiintegration_1.12.2-1.5.1.36

**Comment by defeatedcrow** [comment]
I am grasping, but the cause is unknown.

こちらでも問題は把握していますが原因不明です
ブロックやアイテムの登録処理、レシピ登録ともに正常に通っているので、クリエイティブタブの登録だけが弾かれている（これも登録処理は行っている）状況です
修正には時間がかかると思います


できれば次回からは（タイトルだけでいいので）英語でお願いします
現在報告済みのissue一覧として海外の方も確認するために公開している場所なので……

**Comment by defeatedcrow** [comment]
v2.6.4 で修正しました。
