### ISSUE TITLE
get walnut sapling from dates tree.

### ISSUE THREAD

**Issue by Tronif** [defeatedcrow/HeatAndClimateMod#61]
Minecraft : 1.12.2
HeatAndClimateLib : 2.6.2
HeatAndClimateMod : 1.12.1_2.6.2

デーツの葉を破壊したところ、クルミの苗木がでてきました。

**Comment by defeatedcrow** [comment]
It fixed ib f7868ea. It will be reflected in next update.

コミット f7868ea にて修正されています。次回更新に反映予定なので、しばらくお待ち下さい。
