### ISSUE TITLE
Startup crash with latest Heat and Climate

### ISSUE THREAD

**Issue by raltus** [defeatedcrow/HeatAndClimateMod#63]
The lib jar works fine but when I install the other it fails to start. Since I updated a few before launching it took a moment to find the issue. I have the latest version of java, but not the latest version of forge because of a conflict with the latest forge and another mod.

crash log
https://gist.github.com/raltus/70bab1a953a05acc13a56c745f9b05ab

**Comment by defeatedcrow** [comment]
Thank you for the report. It was fixed at f62b5b1.
