### ISSUE TITLE
[1.12.2] duplicate different recipe exist, but It can craft the same item.

### ISSUE THREAD

**Issue by Tronif** [defeatedcrow/HeatAndClimateMod#65]
HeatAndClimateLib : 2.6.4
HeatAndClimateMod : 1.12.2_2.6.6 (but Looking Mod Option in Game, displayed 1.12.1_2.6.6)
JEI : 4.13.1.220

たまたま見つけたやつです。
添付したスクリーンショットのようにJEIでレシピを見てみたら、Raw Mooncake で要求アイテムの異なる２つのレシピが存在します。また、Raw Crostata は同じ要求アイテムでレシピが２つ表示されるようです。ほかの料理レシピでも同じようなことが起きてるのかも知れませんが、何分量が多いので２つ程度例として挙げさせていただきました。
JEIで見て、コスト安くて作れるならこっちでいいやって思うくらいでしたが、気になったので投稿させていただきました。
MODのバージョンをHeatAndClimateModだと1.12.2_2.6.2からとばして1.12.2_2.6.6に変更したのでそれもダメだったのかな？とも思ってみたりしてます。

![hac_](https://user-images.githubusercontent.com/40921102/46821779-a7f5fb80-cdc4-11e8-9c8f-597b865d5aeb.PNG)

**Comment by defeatedcrow** [comment]
出先なので、日本語のみ
あとで英訳を追記します

仕様です
アイテムのレシピは、アイテム一つに付き一つだけ用意されているわけではありません
レシピの複数実装をDupeと呼称することには疑問があります、アナザーレシピは古くから多数のmodで使われる手段です（これを体系化したものが鉱石辞書システムですからね）

アイテムの入手機会（ランダム性のあるバイオーム生成に依存するmodであることの考慮です）、複数のプレイスタイルへの対応（ピースフル限定やネザー永住などの特殊ケースも多少想定しています）、コンフィグを変えた場合に入手手段が変化する、文化や思想への対応（ベジタリアン用レシピなど）

画像のものは、現実に「鶏卵orピータンを入れる月餅」と「卵なし月餅」のパターンが実在するために用意されているレシピです
プレイヤーの任意選択で選べるようになっています


尚、クラフトレシピはjson化されておりassetsフォルダに含まれる内容です
ストラクチャーやルートテーブルjsonと同様の手法でリソースパックとして改変可能と思いますので
気になる点があればプレイヤー自身が自力で改変すると良いと思います

**Comment by defeatedcrow** [comment]
ちなみに全く同内容でレシピが重複しているものも、同内容ではありません

こちらは、Libの付属機能によって、辞書対応していないレシピを自動で変換し、鉱石辞書対応レシピを追加するシステムによるものです

不要であればcore.cfgのコンフィグからオフにしてください

**Comment by Tronif** [comment]
了解しました。ありがとうございます。
