### ISSUE TITLE
Squid doesn't drop raw squid

### ISSUE THREAD

**Issue by Dinocanid** [defeatedcrow/HeatAndClimateMod#67]
If I kill a squid it doesn't drop raw squid for me, only ink sacs.

**Comment by defeatedcrow** [comment]
Need to overkill by player.

**Comment by Dinocanid** [comment]
So raw squid is only dropped after 8 hearts of damage?

**Comment by defeatedcrow** [comment]
It requires 10F damage (5 hearts) or more. Then it will be dropped at 50% probability.

**Comment by Dinocanid** [comment]
Ok, thanks!
