### ISSUE TITLE
Smelting recipes 

### ISSUE THREAD

**Issue by ghost** [defeatedcrow/HeatAndClimateMod#69]
Vanilla furnace smelting recipes (dust to ingot) are currently hardcoded. is it possible to change to .json recipes?

**Comment by defeatedcrow** [comment]
The Jsonification of smelting recipes is not yet implemented in vanilla 1.12.2. Is it already supported by forge?
Do you require me to modify the core system that vanilla or forge does not support? Do you understand what it means???

HaC smelting recipe conforms to forge's system. These can be removed from the game by modding ways. You can remove the recipe by yourself, with the help of forge and vanilla code.
(FurnaceRecipes.instance().getSmeltingList() can be used to get the Map containing the recipe. You can operate it.)
Do you call this "hard code"? 

I am grumpy. For this matter, I will not help you.

**Comment by ghost** [comment]
Sorry, hardcoded means not configurable.
I did not realize forge recipe system does not apply to furnaces. 
You are right in being grumpy. I should have done further research.
Thanks for the response. Closing issue.
