### ISSUE TITLE
Do we have a Discord server?

### ISSUE THREAD

**Issue by AileRozy** [defeatedcrow/HeatAndClimateMod#71]
I want to help zh_tw translate and I think it's best to have a Discord server, that you can release lang file at there first and let translators translate it, then release new update to keep every lang file up to date every patch.

**Comment by 0999312** [comment]
你是不知道日本人没有用Discord的习惯的吗。。。。。。
尤其是日本MC圈这边。。。。。。

**Comment by defeatedcrow** [comment]
I will not use any platform other than github for project management.
