### ISSUE TITLE
Recipe issue with Mekanism 1.12.2-9.4.13.349

### ISSUE THREAD

**Issue by AileRozy** [defeatedcrow/HeatAndClimateMod#73]
Yep, there're same problem like before again.

Recipe for Garniertie/Nickeline/Sphalerite to Dirty dust/Shard/Clump can not be seen in JEI and can not craft with mekanism machine.
not test with Crystal.

Mod list:
forge-1.12.2-14.23.5.2768
jei_1.12.2-4.13.1.222
HeatAndClimateLib_1.12.2-2.7.1
HeatAndClimateMod_1.12.2-2.7.2
Mekanism-1.12.2-9.4.13.349
MekanismGenerators-1.12.2-9.4.13.349
MekanismTools-1.12.2-9.4.13.349

**Comment by defeatedcrow** [comment]
It fixed at d1b8b73. Thank you!
