### ISSUE TITLE
Crash Between Gregic Additions mod and Heat and Climate

### ISSUE THREAD

**Issue by ghost** [defeatedcrow/HeatAndClimateMod#76]
with 1.12.2, GregTech Community edtion's addon, Gregic Addtions, it makes crash.
Gregicadditions 1.3.0 and heat and climate 2.7.4

**Comment by defeatedcrow** [comment]
In what circumstances did it crash? Do you have a crash report?
There is not any information needed to fix it.

**Comment by defeatedcrow** [comment]
Looking at the crash report "You did not present to me", it looks unrelated to HAC.
Here, I found a necessary report (and a your very rude misunderstanding). I will not cooperate in solving this matter. It is irrelevant.
https://github.com/EmosewaPixel/GregicAdditions/issues/38

**Comment by ghost** [comment]
i'm sorry that i misunderstood and miss word choosen, i'm really sorry.

**Comment by ghost** [comment]
I apologize that my rude speech and i misunderstood about the mod, 
i wasn't fully researched about mod and i mentioned HAC as a TAN addon, it was my big fault,
i immiedatley changed that name, and i really wants to say sorry, it was my big mistake, i'm really sorry.
i can't imagine how you feel upset and i really sorry, what i did was really insult about to you, and i'm really reflecting what i did, reflect on myself, really sorry. sincelry.

**Comment by ghost** [comment]
> Looking at the crash report "You did not present to me", it looks unrelated to HAC.
> Here, I found a necessary report (and a your very rude misunderstanding). I will not cooperate in solving this matter. It is irrelevant.
> [EmosewaPixel/GregicAdditions#38](https://github.com/EmosewaPixel/GregicAdditions/issues/38)

i'm really sorry i apologize

**Comment by defeatedcrow** [comment]
I already pointed out that HaC is **IRRELEVANT** to this problem.

>java.lang.ClassCastException: gregtech.api.unification.material.type.IngotMaterial cannot be cast to gregtech.api.unification.material.type.GemMaterial

This part of the crash report shows that there was a mistake in the implementation of Gregtec API included in GregicAdditions. This is a single crash of GregicAdditions.
Therefore, HaC has no part to fix. You seem to be mistaking a person to report.

**Comment by ghost** [comment]
I'm really sorry. 
It was my mistake, all mistake, including that not report with report.txt and other all things.
I saw the same crash report 
when i only put them together, so i just thought i have to report both. 
I ignored report. I had to search more, 
thank you to correct my fault.
I`m really sorry.
Now i fully recognize what the problem is. I was visited wrong person.
And i will not gonna do something like this happening. I promise. I'm really sorry.

**Comment by ghost** [comment]
> In what circumstances did it crash? Do you have a crash report?
> There is not any information needed to fix it.

It was my mistake that didnt upload crash reports.
And i didnt give any property information. I really sorry. 
From now, with next time, i'll do more advanced question. Really sorry.

/I found similar case 
what i didnt mentioned property information. From your mention, i now can understand what i have to change.
