### ISSUE TITLE
Ice not melting in summer

### ISSUE THREAD

**Issue by radum706** [defeatedcrow/HeatAndClimateMod#78]
Hello. i have Heat and Climate in my modpack and is amazing! but i have a small issue, the frozen lake or ocean won't melt in summer, and it froze in first winter. Am I missing something?

**Comment by defeatedcrow** [comment]
Hello, radum706.
It is currently working correctly. Ice block has the temperature of COLD, and its own coldness prevents melting. However, this specification is unnatural and hinders play. We will improve that in the next update.
Thank you.

**Comment by defeatedcrow** [comment]
Fixed at https://github.com/defeatedcrow/HeatAndClimateLib/commit/a82ee0036b2b852638d0f624bdd5c8e0fd952fd3

**Comment by radum706** [comment]
it is possible to do the same with the snow? thank you!

**Comment by defeatedcrow** [comment]
For snow, it is not subject to HaC system by default config. Please edit "Tick Update Blacklist" in core.cfg and remove snow from blacklist.

**Comment by radum706** [comment]
thank you!
