### ISSUE TITLE
Fuel gas via Blaze Catalyst not working?

### ISSUE THREAD

**Issue by craft90** [defeatedcrow/HeatAndClimateMod#79]
I've been playing around with how to make the synthetic leather through the synthetic drops, however I ran into a problem when making the fuel gas. For some reason the Ethanol/Sulfuric Acid via Blaze catalyst doesn't seem to work. Both tanks are filled up, it got power (a devoted 128 torque) and the heat is correct but still nothing is being produced. The other way to make fuel gas via carbide is working properly. Just not the Blaze reaction. I'm running heat & climate mod version 2.7.5 off the Curse launcher in a private modpack.

**Comment by defeatedcrow** [comment]
The problem occurred due to a previous bug in Lib. It has already been fixed.
https://github.com/defeatedcrow/HeatAndClimateLib/commit/348dbb51afdcec426197dbcfc6d41eea40dc6a4c

Please update HeatClimateLib to latest (v2.7.5).

**Comment by craft90** [comment]
There's no 2.7.5 version of the lib files on Curse though.

**Comment by defeatedcrow** [comment]
Oh, sorry! Soon it will be updated.
