### ISSUE TITLE
[1.12.2]大きい倍の食べ物のバグを取る

### ISSUE THREAD

**Issue by cqzz1cn** [defeatedcrow/HeatAndClimateMod#80]
機械の翻訳をしてください
あなたの作った作品“HeatAndClimate”と“AppleMilkTea2”が大好きです
しかし、使用中の2つのmodには、同じような深刻な問題が発生しました。
世界中に置かれた一つの食べ物は、同時に左右のキーを押して、2倍の食べ物を得る。
キーを左右するすべてのものが上記の問題になっています。
これは私が好きなあなたの作品が多くのサーバーに使用できないことを招いた。

Forgive me for using machine translation
I love your works "Heat AndClimate" and "Apple Milk Tea2"
But in the process of using the two mods, the same serious problems arise:
If you place a food in the world and press the left and right buttons at the same time, you will get twice as much food.
All the items that can be taken by the left and right keys have the above problems.
This leads to my favorite works of yours not being used on many servers.

**Comment by cqzz1cn** [comment]
In order to contact you, I used an infrequent mailbox when registering. (Because QQ mailboxes are not supported for registration)
If you want to know more, I'd be happy to help you with the test. I will leave my usual contact information:
1.QQ: 2769595775
2. Mobile phone number: +86 17705909301
3. My MCBBS ID is cqzz1. (http://www.mcbbs.net/portal.php)

**Comment by defeatedcrow** [comment]
It fixed at https://github.com/defeatedcrow/HeatAndClimateLib/commit/0646a8bf80a0e481792a412054be11280a834312
I tested it on my own server. The Dupe bug seems to have been fixed.
Thank you!
