### ISSUE TITLE
送風機のレシピを間違えるとクラッシュ

### ISSUE THREAD

**Issue by YUPPUN** [defeatedcrow/HeatAndClimateMod#82]
Minecraft : 1.12.2
Forge : 14.23.5.2768
HaCLib : 3.2.2.353
HaC : 1.12.1_2.7.6
にて、送風機のレシピの"鉄"と"レッドストーンダスト"の位置を逆にすると最後のクラフトマスをアイテムで埋めた瞬間クラッシュする問題を見つけました。環境によるものでしたら申し訳ございません。

鉄 = 鉄インゴット
赤 = レッドストーンダスト
真 = 真真鍮の回転子

正：
鉄赤鉄
赤真赤
鉄赤鉄

クラッシュの発生したレシピ：
赤鉄赤
鉄真鉄
赤鉄赤

よろしくおねがいします。

**Comment by defeatedcrow** [comment]
クラッシュレポートを提示してください。
あなたの推測した原因が実際にクラッシュの原因であるか、その点から検証が必要です

（基本、手元のデバッグ環境で再現性を取ってからでないと修正作業が出来ないので、ユーザーの推定や予想で動くことはできないです）

**Comment by defeatedcrow** [comment]
追記
.353というHaCLibは存在しません。LibのバージョンカウントはHaCと同じ書式であり、そのようなバージョンではないはずです。
私以外の人間が作成した改造版HaCLibであればサポートはしません。

（おそらくJEIのバージョンだと思われますが、JEIのそのバージョンは内部仕様変更中のβ版ですのでHaCはまだ追従していません。安定版を使うか、不安定を承知で自己責任で使ってください）

**Comment by YUPPUN** [comment]
バージョン表記の誤字失礼しました。 HaCLibは2.7.7になります。
https://pastebin.com/mQCNjSQR
クラッシュレポートになります。CraftingEX環境下で起こりました。
通常の作業台では再現できませんでした。
CraftingEX環境下にて他のレシピで同様の間違え方をしても再現できませんでした。

**Comment by defeatedcrow** [comment]
**java.lang.IndexOutOfBoundsException: Index: 6, Size: 6**
    at java.util.ArrayList.rangeCheck(ArrayList.java:653)
    at java.util.ArrayList.get(ArrayList.java:429)
    at net.minecraft.util.NonNullList.get(SourceFile:44)
    at net.minecraft.item.crafting.ShapedRecipes.func_77573_a(ShapedRecipes.java:113)

クラッシュレポートを拝見しましたが、ClaftingEXのレシピチェック時にクラッシュしているようですし、うちのmodは無関係に見えますね
（ちなみにHaCのレシピはJsonで追加していますので独自のシステムは使っていないです）

私はClaftingEXの作者ではなく、修正は出来ないので、先方に報告してください。

**Comment by YUPPUN** [comment]
了解しました。お手数おかけして申し訳ございません。
