### ISSUE TITLE
Null pointer exception when using 3.0.0's death-preventing charm

### ISSUE THREAD

**Issue by Prunoideae** [defeatedcrow/HeatAndClimateMod#85]
https://paste.ubuntu.com/p/CdfR2wfWRD/

It comes when I'm trying to kill myself by soaking in lava to test if the charm worked out or not, but then the game crashed.
HAC is much more balanced in the new version ; ), but I wonder if there's a way to get consistent wind blessing effect more than just using a card every 5 minutes? Remembering to use cards is sometime a difficult task :-P

**Comment by defeatedcrow** [comment]
Thank you for your report! I will investigate this matter soon.

About the wind blessing, magical jewel boots can be constantly effective.

**Comment by defeatedcrow** [comment]
Fixed in 688dbafd1ed9907e258846e9135a29afc7f39484
