### ISSUE TITLE
Hammer mill recipe error

### ISSUE THREAD

**Issue by Prunoideae** [defeatedcrow/HeatAndClimateMod#86]
![image](https://user-images.githubusercontent.com/24620047/54807573-9c362b80-4cb8-11e9-9deb-c8a436835d6f.png)
![image](https://user-images.githubusercontent.com/24620047/54807582-a1937600-4cb8-11e9-8fa5-7219c79a9833.png)

**Comment by defeatedcrow** [comment]
It fixed in https://github.com/defeatedcrow/HeatAndClimateMod/commit/30025249cd0e263d3e5afc76a8620fd0ec1b16b4 .
Thank you!
