### ISSUE TITLE
Could you please add something like removeRecipe?

### ISSUE THREAD

**Issue by Prunoideae** [defeatedcrow/HeatAndClimateMod#90]
The list field in recipe registry class are private and there's no public function to change it, using getRecipeList just returned a copy of the list and there seemed to be no way to access the list.
So, is there anything I can use to remove some elements in the recipe list? If you feel it's unpleasing to remove HAC original recipe (Like the guy called ReikaKalseki) then just close this issue :-P
btw, the tweaker mod is published on CurseForge :
https://minecraft.curseforge.com/projects/heat-climate-tweaker
I think it could satisfy those whose brains are occupied with the love of heavy-tweaked mod-packs.

**Comment by defeatedcrow** [comment]
About the recipe lists, it is simply set in a private field to prevent my own operation accident. So I can meet your needs. Those prototypes will be added to the API in a few days.

I welcome people who try to modify or adjust this mod on their own. About tweaker mod, I had received a request in the past but was simply unable to make it for my abilities and free time.
Thank you for your project.

**Comment by defeatedcrow** [comment]
removerecipe api have added at https://github.com/defeatedcrow/HeatAndClimateLib/commit/582e15f4b837d07be61586a35c58daf79ed74967 .
It's available on https://github.com/defeatedcrow/HeatAndClimateLib/releases/tag/v3.0.2.
