### ISSUE TITLE
Patchouli Suggestion

### ISSUE THREAD

**Issue by captcookie** [defeatedcrow/HeatAndClimateMod#91]
Suggestion: Use Patchouli

https://minecraft.curseforge.com/projects/patchouli?gameCategorySlug=mc-mods&projectID=306770

A lot of mods are integrating their mod with this guidebook feature. I feel like it would be a great way to walkthrough the progression of your mod. It's simply an idea.

**Comment by defeatedcrow** [comment]
It is a very good mod, but now I can not afford to write a huge amount of text (EN, JP). I'll consider it but its priority is low.

**Comment by barrowisp** [comment]
I've made a few Patchouli books and would be interested in helping with this.  Perhaps I wouldn't complete the book, but I'd very much want to do the parts most relevant to a player starting a new world with this mod: first machines to build, etc.  Would you like me to get started on one, and post here when I have something ready for you to look over?

**Comment by defeatedcrow** [comment]
I have already started another way as a more description on this mod. There are no plans to make it using Patchouli.
