### ISSUE TITLE
Niter Ore, Sulfur Ore, and Large Black Ore problems 

### ISSUE THREAD

**Issue by dave75vgnut** [defeatedcrow/HeatAndClimateMod#92]
I'm using HeatAndClimateMod_1.12.2-3.0.4.
When mining niter ore I get sulfur, & I get niter when mining sulfur ore.
As to large black ore it shows as black color, but is labeled large red ore, before and after mining it just needs name fix.
Those are the only problems I found so far, will inform you if I find anymore.

**Comment by defeatedcrow** [comment]
Thank you for your report!
The reported issues have been fixed at https://github.com/defeatedcrow/HeatAndClimateMod/commit/bfda5531a05262bc975314bcfedb6170709c6682 .
