### ISSUE TITLE
服・ハーフブロックのテクスチャバグ

### ISSUE THREAD

**Issue by NattoLover15** [defeatedcrow/HeatAndClimateMod#97]
forge-1.12.2-14.23.5.2768
HeatAndClimateLib_1.12.2-3.0.3
HeatAndClimateMod_1.12.2-3.0.7

一部の服のカラーバリエーションにテクスチャバグがあるようです。
![Clothing](https://user-images.githubusercontent.com/50796537/57982933-d5a3d100-7a86-11e9-9885-c1dd984204ea.png)
左からTシャツ(magenta)・Tシャツ(lightBlue)・花柄のスカート(lime)

半ブロックが重ならないのは仕様かと思いますが、上下2ブロックに設置した際に下面のテクスチャが一部透けてしまうようです。
![Slab](https://user-images.githubusercontent.com/50796537/57982937-dfc5cf80-7a86-11e9-9ef9-1cf1f735829d.png)
一部の半ブロックが同じ上付き半ブロックの上に設置された際に発生するようです(ランプは下付きも含む)。

**Comment by defeatedcrow** [comment]
- ○ 服のテクスチャ: 修正しました。
せっかくなのでダブレットにもカラバリ増やしておきます。

- ハーフブロック: 過去にも何度かissueを受けていますが完全には直っていません。修正に時間がかかると思います。
（マイクラは描画処理の軽減のために、固形ブロック同士の接続部分など不要な面の描画を省く機能があるのですが、そのへんの設定ミスで機能が暴発しています。作者の頭が悪すぎて条件分岐処理が狂っているのが原因なので、要修正ですが難航しています。）

**Comment by defeatedcrow** [comment]
Fixed in afd662a514877e4c95e71e999858077a2466f704

**Comment by NattoLover15** [comment]
素早い対応ありがとうございます。
