### ISSUE TITLE
合金入手の進捗が解除できない

### ISSUE THREAD

**Issue by NattoLover15** [defeatedcrow/HeatAndClimateMod#98]
合金入手の進捗が解除できない

forge-1.12.2-14.23.5.2768
HeatAndClimateLib_1.12.2-3.0.3
HeatAndClimateMod_1.12.2-3.0.7

「合金を手に入れる2」・「新素材」・「現代科学への道」の3つの進捗が、対応金属ブロックを入手しても解除できません。
旧バージョン(3.0.4)以前で入手したものなら解除できるようですが、
現バージョンでは気候精錬・クラフトのどちらで入手しても解除できない状態です。

**Comment by defeatedcrow** [comment]
Fixed in afd662a514877e4c95e71e999858077a2466f704
