### ISSUE TITLE
一部のレシピの不足・アイテム増殖

### ISSUE THREAD

**Issue by NattoLover15** [defeatedcrow/HeatAndClimateMod#99]
forge-1.12.2-14.23.5.2768
HeatAndClimateLib_1.12.2-3.0.3
HeatAndClimateMod_1.12.2-3.0.7

アイテムを増殖/変換できるレシピが存在するようです。

**増殖**
プリズマリンの欠片:4 → プリズマリン:1 → プリズマリンの欠片:9
エンドストーン:4 → エンドストーンレンガ:4 → エンドストーン:16(石臼)

**変換**
鉄粉末:8+石墨の粉:1 → 鉄粉ブロック:1 → 鉄粉末:9/脆い鋼ブロック:1 → 鉄インゴット:9
磁鉄鉱粉末:7+天青石:1+石灰:1 → 磁鉄鉱粉ブロック:1 → 磁鉄鉱粉末:9

**不足**
工具鋼の大鎌・ブレックファスト・生クリームのドロップはレシピがJEIで確認できないようですが、
現在はクリエイティブ専用アイテムという事でしょうか?

また、これは質問なのですが、鉛粉ブロックが存在しないのは仕様でしょうか?
特に必要という訳では無いのですが、基本的な金属で1つだけ見当たらないようなので。

**Comment by defeatedcrow** [comment]
- ○ プリズマリン、エンドストーン: 直します

- 鉄・磁鉄鉱粉の変換
このModにおいて鉄・磁鉄鉱の粉末は大量に生成し、倍化手段も追加していますので、有限資源である石炭ジェム・天青石等の宝石類よりもMod内のコストは相当低いです。
（内部設定として各種素材に価値の内部値を設定して比較しています。プレイヤーには公開しませんが、1チャンクの入手数の期待値に作成コストを足し算したような値になっているので、入手しづらく、加工に必要なマシンTierが高く、プレイヤーの操作が煩雑なほど高いイメージです。）
より高価値のアイテムを低価値アイテムに変換するプロセスをDupeとはみなしていません。

- ○ 工具鋼の大鎌: 修正します

- ○ ブレックファスト: 問題が再現できません。ただ予想はつくので対策はとっておきます。

- 生クリーム: レシピを削除済みのボツアイテムです。主に1.10からワールドを引き継いだプレイヤーのアイテムがロストしないように登録だけ残してあるものなので、新規のユーザーはクリエタブのみが入手方法です。

**Comment by defeatedcrow** [comment]
Fixed in afd662a514877e4c95e71e999858077a2466f704
